# This file was auto-generated by Fern from our API Definition.

import typing
from json.decoder import JSONDecodeError

from ..core.api_error import ApiError
from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.http_response import AsyncHttpResponse, HttpResponse
from ..core.jsonable_encoder import encode_path_param
from ..core.parse_error import ParsingError
from ..core.pydantic_utilities import parse_obj_as
from ..core.request_options import RequestOptions
from ..core.serialization import convert_and_respect_annotation_metadata
from ..types.team import Team
from ..types.team_based_permissions_update import TeamBasedPermissionsUpdate
from ..types.team_field_settings_update import TeamFieldSettingsUpdate
from ..types.team_list_response import TeamListResponse
from ..types.team_member_create import TeamMemberCreate
from ..types.team_member_update import TeamMemberUpdate
from pydantic import ValidationError

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class RawTeamClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._client_wrapper = client_wrapper

    def create_team(
        self,
        *,
        name: str,
        members: typing.Sequence[TeamMemberCreate],
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[Team]:
        """
        Creates a team with an initial member roster.

        Parameters
        ----------
        name : str
            Display name for the new team.

        members : typing.Sequence[TeamMemberCreate]
            Initial team members. The authenticated creator must be included.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[Team]
            OK
        """
        _response = self._client_wrapper.httpx_client.request(
            "v2/teams",
            method="POST",
            json={
                "name": name,
                "members": convert_and_respect_annotation_metadata(
                    object_=members, annotation=typing.Sequence[TeamMemberCreate], direction="write"
                ),
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    Team,
                    parse_obj_as(
                        type_=Team,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def get_team(self, team_key: str, *, request_options: typing.Optional[RequestOptions] = None) -> HttpResponse[Team]:
        """
        Returns a team by key.

        Parameters
        ----------
        team_key : str
            Key for the team to return.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[Team]
            OK
        """
        _response = self._client_wrapper.httpx_client.request(
            f"v2/teams/{encode_path_param(team_key)}",
            method="GET",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    Team,
                    parse_obj_as(
                        type_=Team,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def update_team(
        self,
        team_key: str,
        *,
        name: typing.Optional[str] = OMIT,
        sharing_restricted_to_team: typing.Optional[bool] = OMIT,
        automatically_approve_join_requests: typing.Optional[bool] = OMIT,
        automatically_send_invoice_emails: typing.Optional[bool] = OMIT,
        emails_to_send_invoice_to: typing.Optional[typing.Sequence[str]] = OMIT,
        members: typing.Optional[typing.Sequence[TeamMemberUpdate]] = OMIT,
        contact_org_list_permissions: typing.Optional[
            typing.Dict[str, typing.Optional[TeamBasedPermissionsUpdate]]
        ] = OMIT,
        contact_settings: typing.Optional[TeamFieldSettingsUpdate] = OMIT,
        organization_settings: typing.Optional[TeamFieldSettingsUpdate] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[Team]:
        """
        Updates a team by key. Omitted body fields are left unchanged.

        Parameters
        ----------
        team_key : str
            Key for the team to update.

        name : typing.Optional[str]
            New display name for the team.

        sharing_restricted_to_team : typing.Optional[bool]
            Whether sharing outside the team is restricted.

        automatically_approve_join_requests : typing.Optional[bool]
            Whether requests to join the team are approved automatically.

        automatically_send_invoice_emails : typing.Optional[bool]
            Whether invoice emails are sent automatically for this team.

        emails_to_send_invoice_to : typing.Optional[typing.Sequence[str]]
            Complete replacement for additional invoice-recipient email addresses. Omit to leave unchanged; send an empty set to clear.

        members : typing.Optional[typing.Sequence[TeamMemberUpdate]]
            Complete replacement roster. Omit this property to leave membership unchanged.

        contact_org_list_permissions : typing.Optional[typing.Dict[str, typing.Optional[TeamBasedPermissionsUpdate]]]
            Permission updates keyed by system list. Omitted list entries remain unchanged.

        contact_settings : typing.Optional[TeamFieldSettingsUpdate]
            Complete replacement for the team's custom contact fields. Omit to leave unchanged.

        organization_settings : typing.Optional[TeamFieldSettingsUpdate]
            Complete replacement for the team's custom organization fields. Omit to leave unchanged.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[Team]
            OK
        """
        _response = self._client_wrapper.httpx_client.request(
            f"v2/teams/{encode_path_param(team_key)}",
            method="POST",
            json={
                "name": name,
                "sharingRestrictedToTeam": sharing_restricted_to_team,
                "automaticallyApproveJoinRequests": automatically_approve_join_requests,
                "automaticallySendInvoiceEmails": automatically_send_invoice_emails,
                "emailsToSendInvoiceTo": emails_to_send_invoice_to,
                "members": convert_and_respect_annotation_metadata(
                    object_=members, annotation=typing.Optional[typing.Sequence[TeamMemberUpdate]], direction="write"
                ),
                "contactOrgListPermissions": convert_and_respect_annotation_metadata(
                    object_=contact_org_list_permissions,
                    annotation=typing.Optional[typing.Dict[str, typing.Optional[TeamBasedPermissionsUpdate]]],
                    direction="write",
                ),
                "contactSettings": convert_and_respect_annotation_metadata(
                    object_=contact_settings, annotation=typing.Optional[TeamFieldSettingsUpdate], direction="write"
                ),
                "organizationSettings": convert_and_respect_annotation_metadata(
                    object_=organization_settings,
                    annotation=typing.Optional[TeamFieldSettingsUpdate],
                    direction="write",
                ),
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    Team,
                    parse_obj_as(
                        type_=Team,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def list_current_users_teams(
        self,
        *,
        limit: typing.Optional[int] = None,
        page: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[TeamListResponse]:
        """
        Lists the teams the current user belongs to, newest first.

        Parameters
        ----------
        limit : typing.Optional[int]
            Number of items to return.

        page : typing.Optional[int]
            Zero-based page number

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[TeamListResponse]
            OK
        """
        _response = self._client_wrapper.httpx_client.request(
            "v2/users/me/teams",
            method="GET",
            params={
                "limit": limit,
                "page": page,
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    TeamListResponse,
                    parse_obj_as(
                        type_=TeamListResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)


class AsyncRawTeamClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._client_wrapper = client_wrapper

    async def create_team(
        self,
        *,
        name: str,
        members: typing.Sequence[TeamMemberCreate],
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[Team]:
        """
        Creates a team with an initial member roster.

        Parameters
        ----------
        name : str
            Display name for the new team.

        members : typing.Sequence[TeamMemberCreate]
            Initial team members. The authenticated creator must be included.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[Team]
            OK
        """
        _response = await self._client_wrapper.httpx_client.request(
            "v2/teams",
            method="POST",
            json={
                "name": name,
                "members": convert_and_respect_annotation_metadata(
                    object_=members, annotation=typing.Sequence[TeamMemberCreate], direction="write"
                ),
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    Team,
                    parse_obj_as(
                        type_=Team,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def get_team(
        self, team_key: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> AsyncHttpResponse[Team]:
        """
        Returns a team by key.

        Parameters
        ----------
        team_key : str
            Key for the team to return.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[Team]
            OK
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"v2/teams/{encode_path_param(team_key)}",
            method="GET",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    Team,
                    parse_obj_as(
                        type_=Team,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def update_team(
        self,
        team_key: str,
        *,
        name: typing.Optional[str] = OMIT,
        sharing_restricted_to_team: typing.Optional[bool] = OMIT,
        automatically_approve_join_requests: typing.Optional[bool] = OMIT,
        automatically_send_invoice_emails: typing.Optional[bool] = OMIT,
        emails_to_send_invoice_to: typing.Optional[typing.Sequence[str]] = OMIT,
        members: typing.Optional[typing.Sequence[TeamMemberUpdate]] = OMIT,
        contact_org_list_permissions: typing.Optional[
            typing.Dict[str, typing.Optional[TeamBasedPermissionsUpdate]]
        ] = OMIT,
        contact_settings: typing.Optional[TeamFieldSettingsUpdate] = OMIT,
        organization_settings: typing.Optional[TeamFieldSettingsUpdate] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[Team]:
        """
        Updates a team by key. Omitted body fields are left unchanged.

        Parameters
        ----------
        team_key : str
            Key for the team to update.

        name : typing.Optional[str]
            New display name for the team.

        sharing_restricted_to_team : typing.Optional[bool]
            Whether sharing outside the team is restricted.

        automatically_approve_join_requests : typing.Optional[bool]
            Whether requests to join the team are approved automatically.

        automatically_send_invoice_emails : typing.Optional[bool]
            Whether invoice emails are sent automatically for this team.

        emails_to_send_invoice_to : typing.Optional[typing.Sequence[str]]
            Complete replacement for additional invoice-recipient email addresses. Omit to leave unchanged; send an empty set to clear.

        members : typing.Optional[typing.Sequence[TeamMemberUpdate]]
            Complete replacement roster. Omit this property to leave membership unchanged.

        contact_org_list_permissions : typing.Optional[typing.Dict[str, typing.Optional[TeamBasedPermissionsUpdate]]]
            Permission updates keyed by system list. Omitted list entries remain unchanged.

        contact_settings : typing.Optional[TeamFieldSettingsUpdate]
            Complete replacement for the team's custom contact fields. Omit to leave unchanged.

        organization_settings : typing.Optional[TeamFieldSettingsUpdate]
            Complete replacement for the team's custom organization fields. Omit to leave unchanged.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[Team]
            OK
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"v2/teams/{encode_path_param(team_key)}",
            method="POST",
            json={
                "name": name,
                "sharingRestrictedToTeam": sharing_restricted_to_team,
                "automaticallyApproveJoinRequests": automatically_approve_join_requests,
                "automaticallySendInvoiceEmails": automatically_send_invoice_emails,
                "emailsToSendInvoiceTo": emails_to_send_invoice_to,
                "members": convert_and_respect_annotation_metadata(
                    object_=members, annotation=typing.Optional[typing.Sequence[TeamMemberUpdate]], direction="write"
                ),
                "contactOrgListPermissions": convert_and_respect_annotation_metadata(
                    object_=contact_org_list_permissions,
                    annotation=typing.Optional[typing.Dict[str, typing.Optional[TeamBasedPermissionsUpdate]]],
                    direction="write",
                ),
                "contactSettings": convert_and_respect_annotation_metadata(
                    object_=contact_settings, annotation=typing.Optional[TeamFieldSettingsUpdate], direction="write"
                ),
                "organizationSettings": convert_and_respect_annotation_metadata(
                    object_=organization_settings,
                    annotation=typing.Optional[TeamFieldSettingsUpdate],
                    direction="write",
                ),
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    Team,
                    parse_obj_as(
                        type_=Team,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def list_current_users_teams(
        self,
        *,
        limit: typing.Optional[int] = None,
        page: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[TeamListResponse]:
        """
        Lists the teams the current user belongs to, newest first.

        Parameters
        ----------
        limit : typing.Optional[int]
            Number of items to return.

        page : typing.Optional[int]
            Zero-based page number

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[TeamListResponse]
            OK
        """
        _response = await self._client_wrapper.httpx_client.request(
            "v2/users/me/teams",
            method="GET",
            params={
                "limit": limit,
                "page": page,
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    TeamListResponse,
                    parse_obj_as(
                        type_=TeamListResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)
