# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from ..types.search_response import SearchResponse
from .raw_client import AsyncRawSearchClient, RawSearchClient


class SearchClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawSearchClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawSearchClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawSearchClient
        """
        return self._raw_client

    def search_boxes_contacts_and_organizations(
        self,
        *,
        name: typing.Optional[str] = None,
        page: typing.Optional[int] = None,
        pipeline_key: typing.Optional[typing.Sequence[str]] = None,
        query: typing.Optional[str] = None,
        stage_key: typing.Optional[typing.Sequence[str]] = None,
        team_key: typing.Optional[typing.Sequence[str]] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> SearchResponse:
        """
        Searches visible boxes, contacts, and organizations by query, or visible boxes by exact name. Exactly one of query or name must be provided.

        Parameters
        ----------
        name : typing.Optional[str]
            Exact box name to search for.

        page : typing.Optional[int]
            Zero-based page number.

        pipeline_key : typing.Optional[typing.Sequence[str]]
            Pipeline keys to constrain the search to.

        query : typing.Optional[str]
            Full-text query to search across boxes, contacts, and organizations.

        stage_key : typing.Optional[typing.Sequence[str]]
            Stage keys to constrain the search to.

        team_key : typing.Optional[typing.Sequence[str]]
            Team keys to constrain the search to.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        SearchResponse
            OK

        Examples
        --------
        from streak_crm import Streak

        client = Streak(
            token="YOUR_TOKEN",
        )
        client.search.search_boxes_contacts_and_organizations()
        """
        _response = self._raw_client.search_boxes_contacts_and_organizations(
            name=name,
            page=page,
            pipeline_key=pipeline_key,
            query=query,
            stage_key=stage_key,
            team_key=team_key,
            request_options=request_options,
        )
        return _response.data


class AsyncSearchClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawSearchClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawSearchClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawSearchClient
        """
        return self._raw_client

    async def search_boxes_contacts_and_organizations(
        self,
        *,
        name: typing.Optional[str] = None,
        page: typing.Optional[int] = None,
        pipeline_key: typing.Optional[typing.Sequence[str]] = None,
        query: typing.Optional[str] = None,
        stage_key: typing.Optional[typing.Sequence[str]] = None,
        team_key: typing.Optional[typing.Sequence[str]] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> SearchResponse:
        """
        Searches visible boxes, contacts, and organizations by query, or visible boxes by exact name. Exactly one of query or name must be provided.

        Parameters
        ----------
        name : typing.Optional[str]
            Exact box name to search for.

        page : typing.Optional[int]
            Zero-based page number.

        pipeline_key : typing.Optional[typing.Sequence[str]]
            Pipeline keys to constrain the search to.

        query : typing.Optional[str]
            Full-text query to search across boxes, contacts, and organizations.

        stage_key : typing.Optional[typing.Sequence[str]]
            Stage keys to constrain the search to.

        team_key : typing.Optional[typing.Sequence[str]]
            Team keys to constrain the search to.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        SearchResponse
            OK

        Examples
        --------
        import asyncio

        from streak_crm import AsyncStreak

        client = AsyncStreak(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.search.search_boxes_contacts_and_organizations()


        asyncio.run(main())
        """
        _response = await self._raw_client.search_boxes_contacts_and_organizations(
            name=name,
            page=page,
            pipeline_key=pipeline_key,
            query=query,
            stage_key=stage_key,
            team_key=team_key,
            request_options=request_options,
        )
        return _response.data
