# This file was auto-generated by Fern from our API Definition.

import typing
from json.decoder import JSONDecodeError

from ..core.api_error import ApiError
from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.http_response import AsyncHttpResponse, HttpResponse
from ..core.parse_error import ParsingError
from ..core.pydantic_utilities import parse_obj_as
from ..core.request_options import RequestOptions
from ..types.search_response import SearchResponse
from pydantic import ValidationError


class RawSearchClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._client_wrapper = client_wrapper

    def search_boxes_contacts_and_organizations(
        self,
        *,
        name: typing.Optional[str] = None,
        page: typing.Optional[int] = None,
        pipeline_key: typing.Optional[typing.Sequence[str]] = None,
        query: typing.Optional[str] = None,
        stage_key: typing.Optional[typing.Sequence[str]] = None,
        team_key: typing.Optional[typing.Sequence[str]] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[SearchResponse]:
        """
        Searches visible boxes, contacts, and organizations by query, or visible boxes by exact name. Exactly one of query or name must be provided.

        Parameters
        ----------
        name : typing.Optional[str]
            Exact box name to search for.

        page : typing.Optional[int]
            Zero-based page number.

        pipeline_key : typing.Optional[typing.Sequence[str]]
            Pipeline keys to constrain the search to.

        query : typing.Optional[str]
            Full-text query to search across boxes, contacts, and organizations.

        stage_key : typing.Optional[typing.Sequence[str]]
            Stage keys to constrain the search to.

        team_key : typing.Optional[typing.Sequence[str]]
            Team keys to constrain the search to.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[SearchResponse]
            OK
        """
        _response = self._client_wrapper.httpx_client.request(
            "v1/search",
            method="GET",
            params={
                "name": name,
                "page": page,
                "pipelineKey": pipeline_key,
                "query": query,
                "stageKey": stage_key,
                "teamKey": team_key,
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    SearchResponse,
                    parse_obj_as(
                        type_=SearchResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)


class AsyncRawSearchClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._client_wrapper = client_wrapper

    async def search_boxes_contacts_and_organizations(
        self,
        *,
        name: typing.Optional[str] = None,
        page: typing.Optional[int] = None,
        pipeline_key: typing.Optional[typing.Sequence[str]] = None,
        query: typing.Optional[str] = None,
        stage_key: typing.Optional[typing.Sequence[str]] = None,
        team_key: typing.Optional[typing.Sequence[str]] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[SearchResponse]:
        """
        Searches visible boxes, contacts, and organizations by query, or visible boxes by exact name. Exactly one of query or name must be provided.

        Parameters
        ----------
        name : typing.Optional[str]
            Exact box name to search for.

        page : typing.Optional[int]
            Zero-based page number.

        pipeline_key : typing.Optional[typing.Sequence[str]]
            Pipeline keys to constrain the search to.

        query : typing.Optional[str]
            Full-text query to search across boxes, contacts, and organizations.

        stage_key : typing.Optional[typing.Sequence[str]]
            Stage keys to constrain the search to.

        team_key : typing.Optional[typing.Sequence[str]]
            Team keys to constrain the search to.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[SearchResponse]
            OK
        """
        _response = await self._client_wrapper.httpx_client.request(
            "v1/search",
            method="GET",
            params={
                "name": name,
                "page": page,
                "pipelineKey": pipeline_key,
                "query": query,
                "stageKey": stage_key,
                "teamKey": team_key,
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    SearchResponse,
                    parse_obj_as(
                        type_=SearchResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)
