# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from ..types.api_key import ApiKey
from ..types.operation_response import OperationResponse
from .raw_client import AsyncRawApiKeysClient, RawApiKeysClient


class ApiKeysClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawApiKeysClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawApiKeysClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawApiKeysClient
        """
        return self._raw_client

    def list_api_keys(
        self,
        *,
        limit: typing.Optional[int] = None,
        page: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> typing.List[ApiKey]:
        """
        Lists API keys owned by the current user

        Parameters
        ----------
        limit : typing.Optional[int]
            Number of items to return.

        page : typing.Optional[int]
            Zero-based page number

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.List[ApiKey]
            OK

        Examples
        --------
        from streak_crm import Streak

        client = Streak(
            token="YOUR_TOKEN",
        )
        client.api_keys.list_api_keys()
        """
        _response = self._raw_client.list_api_keys(limit=limit, page=page, request_options=request_options)
        return _response.data

    def create_api_key(
        self, *, team_key: typing.Optional[str] = None, request_options: typing.Optional[RequestOptions] = None
    ) -> ApiKey:
        """
        Creates an API key for the current user

        Parameters
        ----------
        team_key : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ApiKey
            OK

        Examples
        --------
        from streak_crm import Streak

        client = Streak(
            token="YOUR_TOKEN",
        )
        client.api_keys.create_api_key()
        """
        _response = self._raw_client.create_api_key(team_key=team_key, request_options=request_options)
        return _response.data

    def delete_api_key(
        self, api_key_key: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> OperationResponse:
        """
        Deletes an API key by key

        Parameters
        ----------
        api_key_key : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        OperationResponse
            OK

        Examples
        --------
        from streak_crm import Streak

        client = Streak(
            token="YOUR_TOKEN",
        )
        client.api_keys.delete_api_key(
            api_key_key="apiKeyKey",
        )
        """
        _response = self._raw_client.delete_api_key(api_key_key, request_options=request_options)
        return _response.data


class AsyncApiKeysClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawApiKeysClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawApiKeysClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawApiKeysClient
        """
        return self._raw_client

    async def list_api_keys(
        self,
        *,
        limit: typing.Optional[int] = None,
        page: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> typing.List[ApiKey]:
        """
        Lists API keys owned by the current user

        Parameters
        ----------
        limit : typing.Optional[int]
            Number of items to return.

        page : typing.Optional[int]
            Zero-based page number

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.List[ApiKey]
            OK

        Examples
        --------
        import asyncio

        from streak_crm import AsyncStreak

        client = AsyncStreak(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.api_keys.list_api_keys()


        asyncio.run(main())
        """
        _response = await self._raw_client.list_api_keys(limit=limit, page=page, request_options=request_options)
        return _response.data

    async def create_api_key(
        self, *, team_key: typing.Optional[str] = None, request_options: typing.Optional[RequestOptions] = None
    ) -> ApiKey:
        """
        Creates an API key for the current user

        Parameters
        ----------
        team_key : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ApiKey
            OK

        Examples
        --------
        import asyncio

        from streak_crm import AsyncStreak

        client = AsyncStreak(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.api_keys.create_api_key()


        asyncio.run(main())
        """
        _response = await self._raw_client.create_api_key(team_key=team_key, request_options=request_options)
        return _response.data

    async def delete_api_key(
        self, api_key_key: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> OperationResponse:
        """
        Deletes an API key by key

        Parameters
        ----------
        api_key_key : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        OperationResponse
            OK

        Examples
        --------
        import asyncio

        from streak_crm import AsyncStreak

        client = AsyncStreak(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.api_keys.delete_api_key(
                api_key_key="apiKeyKey",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.delete_api_key(api_key_key, request_options=request_options)
        return _response.data
