# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from ..types.operation_response import OperationResponse
from ..types.pipeline_stage import PipelineStage
from ..types.pipeline_stage_color import PipelineStageColor
from .raw_client import AsyncRawPipelineStagesClient, RawPipelineStagesClient

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class PipelineStagesClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawPipelineStagesClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawPipelineStagesClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawPipelineStagesClient
        """
        return self._raw_client

    def list_stages(
        self, pipeline_key: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> typing.Dict[str, PipelineStage]:
        """
        Returns the pipeline's stages keyed by stage key.

        Parameters
        ----------
        pipeline_key : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.Dict[str, PipelineStage]
            OK

        Examples
        --------
        from streak_crm import Streak

        client = Streak(
            token="YOUR_TOKEN",
        )
        client.pipeline_stages.list_stages(
            pipeline_key="pipelineKey",
        )
        """
        _response = self._raw_client.list_stages(pipeline_key, request_options=request_options)
        return _response.data

    def create_stage(
        self,
        pipeline_key: str,
        *,
        name: str,
        color: typing.Optional[PipelineStageColor] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> PipelineStage:
        """
        Creates a stage at the end of the pipeline's stage order.

        Parameters
        ----------
        pipeline_key : str

        name : str
            Nonempty name of the new stage.

        color : typing.Optional[PipelineStageColor]
            Custom stage colors. Omit or set to null to use the pipeline theme.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        PipelineStage
            OK

        Examples
        --------
        from streak_crm import Streak

        client = Streak(
            token="YOUR_TOKEN",
        )
        client.pipeline_stages.create_stage(
            pipeline_key="pipelineKey",
            name="name",
        )
        """
        _response = self._raw_client.create_stage(pipeline_key, name=name, color=color, request_options=request_options)
        return _response.data

    def get_stage(
        self, pipeline_key: str, stage_key: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> PipelineStage:
        """
        Returns a stage in a pipeline.

        Parameters
        ----------
        pipeline_key : str

        stage_key : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        PipelineStage
            OK

        Examples
        --------
        from streak_crm import Streak

        client = Streak(
            token="YOUR_TOKEN",
        )
        client.pipeline_stages.get_stage(
            pipeline_key="pipelineKey",
            stage_key="stageKey",
        )
        """
        _response = self._raw_client.get_stage(pipeline_key, stage_key, request_options=request_options)
        return _response.data

    def update_stage(
        self,
        pipeline_key: str,
        stage_key: str,
        *,
        name: typing.Optional[str] = OMIT,
        color: typing.Optional[PipelineStageColor] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> PipelineStage:
        """
        Updates the supplied stage name or colors.

        Parameters
        ----------
        pipeline_key : str

        stage_key : str

        name : typing.Optional[str]
            Nonempty new stage name.

        color : typing.Optional[PipelineStageColor]
            Custom stage colors. Set both foregroundColor and backgroundColor to empty strings to reset to the pipeline theme.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        PipelineStage
            OK

        Examples
        --------
        from streak_crm import Streak

        client = Streak(
            token="YOUR_TOKEN",
        )
        client.pipeline_stages.update_stage(
            pipeline_key="pipelineKey",
            stage_key="stageKey",
        )
        """
        _response = self._raw_client.update_stage(
            pipeline_key, stage_key, name=name, color=color, request_options=request_options
        )
        return _response.data

    def delete_stage(
        self, pipeline_key: str, stage_key: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> OperationResponse:
        """
        Deletes an empty stage. The final stage in a pipeline cannot be deleted.

        Parameters
        ----------
        pipeline_key : str

        stage_key : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        OperationResponse
            OK

        Examples
        --------
        from streak_crm import Streak

        client = Streak(
            token="YOUR_TOKEN",
        )
        client.pipeline_stages.delete_stage(
            pipeline_key="pipelineKey",
            stage_key="stageKey",
        )
        """
        _response = self._raw_client.delete_stage(pipeline_key, stage_key, request_options=request_options)
        return _response.data


class AsyncPipelineStagesClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawPipelineStagesClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawPipelineStagesClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawPipelineStagesClient
        """
        return self._raw_client

    async def list_stages(
        self, pipeline_key: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> typing.Dict[str, PipelineStage]:
        """
        Returns the pipeline's stages keyed by stage key.

        Parameters
        ----------
        pipeline_key : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.Dict[str, PipelineStage]
            OK

        Examples
        --------
        import asyncio

        from streak_crm import AsyncStreak

        client = AsyncStreak(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.pipeline_stages.list_stages(
                pipeline_key="pipelineKey",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.list_stages(pipeline_key, request_options=request_options)
        return _response.data

    async def create_stage(
        self,
        pipeline_key: str,
        *,
        name: str,
        color: typing.Optional[PipelineStageColor] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> PipelineStage:
        """
        Creates a stage at the end of the pipeline's stage order.

        Parameters
        ----------
        pipeline_key : str

        name : str
            Nonempty name of the new stage.

        color : typing.Optional[PipelineStageColor]
            Custom stage colors. Omit or set to null to use the pipeline theme.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        PipelineStage
            OK

        Examples
        --------
        import asyncio

        from streak_crm import AsyncStreak

        client = AsyncStreak(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.pipeline_stages.create_stage(
                pipeline_key="pipelineKey",
                name="name",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.create_stage(
            pipeline_key, name=name, color=color, request_options=request_options
        )
        return _response.data

    async def get_stage(
        self, pipeline_key: str, stage_key: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> PipelineStage:
        """
        Returns a stage in a pipeline.

        Parameters
        ----------
        pipeline_key : str

        stage_key : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        PipelineStage
            OK

        Examples
        --------
        import asyncio

        from streak_crm import AsyncStreak

        client = AsyncStreak(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.pipeline_stages.get_stage(
                pipeline_key="pipelineKey",
                stage_key="stageKey",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get_stage(pipeline_key, stage_key, request_options=request_options)
        return _response.data

    async def update_stage(
        self,
        pipeline_key: str,
        stage_key: str,
        *,
        name: typing.Optional[str] = OMIT,
        color: typing.Optional[PipelineStageColor] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> PipelineStage:
        """
        Updates the supplied stage name or colors.

        Parameters
        ----------
        pipeline_key : str

        stage_key : str

        name : typing.Optional[str]
            Nonempty new stage name.

        color : typing.Optional[PipelineStageColor]
            Custom stage colors. Set both foregroundColor and backgroundColor to empty strings to reset to the pipeline theme.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        PipelineStage
            OK

        Examples
        --------
        import asyncio

        from streak_crm import AsyncStreak

        client = AsyncStreak(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.pipeline_stages.update_stage(
                pipeline_key="pipelineKey",
                stage_key="stageKey",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.update_stage(
            pipeline_key, stage_key, name=name, color=color, request_options=request_options
        )
        return _response.data

    async def delete_stage(
        self, pipeline_key: str, stage_key: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> OperationResponse:
        """
        Deletes an empty stage. The final stage in a pipeline cannot be deleted.

        Parameters
        ----------
        pipeline_key : str

        stage_key : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        OperationResponse
            OK

        Examples
        --------
        import asyncio

        from streak_crm import AsyncStreak

        client = AsyncStreak(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.pipeline_stages.delete_stage(
                pipeline_key="pipelineKey",
                stage_key="stageKey",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.delete_stage(pipeline_key, stage_key, request_options=request_options)
        return _response.data
