# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from ..types.contact_link_input import ContactLinkInput
from ..types.operation_response import OperationResponse
from ..types.organization import Organization
from ..types.organization_link_input import OrganizationLinkInput
from ..types.organization_page import OrganizationPage
from .raw_client import AsyncRawOrganizationClient, RawOrganizationClient

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class OrganizationClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawOrganizationClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawOrganizationClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawOrganizationClient
        """
        return self._raw_client

    def get_organizations_in_a_batch(
        self, *, request: typing.Sequence[str], request_options: typing.Optional[RequestOptions] = None
    ) -> typing.Dict[str, Organization]:
        """
        Returns organizations keyed by their organization keys. Missing and inaccessible organizations are omitted.

        Parameters
        ----------
        request : typing.Sequence[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.Dict[str, Organization]
            OK

        Examples
        --------
        from streak_crm import Streak

        client = Streak(
            token="YOUR_TOKEN",
        )
        client.organization.get_organizations_in_a_batch(
            request=["string"],
        )
        """
        _response = self._raw_client.get_organizations_in_a_batch(request=request, request_options=request_options)
        return _response.data

    def get_an_organization(
        self, organization_key: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> Organization:
        """
        Returns an organization accessible to the current user, including custom fields and relationships.

        Parameters
        ----------
        organization_key : str
            Key of the organization.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        Organization
            OK

        Examples
        --------
        from streak_crm import Streak

        client = Streak(
            token="YOUR_TOKEN",
        )
        client.organization.get_an_organization(
            organization_key="organizationKey",
        )
        """
        _response = self._raw_client.get_an_organization(organization_key, request_options=request_options)
        return _response.data

    def update_an_organization(
        self,
        organization_key: str,
        *,
        name: typing.Optional[str] = OMIT,
        other: typing.Optional[str] = OMIT,
        domains: typing.Optional[typing.Sequence[str]] = OMIT,
        industry: typing.Optional[str] = OMIT,
        phone_numbers: typing.Optional[typing.Sequence[str]] = OMIT,
        addresses: typing.Optional[typing.Sequence[str]] = OMIT,
        employee_count: typing.Optional[str] = OMIT,
        logo_url: typing.Optional[str] = OMIT,
        twitter_handle: typing.Optional[str] = OMIT,
        facebook_handle: typing.Optional[str] = OMIT,
        linkedin_handle: typing.Optional[str] = OMIT,
        instagram_handle: typing.Optional[str] = OMIT,
        contact_links: typing.Optional[typing.Sequence[ContactLinkInput]] = OMIT,
        org_links: typing.Optional[typing.Sequence[OrganizationLinkInput]] = OMIT,
        fields: typing.Optional[typing.Dict[str, typing.Optional[str]]] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> Organization:
        """
        Updates an organization. Omitted and null properties are unchanged. Supplied lists replace existing lists, subject to field validation.

        Parameters
        ----------
        organization_key : str
            Key of the organization.

        name : typing.Optional[str]
            Replacement organization name. A name or domain must remain after the update.

        other : typing.Optional[str]
            Replacement notes. An empty string clears the notes.

        domains : typing.Optional[typing.Sequence[str]]
            Replacement domains, with the primary domain first. An empty list clears domains if a name remains.

        industry : typing.Optional[str]
            Replacement industry.

        phone_numbers : typing.Optional[typing.Sequence[str]]
            Replacement phone numbers. An empty list clears existing phone numbers.

        addresses : typing.Optional[typing.Sequence[str]]
            Replacement postal addresses. An empty list clears existing addresses.

        employee_count : typing.Optional[str]
            Replacement company size as text, including employee-count ranges.

        logo_url : typing.Optional[str]
            Replacement organization logo URL.

        twitter_handle : typing.Optional[str]
            Replacement Twitter profile handle or URL.

        facebook_handle : typing.Optional[str]
            Replacement Facebook profile handle or URL.

        linkedin_handle : typing.Optional[str]
            Replacement LinkedIn profile handle or URL.

        instagram_handle : typing.Optional[str]
            Replacement Instagram profile handle or URL.

        contact_links : typing.Optional[typing.Sequence[ContactLinkInput]]
            Replacement contact relationships. An empty list removes existing relationships.

        org_links : typing.Optional[typing.Sequence[OrganizationLinkInput]]
            Replacement organization relationships. An empty list removes existing relationships.

        fields : typing.Optional[typing.Dict[str, typing.Optional[str]]]
            Custom field values to change, keyed by field ID. Omitted keys and null values are unchanged; an empty object makes no changes.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        Organization
            OK

        Examples
        --------
        from streak_crm import Streak

        client = Streak(
            token="YOUR_TOKEN",
        )
        client.organization.update_an_organization(
            organization_key="organizationKey",
        )
        """
        _response = self._raw_client.update_an_organization(
            organization_key,
            name=name,
            other=other,
            domains=domains,
            industry=industry,
            phone_numbers=phone_numbers,
            addresses=addresses,
            employee_count=employee_count,
            logo_url=logo_url,
            twitter_handle=twitter_handle,
            facebook_handle=facebook_handle,
            linkedin_handle=linkedin_handle,
            instagram_handle=instagram_handle,
            contact_links=contact_links,
            org_links=org_links,
            fields=fields,
            request_options=request_options,
        )
        return _response.data

    def delete_an_organization(
        self, organization_key: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> OperationResponse:
        """
        Deletes an organization and schedules removal of its relationships and box links.

        Parameters
        ----------
        organization_key : str
            Key of the organization.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        OperationResponse
            OK

        Examples
        --------
        from streak_crm import Streak

        client = Streak(
            token="YOUR_TOKEN",
        )
        client.organization.delete_an_organization(
            organization_key="organizationKey",
        )
        """
        _response = self._raw_client.delete_an_organization(organization_key, request_options=request_options)
        return _response.data

    def list_organizations(
        self,
        team_key: str,
        *,
        cursor: typing.Optional[str] = None,
        limit: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> OrganizationPage:
        """
        Returns organizations in a team, ordered by key. Pass the returned cursor to retrieve the next page.

        Parameters
        ----------
        team_key : str
            Key of the team.

        cursor : typing.Optional[str]
            Cursor returned by the previous response. Omit or leave blank to start from the beginning.

        limit : typing.Optional[int]
            Maximum number of results to return. Defaults to 100. Values above 1000 are capped.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        OrganizationPage
            OK

        Examples
        --------
        from streak_crm import Streak

        client = Streak(
            token="YOUR_TOKEN",
        )
        client.organization.list_organizations(
            team_key="teamKey",
        )
        """
        _response = self._raw_client.list_organizations(
            team_key, cursor=cursor, limit=limit, request_options=request_options
        )
        return _response.data

    def create_an_organization(
        self,
        team_key: str,
        *,
        get_if_existing: typing.Optional[bool] = None,
        name: typing.Optional[str] = OMIT,
        other: typing.Optional[str] = OMIT,
        domains: typing.Optional[typing.Sequence[str]] = OMIT,
        industry: typing.Optional[str] = OMIT,
        phone_numbers: typing.Optional[typing.Sequence[str]] = OMIT,
        addresses: typing.Optional[typing.Sequence[str]] = OMIT,
        employee_count: typing.Optional[str] = OMIT,
        logo_url: typing.Optional[str] = OMIT,
        twitter_handle: typing.Optional[str] = OMIT,
        facebook_handle: typing.Optional[str] = OMIT,
        linkedin_handle: typing.Optional[str] = OMIT,
        instagram_handle: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> Organization:
        """
        Creates an organization in a team. Available enrichment data may fill missing details. Provide a name or at least one domain. Set custom fields and relationships in a subsequent update.

        Parameters
        ----------
        team_key : str
            Key of the team.

        get_if_existing : typing.Optional[bool]
            Return an existing organization matching a supplied domain instead of creating another organization. The supplied values are not merged into the existing organization.

        name : typing.Optional[str]
            Organization name.

        other : typing.Optional[str]
            Freeform notes about the organization.

        domains : typing.Optional[typing.Sequence[str]]
            Website domains for the organization, with the primary domain first.

        industry : typing.Optional[str]
            Industry of the organization.

        phone_numbers : typing.Optional[typing.Sequence[str]]
            Phone numbers for the organization.

        addresses : typing.Optional[typing.Sequence[str]]
            Postal addresses for the organization.

        employee_count : typing.Optional[str]
            Company size as text, which can include an employee-count range.

        logo_url : typing.Optional[str]
            URL of the organization's logo.

        twitter_handle : typing.Optional[str]
            Twitter profile handle or URL.

        facebook_handle : typing.Optional[str]
            Facebook profile handle or URL.

        linkedin_handle : typing.Optional[str]
            LinkedIn profile handle or URL.

        instagram_handle : typing.Optional[str]
            Instagram profile handle or URL.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        Organization
            OK

        Examples
        --------
        from streak_crm import Streak

        client = Streak(
            token="YOUR_TOKEN",
        )
        client.organization.create_an_organization(
            team_key="teamKey",
        )
        """
        _response = self._raw_client.create_an_organization(
            team_key,
            get_if_existing=get_if_existing,
            name=name,
            other=other,
            domains=domains,
            industry=industry,
            phone_numbers=phone_numbers,
            addresses=addresses,
            employee_count=employee_count,
            logo_url=logo_url,
            twitter_handle=twitter_handle,
            facebook_handle=facebook_handle,
            linkedin_handle=linkedin_handle,
            instagram_handle=instagram_handle,
            request_options=request_options,
        )
        return _response.data


class AsyncOrganizationClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawOrganizationClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawOrganizationClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawOrganizationClient
        """
        return self._raw_client

    async def get_organizations_in_a_batch(
        self, *, request: typing.Sequence[str], request_options: typing.Optional[RequestOptions] = None
    ) -> typing.Dict[str, Organization]:
        """
        Returns organizations keyed by their organization keys. Missing and inaccessible organizations are omitted.

        Parameters
        ----------
        request : typing.Sequence[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.Dict[str, Organization]
            OK

        Examples
        --------
        import asyncio

        from streak_crm import AsyncStreak

        client = AsyncStreak(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.organization.get_organizations_in_a_batch(
                request=["string"],
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get_organizations_in_a_batch(
            request=request, request_options=request_options
        )
        return _response.data

    async def get_an_organization(
        self, organization_key: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> Organization:
        """
        Returns an organization accessible to the current user, including custom fields and relationships.

        Parameters
        ----------
        organization_key : str
            Key of the organization.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        Organization
            OK

        Examples
        --------
        import asyncio

        from streak_crm import AsyncStreak

        client = AsyncStreak(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.organization.get_an_organization(
                organization_key="organizationKey",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get_an_organization(organization_key, request_options=request_options)
        return _response.data

    async def update_an_organization(
        self,
        organization_key: str,
        *,
        name: typing.Optional[str] = OMIT,
        other: typing.Optional[str] = OMIT,
        domains: typing.Optional[typing.Sequence[str]] = OMIT,
        industry: typing.Optional[str] = OMIT,
        phone_numbers: typing.Optional[typing.Sequence[str]] = OMIT,
        addresses: typing.Optional[typing.Sequence[str]] = OMIT,
        employee_count: typing.Optional[str] = OMIT,
        logo_url: typing.Optional[str] = OMIT,
        twitter_handle: typing.Optional[str] = OMIT,
        facebook_handle: typing.Optional[str] = OMIT,
        linkedin_handle: typing.Optional[str] = OMIT,
        instagram_handle: typing.Optional[str] = OMIT,
        contact_links: typing.Optional[typing.Sequence[ContactLinkInput]] = OMIT,
        org_links: typing.Optional[typing.Sequence[OrganizationLinkInput]] = OMIT,
        fields: typing.Optional[typing.Dict[str, typing.Optional[str]]] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> Organization:
        """
        Updates an organization. Omitted and null properties are unchanged. Supplied lists replace existing lists, subject to field validation.

        Parameters
        ----------
        organization_key : str
            Key of the organization.

        name : typing.Optional[str]
            Replacement organization name. A name or domain must remain after the update.

        other : typing.Optional[str]
            Replacement notes. An empty string clears the notes.

        domains : typing.Optional[typing.Sequence[str]]
            Replacement domains, with the primary domain first. An empty list clears domains if a name remains.

        industry : typing.Optional[str]
            Replacement industry.

        phone_numbers : typing.Optional[typing.Sequence[str]]
            Replacement phone numbers. An empty list clears existing phone numbers.

        addresses : typing.Optional[typing.Sequence[str]]
            Replacement postal addresses. An empty list clears existing addresses.

        employee_count : typing.Optional[str]
            Replacement company size as text, including employee-count ranges.

        logo_url : typing.Optional[str]
            Replacement organization logo URL.

        twitter_handle : typing.Optional[str]
            Replacement Twitter profile handle or URL.

        facebook_handle : typing.Optional[str]
            Replacement Facebook profile handle or URL.

        linkedin_handle : typing.Optional[str]
            Replacement LinkedIn profile handle or URL.

        instagram_handle : typing.Optional[str]
            Replacement Instagram profile handle or URL.

        contact_links : typing.Optional[typing.Sequence[ContactLinkInput]]
            Replacement contact relationships. An empty list removes existing relationships.

        org_links : typing.Optional[typing.Sequence[OrganizationLinkInput]]
            Replacement organization relationships. An empty list removes existing relationships.

        fields : typing.Optional[typing.Dict[str, typing.Optional[str]]]
            Custom field values to change, keyed by field ID. Omitted keys and null values are unchanged; an empty object makes no changes.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        Organization
            OK

        Examples
        --------
        import asyncio

        from streak_crm import AsyncStreak

        client = AsyncStreak(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.organization.update_an_organization(
                organization_key="organizationKey",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.update_an_organization(
            organization_key,
            name=name,
            other=other,
            domains=domains,
            industry=industry,
            phone_numbers=phone_numbers,
            addresses=addresses,
            employee_count=employee_count,
            logo_url=logo_url,
            twitter_handle=twitter_handle,
            facebook_handle=facebook_handle,
            linkedin_handle=linkedin_handle,
            instagram_handle=instagram_handle,
            contact_links=contact_links,
            org_links=org_links,
            fields=fields,
            request_options=request_options,
        )
        return _response.data

    async def delete_an_organization(
        self, organization_key: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> OperationResponse:
        """
        Deletes an organization and schedules removal of its relationships and box links.

        Parameters
        ----------
        organization_key : str
            Key of the organization.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        OperationResponse
            OK

        Examples
        --------
        import asyncio

        from streak_crm import AsyncStreak

        client = AsyncStreak(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.organization.delete_an_organization(
                organization_key="organizationKey",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.delete_an_organization(organization_key, request_options=request_options)
        return _response.data

    async def list_organizations(
        self,
        team_key: str,
        *,
        cursor: typing.Optional[str] = None,
        limit: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> OrganizationPage:
        """
        Returns organizations in a team, ordered by key. Pass the returned cursor to retrieve the next page.

        Parameters
        ----------
        team_key : str
            Key of the team.

        cursor : typing.Optional[str]
            Cursor returned by the previous response. Omit or leave blank to start from the beginning.

        limit : typing.Optional[int]
            Maximum number of results to return. Defaults to 100. Values above 1000 are capped.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        OrganizationPage
            OK

        Examples
        --------
        import asyncio

        from streak_crm import AsyncStreak

        client = AsyncStreak(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.organization.list_organizations(
                team_key="teamKey",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.list_organizations(
            team_key, cursor=cursor, limit=limit, request_options=request_options
        )
        return _response.data

    async def create_an_organization(
        self,
        team_key: str,
        *,
        get_if_existing: typing.Optional[bool] = None,
        name: typing.Optional[str] = OMIT,
        other: typing.Optional[str] = OMIT,
        domains: typing.Optional[typing.Sequence[str]] = OMIT,
        industry: typing.Optional[str] = OMIT,
        phone_numbers: typing.Optional[typing.Sequence[str]] = OMIT,
        addresses: typing.Optional[typing.Sequence[str]] = OMIT,
        employee_count: typing.Optional[str] = OMIT,
        logo_url: typing.Optional[str] = OMIT,
        twitter_handle: typing.Optional[str] = OMIT,
        facebook_handle: typing.Optional[str] = OMIT,
        linkedin_handle: typing.Optional[str] = OMIT,
        instagram_handle: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> Organization:
        """
        Creates an organization in a team. Available enrichment data may fill missing details. Provide a name or at least one domain. Set custom fields and relationships in a subsequent update.

        Parameters
        ----------
        team_key : str
            Key of the team.

        get_if_existing : typing.Optional[bool]
            Return an existing organization matching a supplied domain instead of creating another organization. The supplied values are not merged into the existing organization.

        name : typing.Optional[str]
            Organization name.

        other : typing.Optional[str]
            Freeform notes about the organization.

        domains : typing.Optional[typing.Sequence[str]]
            Website domains for the organization, with the primary domain first.

        industry : typing.Optional[str]
            Industry of the organization.

        phone_numbers : typing.Optional[typing.Sequence[str]]
            Phone numbers for the organization.

        addresses : typing.Optional[typing.Sequence[str]]
            Postal addresses for the organization.

        employee_count : typing.Optional[str]
            Company size as text, which can include an employee-count range.

        logo_url : typing.Optional[str]
            URL of the organization's logo.

        twitter_handle : typing.Optional[str]
            Twitter profile handle or URL.

        facebook_handle : typing.Optional[str]
            Facebook profile handle or URL.

        linkedin_handle : typing.Optional[str]
            LinkedIn profile handle or URL.

        instagram_handle : typing.Optional[str]
            Instagram profile handle or URL.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        Organization
            OK

        Examples
        --------
        import asyncio

        from streak_crm import AsyncStreak

        client = AsyncStreak(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.organization.create_an_organization(
                team_key="teamKey",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.create_an_organization(
            team_key,
            get_if_existing=get_if_existing,
            name=name,
            other=other,
            domains=domains,
            industry=industry,
            phone_numbers=phone_numbers,
            addresses=addresses,
            employee_count=employee_count,
            logo_url=logo_url,
            twitter_handle=twitter_handle,
            facebook_handle=facebook_handle,
            linkedin_handle=linkedin_handle,
            instagram_handle=instagram_handle,
            request_options=request_options,
        )
        return _response.data
