# This file was auto-generated by Fern from our API Definition.

import typing
from json.decoder import JSONDecodeError

from ..core.api_error import ApiError
from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.http_response import AsyncHttpResponse, HttpResponse
from ..core.jsonable_encoder import encode_path_param
from ..core.parse_error import ParsingError
from ..core.pydantic_utilities import parse_obj_as
from ..core.request_options import RequestOptions
from ..core.serialization import convert_and_respect_annotation_metadata
from ..types.contact_link_input import ContactLinkInput
from ..types.operation_response import OperationResponse
from ..types.organization import Organization
from ..types.organization_link_input import OrganizationLinkInput
from ..types.organization_page import OrganizationPage
from pydantic import ValidationError

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class RawOrganizationClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._client_wrapper = client_wrapper

    def get_organizations_in_a_batch(
        self, *, request: typing.Sequence[str], request_options: typing.Optional[RequestOptions] = None
    ) -> HttpResponse[typing.Dict[str, Organization]]:
        """
        Returns organizations keyed by their organization keys. Missing and inaccessible organizations are omitted.

        Parameters
        ----------
        request : typing.Sequence[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[typing.Dict[str, Organization]]
            OK
        """
        _response = self._client_wrapper.httpx_client.request(
            "v2/organizations/batch/get",
            method="POST",
            json=request,
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    typing.Dict[str, Organization],
                    parse_obj_as(
                        type_=typing.Dict[str, Organization],  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def get_an_organization(
        self, organization_key: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> HttpResponse[Organization]:
        """
        Returns an organization accessible to the current user, including custom fields and relationships.

        Parameters
        ----------
        organization_key : str
            Key of the organization.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[Organization]
            OK
        """
        _response = self._client_wrapper.httpx_client.request(
            f"v2/organizations/{encode_path_param(organization_key)}",
            method="GET",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    Organization,
                    parse_obj_as(
                        type_=Organization,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def update_an_organization(
        self,
        organization_key: str,
        *,
        name: typing.Optional[str] = OMIT,
        other: typing.Optional[str] = OMIT,
        domains: typing.Optional[typing.Sequence[str]] = OMIT,
        industry: typing.Optional[str] = OMIT,
        phone_numbers: typing.Optional[typing.Sequence[str]] = OMIT,
        addresses: typing.Optional[typing.Sequence[str]] = OMIT,
        employee_count: typing.Optional[str] = OMIT,
        logo_url: typing.Optional[str] = OMIT,
        twitter_handle: typing.Optional[str] = OMIT,
        facebook_handle: typing.Optional[str] = OMIT,
        linkedin_handle: typing.Optional[str] = OMIT,
        instagram_handle: typing.Optional[str] = OMIT,
        contact_links: typing.Optional[typing.Sequence[ContactLinkInput]] = OMIT,
        org_links: typing.Optional[typing.Sequence[OrganizationLinkInput]] = OMIT,
        fields: typing.Optional[typing.Dict[str, typing.Optional[str]]] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[Organization]:
        """
        Updates an organization. Omitted and null properties are unchanged. Supplied lists replace existing lists, subject to field validation.

        Parameters
        ----------
        organization_key : str
            Key of the organization.

        name : typing.Optional[str]
            Replacement organization name. A name or domain must remain after the update.

        other : typing.Optional[str]
            Replacement notes. An empty string clears the notes.

        domains : typing.Optional[typing.Sequence[str]]
            Replacement domains, with the primary domain first. An empty list clears domains if a name remains.

        industry : typing.Optional[str]
            Replacement industry.

        phone_numbers : typing.Optional[typing.Sequence[str]]
            Replacement phone numbers. An empty list clears existing phone numbers.

        addresses : typing.Optional[typing.Sequence[str]]
            Replacement postal addresses. An empty list clears existing addresses.

        employee_count : typing.Optional[str]
            Replacement company size as text, including employee-count ranges.

        logo_url : typing.Optional[str]
            Replacement organization logo URL.

        twitter_handle : typing.Optional[str]
            Replacement Twitter profile handle or URL.

        facebook_handle : typing.Optional[str]
            Replacement Facebook profile handle or URL.

        linkedin_handle : typing.Optional[str]
            Replacement LinkedIn profile handle or URL.

        instagram_handle : typing.Optional[str]
            Replacement Instagram profile handle or URL.

        contact_links : typing.Optional[typing.Sequence[ContactLinkInput]]
            Replacement contact relationships. An empty list removes existing relationships.

        org_links : typing.Optional[typing.Sequence[OrganizationLinkInput]]
            Replacement organization relationships. An empty list removes existing relationships.

        fields : typing.Optional[typing.Dict[str, typing.Optional[str]]]
            Custom field values to change, keyed by field ID. Omitted keys and null values are unchanged; an empty object makes no changes.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[Organization]
            OK
        """
        _response = self._client_wrapper.httpx_client.request(
            f"v2/organizations/{encode_path_param(organization_key)}",
            method="POST",
            json={
                "name": name,
                "other": other,
                "domains": domains,
                "industry": industry,
                "phoneNumbers": phone_numbers,
                "addresses": addresses,
                "employeeCount": employee_count,
                "logoURL": logo_url,
                "twitterHandle": twitter_handle,
                "facebookHandle": facebook_handle,
                "linkedinHandle": linkedin_handle,
                "instagramHandle": instagram_handle,
                "contactLinks": convert_and_respect_annotation_metadata(
                    object_=contact_links,
                    annotation=typing.Optional[typing.Sequence[ContactLinkInput]],
                    direction="write",
                ),
                "orgLinks": convert_and_respect_annotation_metadata(
                    object_=org_links,
                    annotation=typing.Optional[typing.Sequence[OrganizationLinkInput]],
                    direction="write",
                ),
                "fields": fields,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    Organization,
                    parse_obj_as(
                        type_=Organization,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def delete_an_organization(
        self, organization_key: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> HttpResponse[OperationResponse]:
        """
        Deletes an organization and schedules removal of its relationships and box links.

        Parameters
        ----------
        organization_key : str
            Key of the organization.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[OperationResponse]
            OK
        """
        _response = self._client_wrapper.httpx_client.request(
            f"v2/organizations/{encode_path_param(organization_key)}",
            method="DELETE",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    OperationResponse,
                    parse_obj_as(
                        type_=OperationResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def list_organizations(
        self,
        team_key: str,
        *,
        cursor: typing.Optional[str] = None,
        limit: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[OrganizationPage]:
        """
        Returns organizations in a team, ordered by key. Pass the returned cursor to retrieve the next page.

        Parameters
        ----------
        team_key : str
            Key of the team.

        cursor : typing.Optional[str]
            Cursor returned by the previous response. Omit or leave blank to start from the beginning.

        limit : typing.Optional[int]
            Maximum number of results to return. Defaults to 100. Values above 1000 are capped.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[OrganizationPage]
            OK
        """
        _response = self._client_wrapper.httpx_client.request(
            f"v2/teams/{encode_path_param(team_key)}/organizations",
            method="GET",
            params={
                "cursor": cursor,
                "limit": limit,
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    OrganizationPage,
                    parse_obj_as(
                        type_=OrganizationPage,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def create_an_organization(
        self,
        team_key: str,
        *,
        get_if_existing: typing.Optional[bool] = None,
        name: typing.Optional[str] = OMIT,
        other: typing.Optional[str] = OMIT,
        domains: typing.Optional[typing.Sequence[str]] = OMIT,
        industry: typing.Optional[str] = OMIT,
        phone_numbers: typing.Optional[typing.Sequence[str]] = OMIT,
        addresses: typing.Optional[typing.Sequence[str]] = OMIT,
        employee_count: typing.Optional[str] = OMIT,
        logo_url: typing.Optional[str] = OMIT,
        twitter_handle: typing.Optional[str] = OMIT,
        facebook_handle: typing.Optional[str] = OMIT,
        linkedin_handle: typing.Optional[str] = OMIT,
        instagram_handle: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[Organization]:
        """
        Creates an organization in a team. Available enrichment data may fill missing details. Provide a name or at least one domain. Set custom fields and relationships in a subsequent update.

        Parameters
        ----------
        team_key : str
            Key of the team.

        get_if_existing : typing.Optional[bool]
            Return an existing organization matching a supplied domain instead of creating another organization. The supplied values are not merged into the existing organization.

        name : typing.Optional[str]
            Organization name.

        other : typing.Optional[str]
            Freeform notes about the organization.

        domains : typing.Optional[typing.Sequence[str]]
            Website domains for the organization, with the primary domain first.

        industry : typing.Optional[str]
            Industry of the organization.

        phone_numbers : typing.Optional[typing.Sequence[str]]
            Phone numbers for the organization.

        addresses : typing.Optional[typing.Sequence[str]]
            Postal addresses for the organization.

        employee_count : typing.Optional[str]
            Company size as text, which can include an employee-count range.

        logo_url : typing.Optional[str]
            URL of the organization's logo.

        twitter_handle : typing.Optional[str]
            Twitter profile handle or URL.

        facebook_handle : typing.Optional[str]
            Facebook profile handle or URL.

        linkedin_handle : typing.Optional[str]
            LinkedIn profile handle or URL.

        instagram_handle : typing.Optional[str]
            Instagram profile handle or URL.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[Organization]
            OK
        """
        _response = self._client_wrapper.httpx_client.request(
            f"v2/teams/{encode_path_param(team_key)}/organizations",
            method="POST",
            params={
                "getIfExisting": get_if_existing,
            },
            json={
                "name": name,
                "other": other,
                "domains": domains,
                "industry": industry,
                "phoneNumbers": phone_numbers,
                "addresses": addresses,
                "employeeCount": employee_count,
                "logoURL": logo_url,
                "twitterHandle": twitter_handle,
                "facebookHandle": facebook_handle,
                "linkedinHandle": linkedin_handle,
                "instagramHandle": instagram_handle,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    Organization,
                    parse_obj_as(
                        type_=Organization,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)


class AsyncRawOrganizationClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._client_wrapper = client_wrapper

    async def get_organizations_in_a_batch(
        self, *, request: typing.Sequence[str], request_options: typing.Optional[RequestOptions] = None
    ) -> AsyncHttpResponse[typing.Dict[str, Organization]]:
        """
        Returns organizations keyed by their organization keys. Missing and inaccessible organizations are omitted.

        Parameters
        ----------
        request : typing.Sequence[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[typing.Dict[str, Organization]]
            OK
        """
        _response = await self._client_wrapper.httpx_client.request(
            "v2/organizations/batch/get",
            method="POST",
            json=request,
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    typing.Dict[str, Organization],
                    parse_obj_as(
                        type_=typing.Dict[str, Organization],  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def get_an_organization(
        self, organization_key: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> AsyncHttpResponse[Organization]:
        """
        Returns an organization accessible to the current user, including custom fields and relationships.

        Parameters
        ----------
        organization_key : str
            Key of the organization.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[Organization]
            OK
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"v2/organizations/{encode_path_param(organization_key)}",
            method="GET",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    Organization,
                    parse_obj_as(
                        type_=Organization,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def update_an_organization(
        self,
        organization_key: str,
        *,
        name: typing.Optional[str] = OMIT,
        other: typing.Optional[str] = OMIT,
        domains: typing.Optional[typing.Sequence[str]] = OMIT,
        industry: typing.Optional[str] = OMIT,
        phone_numbers: typing.Optional[typing.Sequence[str]] = OMIT,
        addresses: typing.Optional[typing.Sequence[str]] = OMIT,
        employee_count: typing.Optional[str] = OMIT,
        logo_url: typing.Optional[str] = OMIT,
        twitter_handle: typing.Optional[str] = OMIT,
        facebook_handle: typing.Optional[str] = OMIT,
        linkedin_handle: typing.Optional[str] = OMIT,
        instagram_handle: typing.Optional[str] = OMIT,
        contact_links: typing.Optional[typing.Sequence[ContactLinkInput]] = OMIT,
        org_links: typing.Optional[typing.Sequence[OrganizationLinkInput]] = OMIT,
        fields: typing.Optional[typing.Dict[str, typing.Optional[str]]] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[Organization]:
        """
        Updates an organization. Omitted and null properties are unchanged. Supplied lists replace existing lists, subject to field validation.

        Parameters
        ----------
        organization_key : str
            Key of the organization.

        name : typing.Optional[str]
            Replacement organization name. A name or domain must remain after the update.

        other : typing.Optional[str]
            Replacement notes. An empty string clears the notes.

        domains : typing.Optional[typing.Sequence[str]]
            Replacement domains, with the primary domain first. An empty list clears domains if a name remains.

        industry : typing.Optional[str]
            Replacement industry.

        phone_numbers : typing.Optional[typing.Sequence[str]]
            Replacement phone numbers. An empty list clears existing phone numbers.

        addresses : typing.Optional[typing.Sequence[str]]
            Replacement postal addresses. An empty list clears existing addresses.

        employee_count : typing.Optional[str]
            Replacement company size as text, including employee-count ranges.

        logo_url : typing.Optional[str]
            Replacement organization logo URL.

        twitter_handle : typing.Optional[str]
            Replacement Twitter profile handle or URL.

        facebook_handle : typing.Optional[str]
            Replacement Facebook profile handle or URL.

        linkedin_handle : typing.Optional[str]
            Replacement LinkedIn profile handle or URL.

        instagram_handle : typing.Optional[str]
            Replacement Instagram profile handle or URL.

        contact_links : typing.Optional[typing.Sequence[ContactLinkInput]]
            Replacement contact relationships. An empty list removes existing relationships.

        org_links : typing.Optional[typing.Sequence[OrganizationLinkInput]]
            Replacement organization relationships. An empty list removes existing relationships.

        fields : typing.Optional[typing.Dict[str, typing.Optional[str]]]
            Custom field values to change, keyed by field ID. Omitted keys and null values are unchanged; an empty object makes no changes.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[Organization]
            OK
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"v2/organizations/{encode_path_param(organization_key)}",
            method="POST",
            json={
                "name": name,
                "other": other,
                "domains": domains,
                "industry": industry,
                "phoneNumbers": phone_numbers,
                "addresses": addresses,
                "employeeCount": employee_count,
                "logoURL": logo_url,
                "twitterHandle": twitter_handle,
                "facebookHandle": facebook_handle,
                "linkedinHandle": linkedin_handle,
                "instagramHandle": instagram_handle,
                "contactLinks": convert_and_respect_annotation_metadata(
                    object_=contact_links,
                    annotation=typing.Optional[typing.Sequence[ContactLinkInput]],
                    direction="write",
                ),
                "orgLinks": convert_and_respect_annotation_metadata(
                    object_=org_links,
                    annotation=typing.Optional[typing.Sequence[OrganizationLinkInput]],
                    direction="write",
                ),
                "fields": fields,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    Organization,
                    parse_obj_as(
                        type_=Organization,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def delete_an_organization(
        self, organization_key: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> AsyncHttpResponse[OperationResponse]:
        """
        Deletes an organization and schedules removal of its relationships and box links.

        Parameters
        ----------
        organization_key : str
            Key of the organization.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[OperationResponse]
            OK
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"v2/organizations/{encode_path_param(organization_key)}",
            method="DELETE",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    OperationResponse,
                    parse_obj_as(
                        type_=OperationResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def list_organizations(
        self,
        team_key: str,
        *,
        cursor: typing.Optional[str] = None,
        limit: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[OrganizationPage]:
        """
        Returns organizations in a team, ordered by key. Pass the returned cursor to retrieve the next page.

        Parameters
        ----------
        team_key : str
            Key of the team.

        cursor : typing.Optional[str]
            Cursor returned by the previous response. Omit or leave blank to start from the beginning.

        limit : typing.Optional[int]
            Maximum number of results to return. Defaults to 100. Values above 1000 are capped.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[OrganizationPage]
            OK
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"v2/teams/{encode_path_param(team_key)}/organizations",
            method="GET",
            params={
                "cursor": cursor,
                "limit": limit,
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    OrganizationPage,
                    parse_obj_as(
                        type_=OrganizationPage,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def create_an_organization(
        self,
        team_key: str,
        *,
        get_if_existing: typing.Optional[bool] = None,
        name: typing.Optional[str] = OMIT,
        other: typing.Optional[str] = OMIT,
        domains: typing.Optional[typing.Sequence[str]] = OMIT,
        industry: typing.Optional[str] = OMIT,
        phone_numbers: typing.Optional[typing.Sequence[str]] = OMIT,
        addresses: typing.Optional[typing.Sequence[str]] = OMIT,
        employee_count: typing.Optional[str] = OMIT,
        logo_url: typing.Optional[str] = OMIT,
        twitter_handle: typing.Optional[str] = OMIT,
        facebook_handle: typing.Optional[str] = OMIT,
        linkedin_handle: typing.Optional[str] = OMIT,
        instagram_handle: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[Organization]:
        """
        Creates an organization in a team. Available enrichment data may fill missing details. Provide a name or at least one domain. Set custom fields and relationships in a subsequent update.

        Parameters
        ----------
        team_key : str
            Key of the team.

        get_if_existing : typing.Optional[bool]
            Return an existing organization matching a supplied domain instead of creating another organization. The supplied values are not merged into the existing organization.

        name : typing.Optional[str]
            Organization name.

        other : typing.Optional[str]
            Freeform notes about the organization.

        domains : typing.Optional[typing.Sequence[str]]
            Website domains for the organization, with the primary domain first.

        industry : typing.Optional[str]
            Industry of the organization.

        phone_numbers : typing.Optional[typing.Sequence[str]]
            Phone numbers for the organization.

        addresses : typing.Optional[typing.Sequence[str]]
            Postal addresses for the organization.

        employee_count : typing.Optional[str]
            Company size as text, which can include an employee-count range.

        logo_url : typing.Optional[str]
            URL of the organization's logo.

        twitter_handle : typing.Optional[str]
            Twitter profile handle or URL.

        facebook_handle : typing.Optional[str]
            Facebook profile handle or URL.

        linkedin_handle : typing.Optional[str]
            LinkedIn profile handle or URL.

        instagram_handle : typing.Optional[str]
            Instagram profile handle or URL.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[Organization]
            OK
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"v2/teams/{encode_path_param(team_key)}/organizations",
            method="POST",
            params={
                "getIfExisting": get_if_existing,
            },
            json={
                "name": name,
                "other": other,
                "domains": domains,
                "industry": industry,
                "phoneNumbers": phone_numbers,
                "addresses": addresses,
                "employeeCount": employee_count,
                "logoURL": logo_url,
                "twitterHandle": twitter_handle,
                "facebookHandle": facebook_handle,
                "linkedinHandle": linkedin_handle,
                "instagramHandle": instagram_handle,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    Organization,
                    parse_obj_as(
                        type_=Organization,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)
