# This file was auto-generated by Fern from our API Definition.

from __future__ import annotations

import typing

import httpx
from .core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from .core.logging import LogConfig, Logger
from .core.request_options import RequestOptions
from .environment import StreakEnvironment
from .raw_client import AsyncRawStreak, RawStreak
from .types.search_response import SearchResponse

if typing.TYPE_CHECKING:
    from .api_keys.client import ApiKeysClient, AsyncApiKeysClient
    from .boxes.client import AsyncBoxesClient, BoxesClient
    from .comments.client import AsyncCommentsClient, CommentsClient
    from .contacts.client import AsyncContactsClient, ContactsClient
    from .meetings.client import AsyncMeetingsClient, MeetingsClient
    from .organizations.client import AsyncOrganizationsClient, OrganizationsClient
    from .pipeline_stages.client import AsyncPipelineStagesClient, PipelineStagesClient
    from .pipelines.client import AsyncPipelinesClient, PipelinesClient
    from .tasks.client import AsyncTasksClient, TasksClient
    from .teams.client import AsyncTeamsClient, TeamsClient
    from .users.client import AsyncUsersClient, UsersClient


class Streak:
    """
    Use this class to access the different functions within the SDK. You can instantiate any number of clients with different configuration that will propagate to these functions.

    Parameters
    ----------
    base_url : typing.Optional[str]
        The base url to use for requests from the client.

    environment : StreakEnvironment
        The environment to use for requests from the client. from .environment import StreakEnvironment



        Defaults to StreakEnvironment.DEFAULT



    token : typing.Union[str, typing.Callable[[], str]]
    headers : typing.Optional[typing.Dict[str, str]]
        Additional headers to send with every request.

    timeout : typing.Optional[float]
        The timeout to be used, in seconds, for requests. By default the timeout is 60 seconds, unless a custom httpx client is used, in which case this default is not enforced.

    max_retries : typing.Optional[int]
        The default maximum number of retries for failed requests. Defaults to 2. Per-request `max_retries` in `request_options` takes precedence over this value.

    stream_reconnection_enabled : typing.Optional[bool]
        Whether to automatically reconnect on stream disconnection for resumable streaming endpoints. Defaults to True. Per-request `stream_reconnection_enabled` in `request_options` takes precedence over this value.

    max_stream_reconnection_attempts : typing.Optional[int]
        The maximum number of reconnection attempts for resumable streaming endpoints. Defaults to no limit. Per-request `max_stream_reconnection_attempts` in `request_options` takes precedence over this value.

    follow_redirects : typing.Optional[bool]
        Whether the default httpx client follows redirects or not, this is irrelevant if a custom httpx client is passed in.

    httpx_client : typing.Optional[httpx.Client]
        The httpx client to use for making requests, a preconfigured client is used by default, however this is useful should you want to pass in any custom httpx configuration.

    logging : typing.Optional[typing.Union[LogConfig, Logger]]
        Configure logging for the SDK. Accepts a LogConfig dict with 'level' (debug/info/warn/error), 'logger' (custom logger implementation), and 'silent' (boolean, defaults to True) fields. You can also pass a pre-configured Logger instance.

    Examples
    --------
    from streak_crm import Streak

    client = Streak(
        token="YOUR_TOKEN",
    )
    """

    def __init__(
        self,
        *,
        base_url: typing.Optional[str] = None,
        environment: StreakEnvironment = StreakEnvironment.DEFAULT,
        token: typing.Union[str, typing.Callable[[], str]],
        headers: typing.Optional[typing.Dict[str, str]] = None,
        timeout: typing.Optional[float] = None,
        max_retries: typing.Optional[int] = None,
        stream_reconnection_enabled: typing.Optional[bool] = None,
        max_stream_reconnection_attempts: typing.Optional[int] = None,
        follow_redirects: typing.Optional[bool] = True,
        httpx_client: typing.Optional[httpx.Client] = None,
        logging: typing.Optional[typing.Union[LogConfig, Logger]] = None,
    ):
        _defaulted_timeout = timeout if timeout is not None else 60 if httpx_client is None else None
        _defaulted_max_retries = max_retries if max_retries is not None else 2
        self._client_wrapper = SyncClientWrapper(
            base_url=_get_base_url(base_url=base_url, environment=environment),
            token=token,
            headers=headers,
            httpx_client=httpx_client
            if httpx_client is not None
            else httpx.Client(timeout=_defaulted_timeout, follow_redirects=follow_redirects)
            if follow_redirects is not None
            else httpx.Client(timeout=_defaulted_timeout),
            timeout=_defaulted_timeout,
            max_retries=_defaulted_max_retries,
            stream_reconnection_enabled=stream_reconnection_enabled,
            max_stream_reconnection_attempts=max_stream_reconnection_attempts,
            logging=logging,
        )
        self._raw_client = RawStreak(client_wrapper=self._client_wrapper)
        self._api_keys: typing.Optional[ApiKeysClient] = None
        self._boxes: typing.Optional[BoxesClient] = None
        self._pipelines: typing.Optional[PipelinesClient] = None
        self._users: typing.Optional[UsersClient] = None
        self._comments: typing.Optional[CommentsClient] = None
        self._meetings: typing.Optional[MeetingsClient] = None
        self._tasks: typing.Optional[TasksClient] = None
        self._contacts: typing.Optional[ContactsClient] = None
        self._organizations: typing.Optional[OrganizationsClient] = None
        self._pipeline_stages: typing.Optional[PipelineStagesClient] = None
        self._teams: typing.Optional[TeamsClient] = None

    @property
    def with_raw_response(self) -> RawStreak:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawStreak
        """
        return self._raw_client

    def search(
        self,
        *,
        name: typing.Optional[str] = None,
        page: typing.Optional[int] = None,
        pipeline_key: typing.Optional[typing.Sequence[str]] = None,
        query: typing.Optional[str] = None,
        stage_key: typing.Optional[typing.Sequence[str]] = None,
        team_key: typing.Optional[typing.Sequence[str]] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> SearchResponse:
        """
        Searches visible boxes, contacts, and organizations by query, or visible boxes by exact name. Exactly one of query or name must be provided.

        Parameters
        ----------
        name : typing.Optional[str]
            Exact box name to search for.

        page : typing.Optional[int]
            Zero-based page number.

        pipeline_key : typing.Optional[typing.Sequence[str]]
            Pipeline keys to constrain the search to.

        query : typing.Optional[str]
            Full-text query to search across boxes, contacts, and organizations.

        stage_key : typing.Optional[typing.Sequence[str]]
            Stage keys to constrain the search to.

        team_key : typing.Optional[typing.Sequence[str]]
            Team keys to constrain the search to.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        SearchResponse
            OK

        Examples
        --------
        from streak_crm import Streak

        client = Streak(
            token="YOUR_TOKEN",
        )
        client.search()
        """
        _response = self._raw_client.search(
            name=name,
            page=page,
            pipeline_key=pipeline_key,
            query=query,
            stage_key=stage_key,
            team_key=team_key,
            request_options=request_options,
        )
        return _response.data

    @property
    def api_keys(self):
        if self._api_keys is None:
            from .api_keys.client import ApiKeysClient  # noqa: E402

            self._api_keys = ApiKeysClient(client_wrapper=self._client_wrapper)
        return self._api_keys

    @property
    def boxes(self):
        if self._boxes is None:
            from .boxes.client import BoxesClient  # noqa: E402

            self._boxes = BoxesClient(client_wrapper=self._client_wrapper)
        return self._boxes

    @property
    def pipelines(self):
        if self._pipelines is None:
            from .pipelines.client import PipelinesClient  # noqa: E402

            self._pipelines = PipelinesClient(client_wrapper=self._client_wrapper)
        return self._pipelines

    @property
    def users(self):
        if self._users is None:
            from .users.client import UsersClient  # noqa: E402

            self._users = UsersClient(client_wrapper=self._client_wrapper)
        return self._users

    @property
    def comments(self):
        if self._comments is None:
            from .comments.client import CommentsClient  # noqa: E402

            self._comments = CommentsClient(client_wrapper=self._client_wrapper)
        return self._comments

    @property
    def meetings(self):
        if self._meetings is None:
            from .meetings.client import MeetingsClient  # noqa: E402

            self._meetings = MeetingsClient(client_wrapper=self._client_wrapper)
        return self._meetings

    @property
    def tasks(self):
        if self._tasks is None:
            from .tasks.client import TasksClient  # noqa: E402

            self._tasks = TasksClient(client_wrapper=self._client_wrapper)
        return self._tasks

    @property
    def contacts(self):
        if self._contacts is None:
            from .contacts.client import ContactsClient  # noqa: E402

            self._contacts = ContactsClient(client_wrapper=self._client_wrapper)
        return self._contacts

    @property
    def organizations(self):
        if self._organizations is None:
            from .organizations.client import OrganizationsClient  # noqa: E402

            self._organizations = OrganizationsClient(client_wrapper=self._client_wrapper)
        return self._organizations

    @property
    def pipeline_stages(self):
        if self._pipeline_stages is None:
            from .pipeline_stages.client import PipelineStagesClient  # noqa: E402

            self._pipeline_stages = PipelineStagesClient(client_wrapper=self._client_wrapper)
        return self._pipeline_stages

    @property
    def teams(self):
        if self._teams is None:
            from .teams.client import TeamsClient  # noqa: E402

            self._teams = TeamsClient(client_wrapper=self._client_wrapper)
        return self._teams


def _make_default_async_client(
    timeout: typing.Optional[float],
    follow_redirects: typing.Optional[bool],
) -> httpx.AsyncClient:
    try:
        import httpx_aiohttp  # type: ignore[import-not-found]
    except ImportError:
        pass
    else:
        if follow_redirects is not None:
            return httpx_aiohttp.HttpxAiohttpClient(timeout=timeout, follow_redirects=follow_redirects)
        return httpx_aiohttp.HttpxAiohttpClient(timeout=timeout)

    if follow_redirects is not None:
        return httpx.AsyncClient(timeout=timeout, follow_redirects=follow_redirects)
    return httpx.AsyncClient(timeout=timeout)


class AsyncStreak:
    """
    Use this class to access the different functions within the SDK. You can instantiate any number of clients with different configuration that will propagate to these functions.

    Parameters
    ----------
    base_url : typing.Optional[str]
        The base url to use for requests from the client.

    environment : StreakEnvironment
        The environment to use for requests from the client. from .environment import StreakEnvironment



        Defaults to StreakEnvironment.DEFAULT



    token : typing.Union[str, typing.Callable[[], str]]
    headers : typing.Optional[typing.Dict[str, str]]
        Additional headers to send with every request.

    async_token : typing.Optional[typing.Callable[[], typing.Awaitable[str]]]
        An async callable that returns a bearer token. Use this when token acquisition involves async I/O (e.g., refreshing tokens via an async HTTP client). When provided, this is used instead of the synchronous token for async requests.

    timeout : typing.Optional[float]
        The timeout to be used, in seconds, for requests. By default the timeout is 60 seconds, unless a custom httpx client is used, in which case this default is not enforced.

    max_retries : typing.Optional[int]
        The default maximum number of retries for failed requests. Defaults to 2. Per-request `max_retries` in `request_options` takes precedence over this value.

    stream_reconnection_enabled : typing.Optional[bool]
        Whether to automatically reconnect on stream disconnection for resumable streaming endpoints. Defaults to True. Per-request `stream_reconnection_enabled` in `request_options` takes precedence over this value.

    max_stream_reconnection_attempts : typing.Optional[int]
        The maximum number of reconnection attempts for resumable streaming endpoints. Defaults to no limit. Per-request `max_stream_reconnection_attempts` in `request_options` takes precedence over this value.

    follow_redirects : typing.Optional[bool]
        Whether the default httpx client follows redirects or not, this is irrelevant if a custom httpx client is passed in.

    httpx_client : typing.Optional[httpx.AsyncClient]
        The httpx client to use for making requests, a preconfigured client is used by default, however this is useful should you want to pass in any custom httpx configuration.

    logging : typing.Optional[typing.Union[LogConfig, Logger]]
        Configure logging for the SDK. Accepts a LogConfig dict with 'level' (debug/info/warn/error), 'logger' (custom logger implementation), and 'silent' (boolean, defaults to True) fields. You can also pass a pre-configured Logger instance.

    Examples
    --------
    from streak_crm import AsyncStreak

    client = AsyncStreak(
        token="YOUR_TOKEN",
    )
    """

    def __init__(
        self,
        *,
        base_url: typing.Optional[str] = None,
        environment: StreakEnvironment = StreakEnvironment.DEFAULT,
        token: typing.Union[str, typing.Callable[[], str]],
        headers: typing.Optional[typing.Dict[str, str]] = None,
        async_token: typing.Optional[typing.Callable[[], typing.Awaitable[str]]] = None,
        timeout: typing.Optional[float] = None,
        max_retries: typing.Optional[int] = None,
        stream_reconnection_enabled: typing.Optional[bool] = None,
        max_stream_reconnection_attempts: typing.Optional[int] = None,
        follow_redirects: typing.Optional[bool] = True,
        httpx_client: typing.Optional[httpx.AsyncClient] = None,
        logging: typing.Optional[typing.Union[LogConfig, Logger]] = None,
    ):
        _defaulted_timeout = timeout if timeout is not None else 60 if httpx_client is None else None
        _defaulted_max_retries = max_retries if max_retries is not None else 2
        self._client_wrapper = AsyncClientWrapper(
            base_url=_get_base_url(base_url=base_url, environment=environment),
            token=token,
            headers=headers,
            async_token=async_token,
            httpx_client=httpx_client
            if httpx_client is not None
            else _make_default_async_client(timeout=_defaulted_timeout, follow_redirects=follow_redirects),
            timeout=_defaulted_timeout,
            max_retries=_defaulted_max_retries,
            stream_reconnection_enabled=stream_reconnection_enabled,
            max_stream_reconnection_attempts=max_stream_reconnection_attempts,
            logging=logging,
        )
        self._raw_client = AsyncRawStreak(client_wrapper=self._client_wrapper)
        self._api_keys: typing.Optional[AsyncApiKeysClient] = None
        self._boxes: typing.Optional[AsyncBoxesClient] = None
        self._pipelines: typing.Optional[AsyncPipelinesClient] = None
        self._users: typing.Optional[AsyncUsersClient] = None
        self._comments: typing.Optional[AsyncCommentsClient] = None
        self._meetings: typing.Optional[AsyncMeetingsClient] = None
        self._tasks: typing.Optional[AsyncTasksClient] = None
        self._contacts: typing.Optional[AsyncContactsClient] = None
        self._organizations: typing.Optional[AsyncOrganizationsClient] = None
        self._pipeline_stages: typing.Optional[AsyncPipelineStagesClient] = None
        self._teams: typing.Optional[AsyncTeamsClient] = None

    @property
    def with_raw_response(self) -> AsyncRawStreak:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawStreak
        """
        return self._raw_client

    async def search(
        self,
        *,
        name: typing.Optional[str] = None,
        page: typing.Optional[int] = None,
        pipeline_key: typing.Optional[typing.Sequence[str]] = None,
        query: typing.Optional[str] = None,
        stage_key: typing.Optional[typing.Sequence[str]] = None,
        team_key: typing.Optional[typing.Sequence[str]] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> SearchResponse:
        """
        Searches visible boxes, contacts, and organizations by query, or visible boxes by exact name. Exactly one of query or name must be provided.

        Parameters
        ----------
        name : typing.Optional[str]
            Exact box name to search for.

        page : typing.Optional[int]
            Zero-based page number.

        pipeline_key : typing.Optional[typing.Sequence[str]]
            Pipeline keys to constrain the search to.

        query : typing.Optional[str]
            Full-text query to search across boxes, contacts, and organizations.

        stage_key : typing.Optional[typing.Sequence[str]]
            Stage keys to constrain the search to.

        team_key : typing.Optional[typing.Sequence[str]]
            Team keys to constrain the search to.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        SearchResponse
            OK

        Examples
        --------
        import asyncio

        from streak_crm import AsyncStreak

        client = AsyncStreak(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.search()


        asyncio.run(main())
        """
        _response = await self._raw_client.search(
            name=name,
            page=page,
            pipeline_key=pipeline_key,
            query=query,
            stage_key=stage_key,
            team_key=team_key,
            request_options=request_options,
        )
        return _response.data

    @property
    def api_keys(self):
        if self._api_keys is None:
            from .api_keys.client import AsyncApiKeysClient  # noqa: E402

            self._api_keys = AsyncApiKeysClient(client_wrapper=self._client_wrapper)
        return self._api_keys

    @property
    def boxes(self):
        if self._boxes is None:
            from .boxes.client import AsyncBoxesClient  # noqa: E402

            self._boxes = AsyncBoxesClient(client_wrapper=self._client_wrapper)
        return self._boxes

    @property
    def pipelines(self):
        if self._pipelines is None:
            from .pipelines.client import AsyncPipelinesClient  # noqa: E402

            self._pipelines = AsyncPipelinesClient(client_wrapper=self._client_wrapper)
        return self._pipelines

    @property
    def users(self):
        if self._users is None:
            from .users.client import AsyncUsersClient  # noqa: E402

            self._users = AsyncUsersClient(client_wrapper=self._client_wrapper)
        return self._users

    @property
    def comments(self):
        if self._comments is None:
            from .comments.client import AsyncCommentsClient  # noqa: E402

            self._comments = AsyncCommentsClient(client_wrapper=self._client_wrapper)
        return self._comments

    @property
    def meetings(self):
        if self._meetings is None:
            from .meetings.client import AsyncMeetingsClient  # noqa: E402

            self._meetings = AsyncMeetingsClient(client_wrapper=self._client_wrapper)
        return self._meetings

    @property
    def tasks(self):
        if self._tasks is None:
            from .tasks.client import AsyncTasksClient  # noqa: E402

            self._tasks = AsyncTasksClient(client_wrapper=self._client_wrapper)
        return self._tasks

    @property
    def contacts(self):
        if self._contacts is None:
            from .contacts.client import AsyncContactsClient  # noqa: E402

            self._contacts = AsyncContactsClient(client_wrapper=self._client_wrapper)
        return self._contacts

    @property
    def organizations(self):
        if self._organizations is None:
            from .organizations.client import AsyncOrganizationsClient  # noqa: E402

            self._organizations = AsyncOrganizationsClient(client_wrapper=self._client_wrapper)
        return self._organizations

    @property
    def pipeline_stages(self):
        if self._pipeline_stages is None:
            from .pipeline_stages.client import AsyncPipelineStagesClient  # noqa: E402

            self._pipeline_stages = AsyncPipelineStagesClient(client_wrapper=self._client_wrapper)
        return self._pipeline_stages

    @property
    def teams(self):
        if self._teams is None:
            from .teams.client import AsyncTeamsClient  # noqa: E402

            self._teams = AsyncTeamsClient(client_wrapper=self._client_wrapper)
        return self._teams


def _get_base_url(*, base_url: typing.Optional[str] = None, environment: StreakEnvironment) -> str:
    if base_url is not None:
        return base_url
    elif environment is not None:
        return environment.value
    else:
        raise Exception("Please pass in either base_url or environment to construct the client")
