# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from ..types.user import User
from ..types.user_list_response import UserListResponse
from .raw_client import AsyncRawUsersClient, RawUsersClient

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class UsersClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawUsersClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawUsersClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawUsersClient
        """
        return self._raw_client

    def get_current_user(self, *, request_options: typing.Optional[RequestOptions] = None) -> User:
        """
        Returns information about the currently authenticated user

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        User
            OK

        Examples
        --------
        from streak_crm import Streak

        client = Streak(
            token="YOUR_TOKEN",
        )
        client.users.get_current_user()
        """
        _response = self._raw_client.get_current_user(request_options=request_options)
        return _response.data

    def get_user_by_key(self, user_key: str, *, request_options: typing.Optional[RequestOptions] = None) -> User:
        """
        Returns information about a specific user by their key

        Parameters
        ----------
        user_key : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        User
            OK

        Examples
        --------
        from streak_crm import Streak

        client = Streak(
            token="YOUR_TOKEN",
        )
        client.users.get_user_by_key(
            user_key="userKey",
        )
        """
        _response = self._raw_client.get_user_by_key(user_key, request_options=request_options)
        return _response.data

    def update_user_by_key(
        self,
        user_key: str,
        *,
        timezone_id: typing.Optional[str] = OMIT,
        first_name: typing.Optional[str] = OMIT,
        last_name: typing.Optional[str] = OMIT,
        automatically_send_invoice_emails: typing.Optional[bool] = OMIT,
        emails_to_send_invoice_to: typing.Optional[typing.Sequence[str]] = OMIT,
        customer_specified_invoice_data: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> User:
        """
        Updates a specific user by their key

        Parameters
        ----------
        user_key : str

        timezone_id : typing.Optional[str]
            IANA timezone identifier for the user, such as America/Los_Angeles.

        first_name : typing.Optional[str]
            Given name for the user.

        last_name : typing.Optional[str]
            Family name for the user.

        automatically_send_invoice_emails : typing.Optional[bool]
            Whether invoice emails should be sent automatically.

        emails_to_send_invoice_to : typing.Optional[typing.Sequence[str]]
            Who should receive invoices

        customer_specified_invoice_data : typing.Optional[str]
            Custom data that should be shown on the invoice

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        User
            OK

        Examples
        --------
        from streak_crm import Streak

        client = Streak(
            token="YOUR_TOKEN",
        )
        client.users.update_user_by_key(
            user_key="userKey",
        )
        """
        _response = self._raw_client.update_user_by_key(
            user_key,
            timezone_id=timezone_id,
            first_name=first_name,
            last_name=last_name,
            automatically_send_invoice_emails=automatically_send_invoice_emails,
            emails_to_send_invoice_to=emails_to_send_invoice_to,
            customer_specified_invoice_data=customer_specified_invoice_data,
            request_options=request_options,
        )
        return _response.data

    def get_all_users_on_team(
        self, team_key: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> UserListResponse:
        """
        Returns all the users on a single team including archived users, payer only users, agents, owners and regular members.

        Parameters
        ----------
        team_key : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        UserListResponse
            OK

        Examples
        --------
        from streak_crm import Streak

        client = Streak(
            token="YOUR_TOKEN",
        )
        client.users.get_all_users_on_team(
            team_key="teamKey",
        )
        """
        _response = self._raw_client.get_all_users_on_team(team_key, request_options=request_options)
        return _response.data


class AsyncUsersClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawUsersClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawUsersClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawUsersClient
        """
        return self._raw_client

    async def get_current_user(self, *, request_options: typing.Optional[RequestOptions] = None) -> User:
        """
        Returns information about the currently authenticated user

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        User
            OK

        Examples
        --------
        import asyncio

        from streak_crm import AsyncStreak

        client = AsyncStreak(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.users.get_current_user()


        asyncio.run(main())
        """
        _response = await self._raw_client.get_current_user(request_options=request_options)
        return _response.data

    async def get_user_by_key(self, user_key: str, *, request_options: typing.Optional[RequestOptions] = None) -> User:
        """
        Returns information about a specific user by their key

        Parameters
        ----------
        user_key : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        User
            OK

        Examples
        --------
        import asyncio

        from streak_crm import AsyncStreak

        client = AsyncStreak(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.users.get_user_by_key(
                user_key="userKey",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get_user_by_key(user_key, request_options=request_options)
        return _response.data

    async def update_user_by_key(
        self,
        user_key: str,
        *,
        timezone_id: typing.Optional[str] = OMIT,
        first_name: typing.Optional[str] = OMIT,
        last_name: typing.Optional[str] = OMIT,
        automatically_send_invoice_emails: typing.Optional[bool] = OMIT,
        emails_to_send_invoice_to: typing.Optional[typing.Sequence[str]] = OMIT,
        customer_specified_invoice_data: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> User:
        """
        Updates a specific user by their key

        Parameters
        ----------
        user_key : str

        timezone_id : typing.Optional[str]
            IANA timezone identifier for the user, such as America/Los_Angeles.

        first_name : typing.Optional[str]
            Given name for the user.

        last_name : typing.Optional[str]
            Family name for the user.

        automatically_send_invoice_emails : typing.Optional[bool]
            Whether invoice emails should be sent automatically.

        emails_to_send_invoice_to : typing.Optional[typing.Sequence[str]]
            Who should receive invoices

        customer_specified_invoice_data : typing.Optional[str]
            Custom data that should be shown on the invoice

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        User
            OK

        Examples
        --------
        import asyncio

        from streak_crm import AsyncStreak

        client = AsyncStreak(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.users.update_user_by_key(
                user_key="userKey",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.update_user_by_key(
            user_key,
            timezone_id=timezone_id,
            first_name=first_name,
            last_name=last_name,
            automatically_send_invoice_emails=automatically_send_invoice_emails,
            emails_to_send_invoice_to=emails_to_send_invoice_to,
            customer_specified_invoice_data=customer_specified_invoice_data,
            request_options=request_options,
        )
        return _response.data

    async def get_all_users_on_team(
        self, team_key: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> UserListResponse:
        """
        Returns all the users on a single team including archived users, payer only users, agents, owners and regular members.

        Parameters
        ----------
        team_key : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        UserListResponse
            OK

        Examples
        --------
        import asyncio

        from streak_crm import AsyncStreak

        client = AsyncStreak(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.users.get_all_users_on_team(
                team_key="teamKey",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get_all_users_on_team(team_key, request_options=request_options)
        return _response.data
