# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from ..types.comment import Comment
from ..types.comment_list_response import CommentListResponse
from ..types.comment_mention_body import CommentMentionBody
from ..types.operation_response import OperationResponse
from .raw_client import AsyncRawCommentsClient, RawCommentsClient

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class CommentsClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawCommentsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawCommentsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawCommentsClient
        """
        return self._raw_client

    def list_comments(
        self, box_key: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> CommentListResponse:
        """
        Lists comments on a box

        Parameters
        ----------
        box_key : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        CommentListResponse
            OK

        Examples
        --------
        from streak_crm import Streak

        client = Streak(
            token="YOUR_TOKEN",
        )
        client.comments.list_comments(
            box_key="boxKey",
        )
        """
        _response = self._raw_client.list_comments(box_key, request_options=request_options)
        return _response.data

    def create_comment(
        self,
        box_key: str,
        *,
        message: str,
        mentions: typing.Optional[typing.Sequence[CommentMentionBody]] = OMIT,
        parent: typing.Optional[str] = OMIT,
        search_for_at_mentions: typing.Optional[bool] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> Comment:
        """
        Creates a comment on a box

        Parameters
        ----------
        box_key : str

        message : str
            Comment text.

        mentions : typing.Optional[typing.Sequence[CommentMentionBody]]
            Mention ranges in the comment text.

        parent : typing.Optional[str]
            Parent comment key when creating a reply.

        search_for_at_mentions : typing.Optional[bool]
            Whether to scan the comment text for unstructured @mentions of users display name, first name or email address.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        Comment
            OK

        Examples
        --------
        from streak_crm import Streak

        client = Streak(
            token="YOUR_TOKEN",
        )
        client.comments.create_comment(
            box_key="boxKey",
            message="message",
        )
        """
        _response = self._raw_client.create_comment(
            box_key,
            message=message,
            mentions=mentions,
            parent=parent,
            search_for_at_mentions=search_for_at_mentions,
            request_options=request_options,
        )
        return _response.data

    def get_comment(self, comment_key: str, *, request_options: typing.Optional[RequestOptions] = None) -> Comment:
        """
        Returns a comment by key

        Parameters
        ----------
        comment_key : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        Comment
            OK

        Examples
        --------
        from streak_crm import Streak

        client = Streak(
            token="YOUR_TOKEN",
        )
        client.comments.get_comment(
            comment_key="commentKey",
        )
        """
        _response = self._raw_client.get_comment(comment_key, request_options=request_options)
        return _response.data

    def update_comment(
        self,
        comment_key: str,
        *,
        message: typing.Optional[str] = OMIT,
        mentions: typing.Optional[typing.Sequence[CommentMentionBody]] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> Comment:
        """
        Updates a comment by key

        Parameters
        ----------
        comment_key : str

        message : typing.Optional[str]
            New comment text. Omit this field to keep the existing comment text unchanged.

        mentions : typing.Optional[typing.Sequence[CommentMentionBody]]
            New mention ranges for the comment text. Omit this field to keep existing mentions unchanged.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        Comment
            OK

        Examples
        --------
        from streak_crm import Streak

        client = Streak(
            token="YOUR_TOKEN",
        )
        client.comments.update_comment(
            comment_key="commentKey",
        )
        """
        _response = self._raw_client.update_comment(
            comment_key, message=message, mentions=mentions, request_options=request_options
        )
        return _response.data

    def delete_comment(
        self, comment_key: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> OperationResponse:
        """
        Deletes a comment by key

        Parameters
        ----------
        comment_key : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        OperationResponse
            OK

        Examples
        --------
        from streak_crm import Streak

        client = Streak(
            token="YOUR_TOKEN",
        )
        client.comments.delete_comment(
            comment_key="commentKey",
        )
        """
        _response = self._raw_client.delete_comment(comment_key, request_options=request_options)
        return _response.data

    def react_to_comment(
        self, comment_key: str, *, emoji: str, request_options: typing.Optional[RequestOptions] = None
    ) -> Comment:
        """
        Adds an emoji reaction to a comment

        Parameters
        ----------
        comment_key : str

        emoji : str
            Emoji to add or remove as a reaction.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        Comment
            OK

        Examples
        --------
        from streak_crm import Streak

        client = Streak(
            token="YOUR_TOKEN",
        )
        client.comments.react_to_comment(
            comment_key="commentKey",
            emoji="emoji",
        )
        """
        _response = self._raw_client.react_to_comment(comment_key, emoji=emoji, request_options=request_options)
        return _response.data

    def remove_comment_reaction(
        self, comment_key: str, *, emoji: str, request_options: typing.Optional[RequestOptions] = None
    ) -> Comment:
        """
        Removes an emoji reaction from a comment

        Parameters
        ----------
        comment_key : str

        emoji : str
            Emoji to add or remove as a reaction.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        Comment
            OK

        Examples
        --------
        from streak_crm import Streak

        client = Streak(
            token="YOUR_TOKEN",
        )
        client.comments.remove_comment_reaction(
            comment_key="commentKey",
            emoji="emoji",
        )
        """
        _response = self._raw_client.remove_comment_reaction(comment_key, emoji=emoji, request_options=request_options)
        return _response.data


class AsyncCommentsClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawCommentsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawCommentsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawCommentsClient
        """
        return self._raw_client

    async def list_comments(
        self, box_key: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> CommentListResponse:
        """
        Lists comments on a box

        Parameters
        ----------
        box_key : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        CommentListResponse
            OK

        Examples
        --------
        import asyncio

        from streak_crm import AsyncStreak

        client = AsyncStreak(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.comments.list_comments(
                box_key="boxKey",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.list_comments(box_key, request_options=request_options)
        return _response.data

    async def create_comment(
        self,
        box_key: str,
        *,
        message: str,
        mentions: typing.Optional[typing.Sequence[CommentMentionBody]] = OMIT,
        parent: typing.Optional[str] = OMIT,
        search_for_at_mentions: typing.Optional[bool] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> Comment:
        """
        Creates a comment on a box

        Parameters
        ----------
        box_key : str

        message : str
            Comment text.

        mentions : typing.Optional[typing.Sequence[CommentMentionBody]]
            Mention ranges in the comment text.

        parent : typing.Optional[str]
            Parent comment key when creating a reply.

        search_for_at_mentions : typing.Optional[bool]
            Whether to scan the comment text for unstructured @mentions of users display name, first name or email address.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        Comment
            OK

        Examples
        --------
        import asyncio

        from streak_crm import AsyncStreak

        client = AsyncStreak(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.comments.create_comment(
                box_key="boxKey",
                message="message",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.create_comment(
            box_key,
            message=message,
            mentions=mentions,
            parent=parent,
            search_for_at_mentions=search_for_at_mentions,
            request_options=request_options,
        )
        return _response.data

    async def get_comment(
        self, comment_key: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> Comment:
        """
        Returns a comment by key

        Parameters
        ----------
        comment_key : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        Comment
            OK

        Examples
        --------
        import asyncio

        from streak_crm import AsyncStreak

        client = AsyncStreak(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.comments.get_comment(
                comment_key="commentKey",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get_comment(comment_key, request_options=request_options)
        return _response.data

    async def update_comment(
        self,
        comment_key: str,
        *,
        message: typing.Optional[str] = OMIT,
        mentions: typing.Optional[typing.Sequence[CommentMentionBody]] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> Comment:
        """
        Updates a comment by key

        Parameters
        ----------
        comment_key : str

        message : typing.Optional[str]
            New comment text. Omit this field to keep the existing comment text unchanged.

        mentions : typing.Optional[typing.Sequence[CommentMentionBody]]
            New mention ranges for the comment text. Omit this field to keep existing mentions unchanged.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        Comment
            OK

        Examples
        --------
        import asyncio

        from streak_crm import AsyncStreak

        client = AsyncStreak(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.comments.update_comment(
                comment_key="commentKey",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.update_comment(
            comment_key, message=message, mentions=mentions, request_options=request_options
        )
        return _response.data

    async def delete_comment(
        self, comment_key: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> OperationResponse:
        """
        Deletes a comment by key

        Parameters
        ----------
        comment_key : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        OperationResponse
            OK

        Examples
        --------
        import asyncio

        from streak_crm import AsyncStreak

        client = AsyncStreak(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.comments.delete_comment(
                comment_key="commentKey",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.delete_comment(comment_key, request_options=request_options)
        return _response.data

    async def react_to_comment(
        self, comment_key: str, *, emoji: str, request_options: typing.Optional[RequestOptions] = None
    ) -> Comment:
        """
        Adds an emoji reaction to a comment

        Parameters
        ----------
        comment_key : str

        emoji : str
            Emoji to add or remove as a reaction.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        Comment
            OK

        Examples
        --------
        import asyncio

        from streak_crm import AsyncStreak

        client = AsyncStreak(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.comments.react_to_comment(
                comment_key="commentKey",
                emoji="emoji",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.react_to_comment(comment_key, emoji=emoji, request_options=request_options)
        return _response.data

    async def remove_comment_reaction(
        self, comment_key: str, *, emoji: str, request_options: typing.Optional[RequestOptions] = None
    ) -> Comment:
        """
        Removes an emoji reaction from a comment

        Parameters
        ----------
        comment_key : str

        emoji : str
            Emoji to add or remove as a reaction.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        Comment
            OK

        Examples
        --------
        import asyncio

        from streak_crm import AsyncStreak

        client = AsyncStreak(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.comments.remove_comment_reaction(
                comment_key="commentKey",
                emoji="emoji",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.remove_comment_reaction(
            comment_key, emoji=emoji, request_options=request_options
        )
        return _response.data
