# This file was auto-generated by Fern from our API Definition.

import typing
from json.decoder import JSONDecodeError

from ..core.api_error import ApiError
from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.http_response import AsyncHttpResponse, HttpResponse
from ..core.jsonable_encoder import encode_path_param
from ..core.parse_error import ParsingError
from ..core.pydantic_utilities import parse_obj_as
from ..core.request_options import RequestOptions
from ..core.serialization import convert_and_respect_annotation_metadata
from ..types.comment import Comment
from ..types.comment_list_response import CommentListResponse
from ..types.comment_mention_body import CommentMentionBody
from ..types.operation_response import OperationResponse
from pydantic import ValidationError

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class RawCommentsClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._client_wrapper = client_wrapper

    def list_comments(
        self, box_key: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> HttpResponse[CommentListResponse]:
        """
        Lists comments on a box

        Parameters
        ----------
        box_key : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[CommentListResponse]
            OK
        """
        _response = self._client_wrapper.httpx_client.request(
            f"v2/boxes/{encode_path_param(box_key)}/comments",
            method="GET",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    CommentListResponse,
                    parse_obj_as(
                        type_=CommentListResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def create_comment(
        self,
        box_key: str,
        *,
        message: str,
        mentions: typing.Optional[typing.Sequence[CommentMentionBody]] = OMIT,
        parent: typing.Optional[str] = OMIT,
        search_for_at_mentions: typing.Optional[bool] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[Comment]:
        """
        Creates a comment on a box

        Parameters
        ----------
        box_key : str

        message : str
            Comment text.

        mentions : typing.Optional[typing.Sequence[CommentMentionBody]]
            Mention ranges in the comment text.

        parent : typing.Optional[str]
            Parent comment key when creating a reply.

        search_for_at_mentions : typing.Optional[bool]
            Whether to scan the comment text for unstructured @mentions of users display name, first name or email address.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[Comment]
            OK
        """
        _response = self._client_wrapper.httpx_client.request(
            f"v2/boxes/{encode_path_param(box_key)}/comments",
            method="POST",
            json={
                "message": message,
                "mentions": convert_and_respect_annotation_metadata(
                    object_=mentions, annotation=typing.Optional[typing.Sequence[CommentMentionBody]], direction="write"
                ),
                "parent": parent,
                "searchForAtMentions": search_for_at_mentions,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    Comment,
                    parse_obj_as(
                        type_=Comment,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def get_comment(
        self, comment_key: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> HttpResponse[Comment]:
        """
        Returns a comment by key

        Parameters
        ----------
        comment_key : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[Comment]
            OK
        """
        _response = self._client_wrapper.httpx_client.request(
            f"v2/comments/{encode_path_param(comment_key)}",
            method="GET",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    Comment,
                    parse_obj_as(
                        type_=Comment,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def update_comment(
        self,
        comment_key: str,
        *,
        message: typing.Optional[str] = OMIT,
        mentions: typing.Optional[typing.Sequence[CommentMentionBody]] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[Comment]:
        """
        Updates a comment by key

        Parameters
        ----------
        comment_key : str

        message : typing.Optional[str]
            New comment text. Omit this field to keep the existing comment text unchanged.

        mentions : typing.Optional[typing.Sequence[CommentMentionBody]]
            New mention ranges for the comment text. Omit this field to keep existing mentions unchanged.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[Comment]
            OK
        """
        _response = self._client_wrapper.httpx_client.request(
            f"v2/comments/{encode_path_param(comment_key)}",
            method="POST",
            json={
                "message": message,
                "mentions": convert_and_respect_annotation_metadata(
                    object_=mentions, annotation=typing.Optional[typing.Sequence[CommentMentionBody]], direction="write"
                ),
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    Comment,
                    parse_obj_as(
                        type_=Comment,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def delete_comment(
        self, comment_key: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> HttpResponse[OperationResponse]:
        """
        Deletes a comment by key

        Parameters
        ----------
        comment_key : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[OperationResponse]
            OK
        """
        _response = self._client_wrapper.httpx_client.request(
            f"v2/comments/{encode_path_param(comment_key)}",
            method="DELETE",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    OperationResponse,
                    parse_obj_as(
                        type_=OperationResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def react_to_comment(
        self, comment_key: str, *, emoji: str, request_options: typing.Optional[RequestOptions] = None
    ) -> HttpResponse[Comment]:
        """
        Adds an emoji reaction to a comment

        Parameters
        ----------
        comment_key : str

        emoji : str
            Emoji to add or remove as a reaction.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[Comment]
            OK
        """
        _response = self._client_wrapper.httpx_client.request(
            f"v2/comments/{encode_path_param(comment_key)}/react",
            method="POST",
            json={
                "emoji": emoji,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    Comment,
                    parse_obj_as(
                        type_=Comment,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def remove_comment_reaction(
        self, comment_key: str, *, emoji: str, request_options: typing.Optional[RequestOptions] = None
    ) -> HttpResponse[Comment]:
        """
        Removes an emoji reaction from a comment

        Parameters
        ----------
        comment_key : str

        emoji : str
            Emoji to add or remove as a reaction.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[Comment]
            OK
        """
        _response = self._client_wrapper.httpx_client.request(
            f"v2/comments/{encode_path_param(comment_key)}/unreact",
            method="POST",
            json={
                "emoji": emoji,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    Comment,
                    parse_obj_as(
                        type_=Comment,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)


class AsyncRawCommentsClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._client_wrapper = client_wrapper

    async def list_comments(
        self, box_key: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> AsyncHttpResponse[CommentListResponse]:
        """
        Lists comments on a box

        Parameters
        ----------
        box_key : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[CommentListResponse]
            OK
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"v2/boxes/{encode_path_param(box_key)}/comments",
            method="GET",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    CommentListResponse,
                    parse_obj_as(
                        type_=CommentListResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def create_comment(
        self,
        box_key: str,
        *,
        message: str,
        mentions: typing.Optional[typing.Sequence[CommentMentionBody]] = OMIT,
        parent: typing.Optional[str] = OMIT,
        search_for_at_mentions: typing.Optional[bool] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[Comment]:
        """
        Creates a comment on a box

        Parameters
        ----------
        box_key : str

        message : str
            Comment text.

        mentions : typing.Optional[typing.Sequence[CommentMentionBody]]
            Mention ranges in the comment text.

        parent : typing.Optional[str]
            Parent comment key when creating a reply.

        search_for_at_mentions : typing.Optional[bool]
            Whether to scan the comment text for unstructured @mentions of users display name, first name or email address.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[Comment]
            OK
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"v2/boxes/{encode_path_param(box_key)}/comments",
            method="POST",
            json={
                "message": message,
                "mentions": convert_and_respect_annotation_metadata(
                    object_=mentions, annotation=typing.Optional[typing.Sequence[CommentMentionBody]], direction="write"
                ),
                "parent": parent,
                "searchForAtMentions": search_for_at_mentions,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    Comment,
                    parse_obj_as(
                        type_=Comment,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def get_comment(
        self, comment_key: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> AsyncHttpResponse[Comment]:
        """
        Returns a comment by key

        Parameters
        ----------
        comment_key : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[Comment]
            OK
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"v2/comments/{encode_path_param(comment_key)}",
            method="GET",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    Comment,
                    parse_obj_as(
                        type_=Comment,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def update_comment(
        self,
        comment_key: str,
        *,
        message: typing.Optional[str] = OMIT,
        mentions: typing.Optional[typing.Sequence[CommentMentionBody]] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[Comment]:
        """
        Updates a comment by key

        Parameters
        ----------
        comment_key : str

        message : typing.Optional[str]
            New comment text. Omit this field to keep the existing comment text unchanged.

        mentions : typing.Optional[typing.Sequence[CommentMentionBody]]
            New mention ranges for the comment text. Omit this field to keep existing mentions unchanged.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[Comment]
            OK
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"v2/comments/{encode_path_param(comment_key)}",
            method="POST",
            json={
                "message": message,
                "mentions": convert_and_respect_annotation_metadata(
                    object_=mentions, annotation=typing.Optional[typing.Sequence[CommentMentionBody]], direction="write"
                ),
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    Comment,
                    parse_obj_as(
                        type_=Comment,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def delete_comment(
        self, comment_key: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> AsyncHttpResponse[OperationResponse]:
        """
        Deletes a comment by key

        Parameters
        ----------
        comment_key : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[OperationResponse]
            OK
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"v2/comments/{encode_path_param(comment_key)}",
            method="DELETE",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    OperationResponse,
                    parse_obj_as(
                        type_=OperationResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def react_to_comment(
        self, comment_key: str, *, emoji: str, request_options: typing.Optional[RequestOptions] = None
    ) -> AsyncHttpResponse[Comment]:
        """
        Adds an emoji reaction to a comment

        Parameters
        ----------
        comment_key : str

        emoji : str
            Emoji to add or remove as a reaction.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[Comment]
            OK
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"v2/comments/{encode_path_param(comment_key)}/react",
            method="POST",
            json={
                "emoji": emoji,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    Comment,
                    parse_obj_as(
                        type_=Comment,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def remove_comment_reaction(
        self, comment_key: str, *, emoji: str, request_options: typing.Optional[RequestOptions] = None
    ) -> AsyncHttpResponse[Comment]:
        """
        Removes an emoji reaction from a comment

        Parameters
        ----------
        comment_key : str

        emoji : str
            Emoji to add or remove as a reaction.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[Comment]
            OK
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"v2/comments/{encode_path_param(comment_key)}/unreact",
            method="POST",
            json={
                "emoji": emoji,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    Comment,
                    parse_obj_as(
                        type_=Comment,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)
