# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from ..types.contact import Contact
from ..types.contact_key_batch import ContactKeyBatch
from ..types.contact_link_input import ContactLinkInput
from ..types.contact_page import ContactPage
from ..types.operation_response import OperationResponse
from ..types.organization_link_input import OrganizationLinkInput
from .raw_client import AsyncRawContactClient, RawContactClient

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class ContactClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawContactClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawContactClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawContactClient
        """
        return self._raw_client

    def get_contacts_in_bulk(
        self, *, request: typing.Sequence[str], request_options: typing.Optional[RequestOptions] = None
    ) -> ContactKeyBatch:
        """
        Returns accessible contacts indexed by their requested keys. Missing and inaccessible contacts are omitted.

        Parameters
        ----------
        request : typing.Sequence[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ContactKeyBatch
            Contacts indexed by their requested keys.

        Examples
        --------
        from streak_crm import Streak

        client = Streak(
            token="YOUR_TOKEN",
        )
        client.contact.get_contacts_in_bulk(
            request=["string"],
        )
        """
        _response = self._raw_client.get_contacts_in_bulk(request=request, request_options=request_options)
        return _response.data

    def get_contact(self, contact_key: str, *, request_options: typing.Optional[RequestOptions] = None) -> Contact:
        """
        Returns an accessible contact by key.

        Parameters
        ----------
        contact_key : str
            Key of the contact.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        Contact
            OK

        Examples
        --------
        from streak_crm import Streak

        client = Streak(
            token="YOUR_TOKEN",
        )
        client.contact.get_contact(
            contact_key="contactKey",
        )
        """
        _response = self._raw_client.get_contact(contact_key, request_options=request_options)
        return _response.data

    def update_contact(
        self,
        contact_key: str,
        *,
        given_name: typing.Optional[str] = OMIT,
        family_name: typing.Optional[str] = OMIT,
        title: typing.Optional[str] = OMIT,
        other: typing.Optional[str] = OMIT,
        email_addresses: typing.Optional[typing.Sequence[str]] = OMIT,
        phone_numbers: typing.Optional[typing.Sequence[str]] = OMIT,
        addresses: typing.Optional[typing.Sequence[str]] = OMIT,
        domains: typing.Optional[typing.Sequence[str]] = OMIT,
        twitter_handle: typing.Optional[str] = OMIT,
        facebook_handle: typing.Optional[str] = OMIT,
        linkedin_handle: typing.Optional[str] = OMIT,
        instagram_handle: typing.Optional[str] = OMIT,
        photo_url: typing.Optional[str] = OMIT,
        fields: typing.Optional[typing.Dict[str, typing.Optional[str]]] = OMIT,
        contact_links: typing.Optional[typing.Sequence[ContactLinkInput]] = OMIT,
        org_links: typing.Optional[typing.Sequence[OrganizationLinkInput]] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> Contact:
        """
        Applies supplied changes. Null or omitted fields remain unchanged.

        Parameters
        ----------
        contact_key : str
            Key of the contact.

        given_name : typing.Optional[str]
            New given name; an empty string clears it if another identifier remains.

        family_name : typing.Optional[str]
            New family name; an empty string clears it if another identifier remains.

        title : typing.Optional[str]
            New job title; an empty string clears it.

        other : typing.Optional[str]
            New notes; an empty string clears them.

        email_addresses : typing.Optional[typing.Sequence[str]]
            Replacement email addresses; a contact must retain an email address or a name.

        phone_numbers : typing.Optional[typing.Sequence[str]]
            Replacement phone numbers. Empty entries are removed.

        addresses : typing.Optional[typing.Sequence[str]]
            Replacement postal addresses. Empty entries are removed.

        domains : typing.Optional[typing.Sequence[str]]
            Replacement website domains.

        twitter_handle : typing.Optional[str]
            Replacement Twitter handle.

        facebook_handle : typing.Optional[str]
            Replacement Facebook handle.

        linkedin_handle : typing.Optional[str]
            Replacement LinkedIn handle.

        instagram_handle : typing.Optional[str]
            Replacement Instagram handle.

        photo_url : typing.Optional[str]
            Replacement photo URL.

        fields : typing.Optional[typing.Dict[str, typing.Optional[str]]]
            Custom-field values to merge by field key. Null entries are ignored; an empty map leaves existing fields unchanged.

        contact_links : typing.Optional[typing.Sequence[ContactLinkInput]]
            Replacement links to contacts; an empty list removes the links.

        org_links : typing.Optional[typing.Sequence[OrganizationLinkInput]]
            Replacement links to organizations; an empty list removes the links.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        Contact
            OK

        Examples
        --------
        from streak_crm import Streak

        client = Streak(
            token="YOUR_TOKEN",
        )
        client.contact.update_contact(
            contact_key="contactKey",
        )
        """
        _response = self._raw_client.update_contact(
            contact_key,
            given_name=given_name,
            family_name=family_name,
            title=title,
            other=other,
            email_addresses=email_addresses,
            phone_numbers=phone_numbers,
            addresses=addresses,
            domains=domains,
            twitter_handle=twitter_handle,
            facebook_handle=facebook_handle,
            linkedin_handle=linkedin_handle,
            instagram_handle=instagram_handle,
            photo_url=photo_url,
            fields=fields,
            contact_links=contact_links,
            org_links=org_links,
            request_options=request_options,
        )
        return _response.data

    def delete_contact(
        self, contact_key: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> OperationResponse:
        """
        Deletes a contact and schedules cleanup of its links. A missing contact returns 404.

        Parameters
        ----------
        contact_key : str
            Key of the contact.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        OperationResponse
            OK

        Examples
        --------
        from streak_crm import Streak

        client = Streak(
            token="YOUR_TOKEN",
        )
        client.contact.delete_contact(
            contact_key="contactKey",
        )
        """
        _response = self._raw_client.delete_contact(contact_key, request_options=request_options)
        return _response.data

    def list_contacts(
        self,
        team_key: str,
        *,
        after: typing.Optional[int] = None,
        cursor: typing.Optional[str] = None,
        limit: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ContactPage:
        """
        Lists contacts in stable order. Pass the returned cursor to continue; keep the same after filter across pages. A full last page may be followed by an empty page.

        Parameters
        ----------
        team_key : str
            Key of the team.

        after : typing.Optional[int]
            Include contacts last saved at or after this epoch-seconds timestamp.

        cursor : typing.Optional[str]
            Cursor returned by the previous response. Omit or leave blank to start from the beginning.

        limit : typing.Optional[int]
            Maximum number of results to return. Defaults to 100. Values above 1000 are capped.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ContactPage
            OK

        Examples
        --------
        from streak_crm import Streak

        client = Streak(
            token="YOUR_TOKEN",
        )
        client.contact.list_contacts(
            team_key="teamKey",
            after=1646870400,
        )
        """
        _response = self._raw_client.list_contacts(
            team_key, after=after, cursor=cursor, limit=limit, request_options=request_options
        )
        return _response.data

    def create_contact(
        self,
        team_key: str,
        *,
        get_if_existing: typing.Optional[bool] = None,
        given_name: typing.Optional[str] = OMIT,
        family_name: typing.Optional[str] = OMIT,
        title: typing.Optional[str] = OMIT,
        other: typing.Optional[str] = OMIT,
        email_addresses: typing.Optional[typing.Sequence[str]] = OMIT,
        phone_numbers: typing.Optional[typing.Sequence[str]] = OMIT,
        addresses: typing.Optional[typing.Sequence[str]] = OMIT,
        domains: typing.Optional[typing.Sequence[str]] = OMIT,
        twitter_handle: typing.Optional[str] = OMIT,
        facebook_handle: typing.Optional[str] = OMIT,
        linkedin_handle: typing.Optional[str] = OMIT,
        instagram_handle: typing.Optional[str] = OMIT,
        photo_url: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> Contact:
        """
        Creates a contact from its basic details. Links and custom fields require a subsequent update.

        Parameters
        ----------
        team_key : str
            Key of the team.

        get_if_existing : typing.Optional[bool]
            Return an existing email match instead of creating a contact. When getIfExisting=true, an email match is returned without merging new values.

        given_name : typing.Optional[str]
            Given name.

        family_name : typing.Optional[str]
            Family name.

        title : typing.Optional[str]
            Job title.

        other : typing.Optional[str]
            Additional notes about the contact.

        email_addresses : typing.Optional[typing.Sequence[str]]
            Email addresses for the contact.

        phone_numbers : typing.Optional[typing.Sequence[str]]
            Phone numbers for the contact.

        addresses : typing.Optional[typing.Sequence[str]]
            Postal addresses for the contact.

        domains : typing.Optional[typing.Sequence[str]]
            Website domains associated with the contact.

        twitter_handle : typing.Optional[str]
            Twitter handle.

        facebook_handle : typing.Optional[str]
            Facebook handle.

        linkedin_handle : typing.Optional[str]
            LinkedIn handle.

        instagram_handle : typing.Optional[str]
            Instagram handle.

        photo_url : typing.Optional[str]
            URL for the contact's photo.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        Contact
            OK

        Examples
        --------
        from streak_crm import Streak

        client = Streak(
            token="YOUR_TOKEN",
        )
        client.contact.create_contact(
            team_key="teamKey",
        )
        """
        _response = self._raw_client.create_contact(
            team_key,
            get_if_existing=get_if_existing,
            given_name=given_name,
            family_name=family_name,
            title=title,
            other=other,
            email_addresses=email_addresses,
            phone_numbers=phone_numbers,
            addresses=addresses,
            domains=domains,
            twitter_handle=twitter_handle,
            facebook_handle=facebook_handle,
            linkedin_handle=linkedin_handle,
            instagram_handle=instagram_handle,
            photo_url=photo_url,
            request_options=request_options,
        )
        return _response.data


class AsyncContactClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawContactClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawContactClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawContactClient
        """
        return self._raw_client

    async def get_contacts_in_bulk(
        self, *, request: typing.Sequence[str], request_options: typing.Optional[RequestOptions] = None
    ) -> ContactKeyBatch:
        """
        Returns accessible contacts indexed by their requested keys. Missing and inaccessible contacts are omitted.

        Parameters
        ----------
        request : typing.Sequence[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ContactKeyBatch
            Contacts indexed by their requested keys.

        Examples
        --------
        import asyncio

        from streak_crm import AsyncStreak

        client = AsyncStreak(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.contact.get_contacts_in_bulk(
                request=["string"],
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get_contacts_in_bulk(request=request, request_options=request_options)
        return _response.data

    async def get_contact(
        self, contact_key: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> Contact:
        """
        Returns an accessible contact by key.

        Parameters
        ----------
        contact_key : str
            Key of the contact.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        Contact
            OK

        Examples
        --------
        import asyncio

        from streak_crm import AsyncStreak

        client = AsyncStreak(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.contact.get_contact(
                contact_key="contactKey",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get_contact(contact_key, request_options=request_options)
        return _response.data

    async def update_contact(
        self,
        contact_key: str,
        *,
        given_name: typing.Optional[str] = OMIT,
        family_name: typing.Optional[str] = OMIT,
        title: typing.Optional[str] = OMIT,
        other: typing.Optional[str] = OMIT,
        email_addresses: typing.Optional[typing.Sequence[str]] = OMIT,
        phone_numbers: typing.Optional[typing.Sequence[str]] = OMIT,
        addresses: typing.Optional[typing.Sequence[str]] = OMIT,
        domains: typing.Optional[typing.Sequence[str]] = OMIT,
        twitter_handle: typing.Optional[str] = OMIT,
        facebook_handle: typing.Optional[str] = OMIT,
        linkedin_handle: typing.Optional[str] = OMIT,
        instagram_handle: typing.Optional[str] = OMIT,
        photo_url: typing.Optional[str] = OMIT,
        fields: typing.Optional[typing.Dict[str, typing.Optional[str]]] = OMIT,
        contact_links: typing.Optional[typing.Sequence[ContactLinkInput]] = OMIT,
        org_links: typing.Optional[typing.Sequence[OrganizationLinkInput]] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> Contact:
        """
        Applies supplied changes. Null or omitted fields remain unchanged.

        Parameters
        ----------
        contact_key : str
            Key of the contact.

        given_name : typing.Optional[str]
            New given name; an empty string clears it if another identifier remains.

        family_name : typing.Optional[str]
            New family name; an empty string clears it if another identifier remains.

        title : typing.Optional[str]
            New job title; an empty string clears it.

        other : typing.Optional[str]
            New notes; an empty string clears them.

        email_addresses : typing.Optional[typing.Sequence[str]]
            Replacement email addresses; a contact must retain an email address or a name.

        phone_numbers : typing.Optional[typing.Sequence[str]]
            Replacement phone numbers. Empty entries are removed.

        addresses : typing.Optional[typing.Sequence[str]]
            Replacement postal addresses. Empty entries are removed.

        domains : typing.Optional[typing.Sequence[str]]
            Replacement website domains.

        twitter_handle : typing.Optional[str]
            Replacement Twitter handle.

        facebook_handle : typing.Optional[str]
            Replacement Facebook handle.

        linkedin_handle : typing.Optional[str]
            Replacement LinkedIn handle.

        instagram_handle : typing.Optional[str]
            Replacement Instagram handle.

        photo_url : typing.Optional[str]
            Replacement photo URL.

        fields : typing.Optional[typing.Dict[str, typing.Optional[str]]]
            Custom-field values to merge by field key. Null entries are ignored; an empty map leaves existing fields unchanged.

        contact_links : typing.Optional[typing.Sequence[ContactLinkInput]]
            Replacement links to contacts; an empty list removes the links.

        org_links : typing.Optional[typing.Sequence[OrganizationLinkInput]]
            Replacement links to organizations; an empty list removes the links.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        Contact
            OK

        Examples
        --------
        import asyncio

        from streak_crm import AsyncStreak

        client = AsyncStreak(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.contact.update_contact(
                contact_key="contactKey",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.update_contact(
            contact_key,
            given_name=given_name,
            family_name=family_name,
            title=title,
            other=other,
            email_addresses=email_addresses,
            phone_numbers=phone_numbers,
            addresses=addresses,
            domains=domains,
            twitter_handle=twitter_handle,
            facebook_handle=facebook_handle,
            linkedin_handle=linkedin_handle,
            instagram_handle=instagram_handle,
            photo_url=photo_url,
            fields=fields,
            contact_links=contact_links,
            org_links=org_links,
            request_options=request_options,
        )
        return _response.data

    async def delete_contact(
        self, contact_key: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> OperationResponse:
        """
        Deletes a contact and schedules cleanup of its links. A missing contact returns 404.

        Parameters
        ----------
        contact_key : str
            Key of the contact.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        OperationResponse
            OK

        Examples
        --------
        import asyncio

        from streak_crm import AsyncStreak

        client = AsyncStreak(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.contact.delete_contact(
                contact_key="contactKey",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.delete_contact(contact_key, request_options=request_options)
        return _response.data

    async def list_contacts(
        self,
        team_key: str,
        *,
        after: typing.Optional[int] = None,
        cursor: typing.Optional[str] = None,
        limit: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ContactPage:
        """
        Lists contacts in stable order. Pass the returned cursor to continue; keep the same after filter across pages. A full last page may be followed by an empty page.

        Parameters
        ----------
        team_key : str
            Key of the team.

        after : typing.Optional[int]
            Include contacts last saved at or after this epoch-seconds timestamp.

        cursor : typing.Optional[str]
            Cursor returned by the previous response. Omit or leave blank to start from the beginning.

        limit : typing.Optional[int]
            Maximum number of results to return. Defaults to 100. Values above 1000 are capped.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ContactPage
            OK

        Examples
        --------
        import asyncio

        from streak_crm import AsyncStreak

        client = AsyncStreak(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.contact.list_contacts(
                team_key="teamKey",
                after=1646870400,
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.list_contacts(
            team_key, after=after, cursor=cursor, limit=limit, request_options=request_options
        )
        return _response.data

    async def create_contact(
        self,
        team_key: str,
        *,
        get_if_existing: typing.Optional[bool] = None,
        given_name: typing.Optional[str] = OMIT,
        family_name: typing.Optional[str] = OMIT,
        title: typing.Optional[str] = OMIT,
        other: typing.Optional[str] = OMIT,
        email_addresses: typing.Optional[typing.Sequence[str]] = OMIT,
        phone_numbers: typing.Optional[typing.Sequence[str]] = OMIT,
        addresses: typing.Optional[typing.Sequence[str]] = OMIT,
        domains: typing.Optional[typing.Sequence[str]] = OMIT,
        twitter_handle: typing.Optional[str] = OMIT,
        facebook_handle: typing.Optional[str] = OMIT,
        linkedin_handle: typing.Optional[str] = OMIT,
        instagram_handle: typing.Optional[str] = OMIT,
        photo_url: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> Contact:
        """
        Creates a contact from its basic details. Links and custom fields require a subsequent update.

        Parameters
        ----------
        team_key : str
            Key of the team.

        get_if_existing : typing.Optional[bool]
            Return an existing email match instead of creating a contact. When getIfExisting=true, an email match is returned without merging new values.

        given_name : typing.Optional[str]
            Given name.

        family_name : typing.Optional[str]
            Family name.

        title : typing.Optional[str]
            Job title.

        other : typing.Optional[str]
            Additional notes about the contact.

        email_addresses : typing.Optional[typing.Sequence[str]]
            Email addresses for the contact.

        phone_numbers : typing.Optional[typing.Sequence[str]]
            Phone numbers for the contact.

        addresses : typing.Optional[typing.Sequence[str]]
            Postal addresses for the contact.

        domains : typing.Optional[typing.Sequence[str]]
            Website domains associated with the contact.

        twitter_handle : typing.Optional[str]
            Twitter handle.

        facebook_handle : typing.Optional[str]
            Facebook handle.

        linkedin_handle : typing.Optional[str]
            LinkedIn handle.

        instagram_handle : typing.Optional[str]
            Instagram handle.

        photo_url : typing.Optional[str]
            URL for the contact's photo.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        Contact
            OK

        Examples
        --------
        import asyncio

        from streak_crm import AsyncStreak

        client = AsyncStreak(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.contact.create_contact(
                team_key="teamKey",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.create_contact(
            team_key,
            get_if_existing=get_if_existing,
            given_name=given_name,
            family_name=family_name,
            title=title,
            other=other,
            email_addresses=email_addresses,
            phone_numbers=phone_numbers,
            addresses=addresses,
            domains=domains,
            twitter_handle=twitter_handle,
            facebook_handle=facebook_handle,
            linkedin_handle=linkedin_handle,
            instagram_handle=instagram_handle,
            photo_url=photo_url,
            request_options=request_options,
        )
        return _response.data
