# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from ..types.meeting import Meeting
from ..types.meeting_list_response import MeetingListResponse
from ..types.meeting_type import MeetingType
from ..types.operation_response import OperationResponse
from .raw_client import AsyncRawMeetingsClient, RawMeetingsClient

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class MeetingsClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawMeetingsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawMeetingsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawMeetingsClient
        """
        return self._raw_client

    def list_meetings(
        self,
        box_key: str,
        *,
        limit: typing.Optional[int] = None,
        page: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> MeetingListResponse:
        """
        Lists meetings and call logs on a box

        Parameters
        ----------
        box_key : str

        limit : typing.Optional[int]
            Number of items to return.

        page : typing.Optional[int]
            Zero-based page number

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        MeetingListResponse
            OK

        Examples
        --------
        from streak_crm import Streak

        client = Streak(
            token="YOUR_TOKEN",
        )
        client.meetings.list_meetings(
            box_key="boxKey",
        )
        """
        _response = self._raw_client.list_meetings(box_key, limit=limit, page=page, request_options=request_options)
        return _response.data

    def create_meeting(
        self,
        box_key: str,
        *,
        meeting_type: MeetingType,
        start_timestamp: int,
        duration: typing.Optional[int] = OMIT,
        notes: typing.Optional[str] = OMIT,
        task_keys: typing.Optional[typing.Sequence[str]] = OMIT,
        is_draft: typing.Optional[bool] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> Meeting:
        """
        Creates a meeting or call log on a box

        Parameters
        ----------
        box_key : str

        meeting_type : MeetingType
            Meeting type.

        start_timestamp : int
            Meeting start timestamp, in epoch milliseconds.

        duration : typing.Optional[int]
            Meeting duration in milliseconds.

        notes : typing.Optional[str]
            Meeting notes.

        task_keys : typing.Optional[typing.Sequence[str]]
            Task keys associated with this meeting.

        is_draft : typing.Optional[bool]
            Whether this meeting is a draft.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        Meeting
            OK

        Examples
        --------
        from streak_crm import Streak

        client = Streak(
            token="YOUR_TOKEN",
        )
        client.meetings.create_meeting(
            box_key="boxKey",
            meeting_type="CALL_LOG",
            start_timestamp=1646870400000,
        )
        """
        _response = self._raw_client.create_meeting(
            box_key,
            meeting_type=meeting_type,
            start_timestamp=start_timestamp,
            duration=duration,
            notes=notes,
            task_keys=task_keys,
            is_draft=is_draft,
            request_options=request_options,
        )
        return _response.data

    def get_meeting(self, meeting_key: str, *, request_options: typing.Optional[RequestOptions] = None) -> Meeting:
        """
        Returns a meeting or call log by key

        Parameters
        ----------
        meeting_key : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        Meeting
            OK

        Examples
        --------
        from streak_crm import Streak

        client = Streak(
            token="YOUR_TOKEN",
        )
        client.meetings.get_meeting(
            meeting_key="meetingKey",
        )
        """
        _response = self._raw_client.get_meeting(meeting_key, request_options=request_options)
        return _response.data

    def update_meeting(
        self,
        meeting_key: str,
        *,
        meeting_type: typing.Optional[str] = OMIT,
        start_timestamp: typing.Optional[int] = OMIT,
        duration: typing.Optional[int] = OMIT,
        notes: typing.Optional[str] = OMIT,
        is_draft: typing.Optional[bool] = OMIT,
        task_keys: typing.Optional[typing.Sequence[str]] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> Meeting:
        """
        Updates a meeting or call log by key

        Parameters
        ----------
        meeting_key : str

        meeting_type : typing.Optional[str]
            New meeting type. Omit this field to keep the existing meeting type unchanged.

        start_timestamp : typing.Optional[int]
            New meeting start timestamp, in epoch milliseconds. Omit this field to keep the existing start time unchanged.

        duration : typing.Optional[int]
            New meeting duration in milliseconds. Omit this field to keep the existing duration unchanged.

        notes : typing.Optional[str]
            New meeting notes. Omit this field to keep the existing notes unchanged.

        is_draft : typing.Optional[bool]
            Whether to publish a draft meeting. Omit this field to keep the existing draft state unchanged.

        task_keys : typing.Optional[typing.Sequence[str]]
            Replacement task keys associated with this meeting. Omit this field to keep existing task keys unchanged.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        Meeting
            OK

        Examples
        --------
        from streak_crm import Streak

        client = Streak(
            token="YOUR_TOKEN",
        )
        client.meetings.update_meeting(
            meeting_key="meetingKey",
        )
        """
        _response = self._raw_client.update_meeting(
            meeting_key,
            meeting_type=meeting_type,
            start_timestamp=start_timestamp,
            duration=duration,
            notes=notes,
            is_draft=is_draft,
            task_keys=task_keys,
            request_options=request_options,
        )
        return _response.data

    def delete_meeting(
        self, meeting_key: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> OperationResponse:
        """
        Deletes a meeting or call log by key

        Parameters
        ----------
        meeting_key : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        OperationResponse
            OK

        Examples
        --------
        from streak_crm import Streak

        client = Streak(
            token="YOUR_TOKEN",
        )
        client.meetings.delete_meeting(
            meeting_key="meetingKey",
        )
        """
        _response = self._raw_client.delete_meeting(meeting_key, request_options=request_options)
        return _response.data


class AsyncMeetingsClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawMeetingsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawMeetingsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawMeetingsClient
        """
        return self._raw_client

    async def list_meetings(
        self,
        box_key: str,
        *,
        limit: typing.Optional[int] = None,
        page: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> MeetingListResponse:
        """
        Lists meetings and call logs on a box

        Parameters
        ----------
        box_key : str

        limit : typing.Optional[int]
            Number of items to return.

        page : typing.Optional[int]
            Zero-based page number

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        MeetingListResponse
            OK

        Examples
        --------
        import asyncio

        from streak_crm import AsyncStreak

        client = AsyncStreak(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.meetings.list_meetings(
                box_key="boxKey",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.list_meetings(
            box_key, limit=limit, page=page, request_options=request_options
        )
        return _response.data

    async def create_meeting(
        self,
        box_key: str,
        *,
        meeting_type: MeetingType,
        start_timestamp: int,
        duration: typing.Optional[int] = OMIT,
        notes: typing.Optional[str] = OMIT,
        task_keys: typing.Optional[typing.Sequence[str]] = OMIT,
        is_draft: typing.Optional[bool] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> Meeting:
        """
        Creates a meeting or call log on a box

        Parameters
        ----------
        box_key : str

        meeting_type : MeetingType
            Meeting type.

        start_timestamp : int
            Meeting start timestamp, in epoch milliseconds.

        duration : typing.Optional[int]
            Meeting duration in milliseconds.

        notes : typing.Optional[str]
            Meeting notes.

        task_keys : typing.Optional[typing.Sequence[str]]
            Task keys associated with this meeting.

        is_draft : typing.Optional[bool]
            Whether this meeting is a draft.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        Meeting
            OK

        Examples
        --------
        import asyncio

        from streak_crm import AsyncStreak

        client = AsyncStreak(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.meetings.create_meeting(
                box_key="boxKey",
                meeting_type="CALL_LOG",
                start_timestamp=1646870400000,
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.create_meeting(
            box_key,
            meeting_type=meeting_type,
            start_timestamp=start_timestamp,
            duration=duration,
            notes=notes,
            task_keys=task_keys,
            is_draft=is_draft,
            request_options=request_options,
        )
        return _response.data

    async def get_meeting(
        self, meeting_key: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> Meeting:
        """
        Returns a meeting or call log by key

        Parameters
        ----------
        meeting_key : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        Meeting
            OK

        Examples
        --------
        import asyncio

        from streak_crm import AsyncStreak

        client = AsyncStreak(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.meetings.get_meeting(
                meeting_key="meetingKey",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get_meeting(meeting_key, request_options=request_options)
        return _response.data

    async def update_meeting(
        self,
        meeting_key: str,
        *,
        meeting_type: typing.Optional[str] = OMIT,
        start_timestamp: typing.Optional[int] = OMIT,
        duration: typing.Optional[int] = OMIT,
        notes: typing.Optional[str] = OMIT,
        is_draft: typing.Optional[bool] = OMIT,
        task_keys: typing.Optional[typing.Sequence[str]] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> Meeting:
        """
        Updates a meeting or call log by key

        Parameters
        ----------
        meeting_key : str

        meeting_type : typing.Optional[str]
            New meeting type. Omit this field to keep the existing meeting type unchanged.

        start_timestamp : typing.Optional[int]
            New meeting start timestamp, in epoch milliseconds. Omit this field to keep the existing start time unchanged.

        duration : typing.Optional[int]
            New meeting duration in milliseconds. Omit this field to keep the existing duration unchanged.

        notes : typing.Optional[str]
            New meeting notes. Omit this field to keep the existing notes unchanged.

        is_draft : typing.Optional[bool]
            Whether to publish a draft meeting. Omit this field to keep the existing draft state unchanged.

        task_keys : typing.Optional[typing.Sequence[str]]
            Replacement task keys associated with this meeting. Omit this field to keep existing task keys unchanged.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        Meeting
            OK

        Examples
        --------
        import asyncio

        from streak_crm import AsyncStreak

        client = AsyncStreak(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.meetings.update_meeting(
                meeting_key="meetingKey",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.update_meeting(
            meeting_key,
            meeting_type=meeting_type,
            start_timestamp=start_timestamp,
            duration=duration,
            notes=notes,
            is_draft=is_draft,
            task_keys=task_keys,
            request_options=request_options,
        )
        return _response.data

    async def delete_meeting(
        self, meeting_key: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> OperationResponse:
        """
        Deletes a meeting or call log by key

        Parameters
        ----------
        meeting_key : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        OperationResponse
            OK

        Examples
        --------
        import asyncio

        from streak_crm import AsyncStreak

        client = AsyncStreak(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.meetings.delete_meeting(
                meeting_key="meetingKey",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.delete_meeting(meeting_key, request_options=request_options)
        return _response.data
