# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from ..types.field_type import FieldType
from ..types.operation_response import OperationResponse
from ..types.pipeline import Pipeline
from ..types.pipeline_field import PipelineField
from ..types.pipeline_field_ai_settings_update import PipelineFieldAiSettingsUpdate
from ..types.pipeline_field_create import PipelineFieldCreate
from ..types.pipeline_field_dropdown_settings_update import PipelineFieldDropdownSettingsUpdate
from ..types.pipeline_field_tag_settings_update import PipelineFieldTagSettingsUpdate
from ..types.pipeline_list_response import PipelineListResponse
from ..types.pipeline_permission_set_input import PipelinePermissionSetInput
from ..types.pipeline_sharing_entry_input import PipelineSharingEntryInput
from .raw_client import AsyncRawPipelineClient, RawPipelineClient

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class PipelineClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawPipelineClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawPipelineClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawPipelineClient
        """
        return self._raw_client

    def list_pipeline_fields(
        self, pipeline_key: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> typing.List[PipelineField]:
        """
        Returns the fields in a pipeline in their stored order.

        Parameters
        ----------
        pipeline_key : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.List[PipelineField]
            OK

        Examples
        --------
        from streak_crm import Streak

        client = Streak(
            token="YOUR_TOKEN",
        )
        client.pipeline.list_pipeline_fields(
            pipeline_key="pipelineKey",
        )
        """
        _response = self._raw_client.list_pipeline_fields(pipeline_key, request_options=request_options)
        return _response.data

    def get_pipeline_field(
        self, pipeline_key: str, field_key: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> PipelineField:
        """
        Returns a field by its key within a pipeline.

        Parameters
        ----------
        pipeline_key : str

        field_key : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        PipelineField
            OK

        Examples
        --------
        from streak_crm import Streak

        client = Streak(
            token="YOUR_TOKEN",
        )
        client.pipeline.get_pipeline_field(
            pipeline_key="pipelineKey",
            field_key="fieldKey",
        )
        """
        _response = self._raw_client.get_pipeline_field(pipeline_key, field_key, request_options=request_options)
        return _response.data

    def update_pipeline_field(
        self,
        pipeline_key: str,
        field_key: str,
        *,
        add_only: typing.Optional[bool] = None,
        name: typing.Optional[str] = OMIT,
        default_value: typing.Optional[str] = OMIT,
        dropdown_settings: typing.Optional[PipelineFieldDropdownSettingsUpdate] = OMIT,
        tag_settings: typing.Optional[PipelineFieldTagSettingsUpdate] = OMIT,
        ai_settings: typing.Optional[PipelineFieldAiSettingsUpdate] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> PipelineField:
        """
        Updates a field's name, default value, options, or AI settings.

        Parameters
        ----------
        pipeline_key : str

        field_key : str

        add_only : typing.Optional[bool]
            Append dropdown or tag options while retaining existing options. Defaults to false.

        name : typing.Optional[str]
            New field name.

        default_value : typing.Optional[str]
            New default value or formula.

        dropdown_settings : typing.Optional[PipelineFieldDropdownSettingsUpdate]
            Dropdown options to apply.

        tag_settings : typing.Optional[PipelineFieldTagSettingsUpdate]
            Tag options to apply.

        ai_settings : typing.Optional[PipelineFieldAiSettingsUpdate]
            AI settings to update.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        PipelineField
            OK

        Examples
        --------
        from streak_crm import Streak

        client = Streak(
            token="YOUR_TOKEN",
        )
        client.pipeline.update_pipeline_field(
            pipeline_key="pipelineKey",
            field_key="fieldKey",
        )
        """
        _response = self._raw_client.update_pipeline_field(
            pipeline_key,
            field_key,
            add_only=add_only,
            name=name,
            default_value=default_value,
            dropdown_settings=dropdown_settings,
            tag_settings=tag_settings,
            ai_settings=ai_settings,
            request_options=request_options,
        )
        return _response.data

    def delete_pipeline_field(
        self, pipeline_key: str, field_key: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> OperationResponse:
        """
        Deletes a custom field and clears the value from all the pipeline's boxes.

        Parameters
        ----------
        pipeline_key : str

        field_key : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        OperationResponse
            OK

        Examples
        --------
        from streak_crm import Streak

        client = Streak(
            token="YOUR_TOKEN",
        )
        client.pipeline.delete_pipeline_field(
            pipeline_key="pipelineKey",
            field_key="fieldKey",
        )
        """
        _response = self._raw_client.delete_pipeline_field(pipeline_key, field_key, request_options=request_options)
        return _response.data

    def list_pipelines(
        self,
        *,
        sort_by: typing.Optional[str] = None,
        limit: typing.Optional[int] = None,
        page: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> PipelineListResponse:
        """
        Lists pipelines accessible to the current user.

        Parameters
        ----------
        sort_by : typing.Optional[str]

        limit : typing.Optional[int]
            Number of items to return.

        page : typing.Optional[int]
            Zero-based page number

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        PipelineListResponse
            OK

        Examples
        --------
        from streak_crm import Streak

        client = Streak(
            token="YOUR_TOKEN",
        )
        client.pipeline.list_pipelines()
        """
        _response = self._raw_client.list_pipelines(
            sort_by=sort_by, limit=limit, page=page, request_options=request_options
        )
        return _response.data

    def create_pipeline(
        self,
        *,
        name: str,
        team_key: str,
        stages: typing.Sequence[str],
        icon: typing.Optional[str] = OMIT,
        description: typing.Optional[str] = OMIT,
        template_type: typing.Optional[str] = OMIT,
        fields: typing.Optional[typing.Sequence[PipelineFieldCreate]] = OMIT,
        default_permission_set_name: typing.Optional[str] = OMIT,
        sharing_restricted_to_team: typing.Optional[bool] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> None:
        """
        Creates a basic pipeline.

        Parameters
        ----------
        name : str
            Pipeline name.

        team_key : str
            Key for the team that will own the pipeline.

        stages : typing.Sequence[str]
            Stage names in display order.

        icon : typing.Optional[str]
            Pipeline icon name.

        description : typing.Optional[str]
            Pipeline description.

        template_type : typing.Optional[str]
            Template identifier associated with the pipeline.

        fields : typing.Optional[typing.Sequence[PipelineFieldCreate]]
            Fields to create in the pipeline.

        default_permission_set_name : typing.Optional[str]
            Default permission set for users without an explicit assignment.

        sharing_restricted_to_team : typing.Optional[bool]
            Whether sharing is restricted to members of the owning team.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        from streak_crm import Streak

        client = Streak(
            token="YOUR_TOKEN",
        )
        client.pipeline.create_pipeline(
            name="name",
            team_key="teamKey",
            stages=["stages"],
        )
        """
        _response = self._raw_client.create_pipeline(
            name=name,
            team_key=team_key,
            stages=stages,
            icon=icon,
            description=description,
            template_type=template_type,
            fields=fields,
            default_permission_set_name=default_permission_set_name,
            sharing_restricted_to_team=sharing_restricted_to_team,
            request_options=request_options,
        )
        return _response.data

    def get_pipeline(self, pipeline_key: str, *, request_options: typing.Optional[RequestOptions] = None) -> Pipeline:
        """
        Returns a pipeline by key.

        Parameters
        ----------
        pipeline_key : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        Pipeline
            OK

        Examples
        --------
        from streak_crm import Streak

        client = Streak(
            token="YOUR_TOKEN",
        )
        client.pipeline.get_pipeline(
            pipeline_key="pipelineKey",
        )
        """
        _response = self._raw_client.get_pipeline(pipeline_key, request_options=request_options)
        return _response.data

    def update_pipeline(
        self,
        pipeline_key: str,
        *,
        team_key: typing.Optional[str] = OMIT,
        icon: typing.Optional[str] = OMIT,
        name: typing.Optional[str] = OMIT,
        description: typing.Optional[str] = OMIT,
        sharing_restricted_to_team: typing.Optional[bool] = OMIT,
        stage_order: typing.Optional[typing.Sequence[str]] = OMIT,
        stage_color_theme: typing.Optional[str] = OMIT,
        custom_permission_sets: typing.Optional[typing.Dict[str, typing.Optional[PipelinePermissionSetInput]]] = OMIT,
        default_permission_set_name: typing.Optional[str] = OMIT,
        acl_entries: typing.Optional[typing.Sequence[PipelineSharingEntryInput]] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> Pipeline:
        """
        Updates the supplied Pipeline fields. Omitted fields remain unchanged.

        Parameters
        ----------
        pipeline_key : str

        team_key : typing.Optional[str]
            New team key. Omit to keep the current team.

        icon : typing.Optional[str]
            New icon. Omit to keep the current icon.

        name : typing.Optional[str]
            New name. Omit to keep the current name.

        description : typing.Optional[str]
            New description. Omit to keep the current description.

        sharing_restricted_to_team : typing.Optional[bool]
            New team sharing restriction. Omit to keep the current value.

        stage_order : typing.Optional[typing.Sequence[str]]
            Complete stage order. Omit to keep the current order; an empty list is invalid.

        stage_color_theme : typing.Optional[str]
            New stage color theme. Omit to keep the current theme.

        custom_permission_sets : typing.Optional[typing.Dict[str, typing.Optional[PipelinePermissionSetInput]]]
            Replacement custom permission sets. Omit to keep existing sets.

        default_permission_set_name : typing.Optional[str]
            New default permission set. Omit to keep the current value.

        acl_entries : typing.Optional[typing.Sequence[PipelineSharingEntryInput]]
            Replacement sharing entries. Omit to keep existing sharing; an empty list is invalid.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        Pipeline
            OK

        Examples
        --------
        from streak_crm import Streak

        client = Streak(
            token="YOUR_TOKEN",
        )
        client.pipeline.update_pipeline(
            pipeline_key="pipelineKey",
        )
        """
        _response = self._raw_client.update_pipeline(
            pipeline_key,
            team_key=team_key,
            icon=icon,
            name=name,
            description=description,
            sharing_restricted_to_team=sharing_restricted_to_team,
            stage_order=stage_order,
            stage_color_theme=stage_color_theme,
            custom_permission_sets=custom_permission_sets,
            default_permission_set_name=default_permission_set_name,
            acl_entries=acl_entries,
            request_options=request_options,
        )
        return _response.data

    def delete_pipeline(
        self, pipeline_key: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> OperationResponse:
        """
        Deletes an empty pipeline.

        Parameters
        ----------
        pipeline_key : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        OperationResponse
            OK

        Examples
        --------
        from streak_crm import Streak

        client = Streak(
            token="YOUR_TOKEN",
        )
        client.pipeline.delete_pipeline(
            pipeline_key="pipelineKey",
        )
        """
        _response = self._raw_client.delete_pipeline(pipeline_key, request_options=request_options)
        return _response.data

    def create_pipeline_field(
        self,
        pipeline_key: str,
        *,
        name: str,
        type: FieldType,
        default_value: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> PipelineField:
        """
        Creates a custom field in a pipeline.

        Parameters
        ----------
        pipeline_key : str

        name : str
            Field name.

        type : FieldType
            Field data type.

        default_value : typing.Optional[str]
            Initial default value. Currently only used for formula fields.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        PipelineField
            OK

        Examples
        --------
        from streak_crm import Streak

        client = Streak(
            token="YOUR_TOKEN",
        )
        client.pipeline.create_pipeline_field(
            pipeline_key="pipelineKey",
            name="name",
            type="TEXT_INPUT",
        )
        """
        _response = self._raw_client.create_pipeline_field(
            pipeline_key, name=name, type=type, default_value=default_value, request_options=request_options
        )
        return _response.data


class AsyncPipelineClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawPipelineClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawPipelineClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawPipelineClient
        """
        return self._raw_client

    async def list_pipeline_fields(
        self, pipeline_key: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> typing.List[PipelineField]:
        """
        Returns the fields in a pipeline in their stored order.

        Parameters
        ----------
        pipeline_key : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.List[PipelineField]
            OK

        Examples
        --------
        import asyncio

        from streak_crm import AsyncStreak

        client = AsyncStreak(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.pipeline.list_pipeline_fields(
                pipeline_key="pipelineKey",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.list_pipeline_fields(pipeline_key, request_options=request_options)
        return _response.data

    async def get_pipeline_field(
        self, pipeline_key: str, field_key: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> PipelineField:
        """
        Returns a field by its key within a pipeline.

        Parameters
        ----------
        pipeline_key : str

        field_key : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        PipelineField
            OK

        Examples
        --------
        import asyncio

        from streak_crm import AsyncStreak

        client = AsyncStreak(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.pipeline.get_pipeline_field(
                pipeline_key="pipelineKey",
                field_key="fieldKey",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get_pipeline_field(pipeline_key, field_key, request_options=request_options)
        return _response.data

    async def update_pipeline_field(
        self,
        pipeline_key: str,
        field_key: str,
        *,
        add_only: typing.Optional[bool] = None,
        name: typing.Optional[str] = OMIT,
        default_value: typing.Optional[str] = OMIT,
        dropdown_settings: typing.Optional[PipelineFieldDropdownSettingsUpdate] = OMIT,
        tag_settings: typing.Optional[PipelineFieldTagSettingsUpdate] = OMIT,
        ai_settings: typing.Optional[PipelineFieldAiSettingsUpdate] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> PipelineField:
        """
        Updates a field's name, default value, options, or AI settings.

        Parameters
        ----------
        pipeline_key : str

        field_key : str

        add_only : typing.Optional[bool]
            Append dropdown or tag options while retaining existing options. Defaults to false.

        name : typing.Optional[str]
            New field name.

        default_value : typing.Optional[str]
            New default value or formula.

        dropdown_settings : typing.Optional[PipelineFieldDropdownSettingsUpdate]
            Dropdown options to apply.

        tag_settings : typing.Optional[PipelineFieldTagSettingsUpdate]
            Tag options to apply.

        ai_settings : typing.Optional[PipelineFieldAiSettingsUpdate]
            AI settings to update.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        PipelineField
            OK

        Examples
        --------
        import asyncio

        from streak_crm import AsyncStreak

        client = AsyncStreak(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.pipeline.update_pipeline_field(
                pipeline_key="pipelineKey",
                field_key="fieldKey",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.update_pipeline_field(
            pipeline_key,
            field_key,
            add_only=add_only,
            name=name,
            default_value=default_value,
            dropdown_settings=dropdown_settings,
            tag_settings=tag_settings,
            ai_settings=ai_settings,
            request_options=request_options,
        )
        return _response.data

    async def delete_pipeline_field(
        self, pipeline_key: str, field_key: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> OperationResponse:
        """
        Deletes a custom field and clears the value from all the pipeline's boxes.

        Parameters
        ----------
        pipeline_key : str

        field_key : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        OperationResponse
            OK

        Examples
        --------
        import asyncio

        from streak_crm import AsyncStreak

        client = AsyncStreak(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.pipeline.delete_pipeline_field(
                pipeline_key="pipelineKey",
                field_key="fieldKey",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.delete_pipeline_field(
            pipeline_key, field_key, request_options=request_options
        )
        return _response.data

    async def list_pipelines(
        self,
        *,
        sort_by: typing.Optional[str] = None,
        limit: typing.Optional[int] = None,
        page: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> PipelineListResponse:
        """
        Lists pipelines accessible to the current user.

        Parameters
        ----------
        sort_by : typing.Optional[str]

        limit : typing.Optional[int]
            Number of items to return.

        page : typing.Optional[int]
            Zero-based page number

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        PipelineListResponse
            OK

        Examples
        --------
        import asyncio

        from streak_crm import AsyncStreak

        client = AsyncStreak(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.pipeline.list_pipelines()


        asyncio.run(main())
        """
        _response = await self._raw_client.list_pipelines(
            sort_by=sort_by, limit=limit, page=page, request_options=request_options
        )
        return _response.data

    async def create_pipeline(
        self,
        *,
        name: str,
        team_key: str,
        stages: typing.Sequence[str],
        icon: typing.Optional[str] = OMIT,
        description: typing.Optional[str] = OMIT,
        template_type: typing.Optional[str] = OMIT,
        fields: typing.Optional[typing.Sequence[PipelineFieldCreate]] = OMIT,
        default_permission_set_name: typing.Optional[str] = OMIT,
        sharing_restricted_to_team: typing.Optional[bool] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> None:
        """
        Creates a basic pipeline.

        Parameters
        ----------
        name : str
            Pipeline name.

        team_key : str
            Key for the team that will own the pipeline.

        stages : typing.Sequence[str]
            Stage names in display order.

        icon : typing.Optional[str]
            Pipeline icon name.

        description : typing.Optional[str]
            Pipeline description.

        template_type : typing.Optional[str]
            Template identifier associated with the pipeline.

        fields : typing.Optional[typing.Sequence[PipelineFieldCreate]]
            Fields to create in the pipeline.

        default_permission_set_name : typing.Optional[str]
            Default permission set for users without an explicit assignment.

        sharing_restricted_to_team : typing.Optional[bool]
            Whether sharing is restricted to members of the owning team.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        import asyncio

        from streak_crm import AsyncStreak

        client = AsyncStreak(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.pipeline.create_pipeline(
                name="name",
                team_key="teamKey",
                stages=["stages"],
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.create_pipeline(
            name=name,
            team_key=team_key,
            stages=stages,
            icon=icon,
            description=description,
            template_type=template_type,
            fields=fields,
            default_permission_set_name=default_permission_set_name,
            sharing_restricted_to_team=sharing_restricted_to_team,
            request_options=request_options,
        )
        return _response.data

    async def get_pipeline(
        self, pipeline_key: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> Pipeline:
        """
        Returns a pipeline by key.

        Parameters
        ----------
        pipeline_key : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        Pipeline
            OK

        Examples
        --------
        import asyncio

        from streak_crm import AsyncStreak

        client = AsyncStreak(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.pipeline.get_pipeline(
                pipeline_key="pipelineKey",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get_pipeline(pipeline_key, request_options=request_options)
        return _response.data

    async def update_pipeline(
        self,
        pipeline_key: str,
        *,
        team_key: typing.Optional[str] = OMIT,
        icon: typing.Optional[str] = OMIT,
        name: typing.Optional[str] = OMIT,
        description: typing.Optional[str] = OMIT,
        sharing_restricted_to_team: typing.Optional[bool] = OMIT,
        stage_order: typing.Optional[typing.Sequence[str]] = OMIT,
        stage_color_theme: typing.Optional[str] = OMIT,
        custom_permission_sets: typing.Optional[typing.Dict[str, typing.Optional[PipelinePermissionSetInput]]] = OMIT,
        default_permission_set_name: typing.Optional[str] = OMIT,
        acl_entries: typing.Optional[typing.Sequence[PipelineSharingEntryInput]] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> Pipeline:
        """
        Updates the supplied Pipeline fields. Omitted fields remain unchanged.

        Parameters
        ----------
        pipeline_key : str

        team_key : typing.Optional[str]
            New team key. Omit to keep the current team.

        icon : typing.Optional[str]
            New icon. Omit to keep the current icon.

        name : typing.Optional[str]
            New name. Omit to keep the current name.

        description : typing.Optional[str]
            New description. Omit to keep the current description.

        sharing_restricted_to_team : typing.Optional[bool]
            New team sharing restriction. Omit to keep the current value.

        stage_order : typing.Optional[typing.Sequence[str]]
            Complete stage order. Omit to keep the current order; an empty list is invalid.

        stage_color_theme : typing.Optional[str]
            New stage color theme. Omit to keep the current theme.

        custom_permission_sets : typing.Optional[typing.Dict[str, typing.Optional[PipelinePermissionSetInput]]]
            Replacement custom permission sets. Omit to keep existing sets.

        default_permission_set_name : typing.Optional[str]
            New default permission set. Omit to keep the current value.

        acl_entries : typing.Optional[typing.Sequence[PipelineSharingEntryInput]]
            Replacement sharing entries. Omit to keep existing sharing; an empty list is invalid.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        Pipeline
            OK

        Examples
        --------
        import asyncio

        from streak_crm import AsyncStreak

        client = AsyncStreak(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.pipeline.update_pipeline(
                pipeline_key="pipelineKey",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.update_pipeline(
            pipeline_key,
            team_key=team_key,
            icon=icon,
            name=name,
            description=description,
            sharing_restricted_to_team=sharing_restricted_to_team,
            stage_order=stage_order,
            stage_color_theme=stage_color_theme,
            custom_permission_sets=custom_permission_sets,
            default_permission_set_name=default_permission_set_name,
            acl_entries=acl_entries,
            request_options=request_options,
        )
        return _response.data

    async def delete_pipeline(
        self, pipeline_key: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> OperationResponse:
        """
        Deletes an empty pipeline.

        Parameters
        ----------
        pipeline_key : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        OperationResponse
            OK

        Examples
        --------
        import asyncio

        from streak_crm import AsyncStreak

        client = AsyncStreak(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.pipeline.delete_pipeline(
                pipeline_key="pipelineKey",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.delete_pipeline(pipeline_key, request_options=request_options)
        return _response.data

    async def create_pipeline_field(
        self,
        pipeline_key: str,
        *,
        name: str,
        type: FieldType,
        default_value: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> PipelineField:
        """
        Creates a custom field in a pipeline.

        Parameters
        ----------
        pipeline_key : str

        name : str
            Field name.

        type : FieldType
            Field data type.

        default_value : typing.Optional[str]
            Initial default value. Currently only used for formula fields.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        PipelineField
            OK

        Examples
        --------
        import asyncio

        from streak_crm import AsyncStreak

        client = AsyncStreak(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.pipeline.create_pipeline_field(
                pipeline_key="pipelineKey",
                name="name",
                type="TEXT_INPUT",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.create_pipeline_field(
            pipeline_key, name=name, type=type, default_value=default_value, request_options=request_options
        )
        return _response.data
