# This file was auto-generated by Fern from our API Definition.

import typing
from json.decoder import JSONDecodeError

from ..core.api_error import ApiError
from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.http_response import AsyncHttpResponse, HttpResponse
from ..core.jsonable_encoder import encode_path_param
from ..core.parse_error import ParsingError
from ..core.pydantic_utilities import parse_obj_as
from ..core.request_options import RequestOptions
from ..core.serialization import convert_and_respect_annotation_metadata
from ..types.field_type import FieldType
from ..types.operation_response import OperationResponse
from ..types.pipeline import Pipeline
from ..types.pipeline_field import PipelineField
from ..types.pipeline_field_ai_settings_update import PipelineFieldAiSettingsUpdate
from ..types.pipeline_field_create import PipelineFieldCreate
from ..types.pipeline_field_dropdown_settings_update import PipelineFieldDropdownSettingsUpdate
from ..types.pipeline_field_tag_settings_update import PipelineFieldTagSettingsUpdate
from ..types.pipeline_list_response import PipelineListResponse
from ..types.pipeline_permission_set_input import PipelinePermissionSetInput
from ..types.pipeline_sharing_entry_input import PipelineSharingEntryInput
from pydantic import ValidationError

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class RawPipelineClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._client_wrapper = client_wrapper

    def list_pipeline_fields(
        self, pipeline_key: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> HttpResponse[typing.List[PipelineField]]:
        """
        Returns the fields in a pipeline in their stored order.

        Parameters
        ----------
        pipeline_key : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[typing.List[PipelineField]]
            OK
        """
        _response = self._client_wrapper.httpx_client.request(
            f"v1/pipelines/{encode_path_param(pipeline_key)}/fields",
            method="GET",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    typing.List[PipelineField],
                    parse_obj_as(
                        type_=typing.List[PipelineField],  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def get_pipeline_field(
        self, pipeline_key: str, field_key: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> HttpResponse[PipelineField]:
        """
        Returns a field by its key within a pipeline.

        Parameters
        ----------
        pipeline_key : str

        field_key : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[PipelineField]
            OK
        """
        _response = self._client_wrapper.httpx_client.request(
            f"v1/pipelines/{encode_path_param(pipeline_key)}/fields/{encode_path_param(field_key)}",
            method="GET",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    PipelineField,
                    parse_obj_as(
                        type_=PipelineField,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def update_pipeline_field(
        self,
        pipeline_key: str,
        field_key: str,
        *,
        add_only: typing.Optional[bool] = None,
        name: typing.Optional[str] = OMIT,
        default_value: typing.Optional[str] = OMIT,
        dropdown_settings: typing.Optional[PipelineFieldDropdownSettingsUpdate] = OMIT,
        tag_settings: typing.Optional[PipelineFieldTagSettingsUpdate] = OMIT,
        ai_settings: typing.Optional[PipelineFieldAiSettingsUpdate] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[PipelineField]:
        """
        Updates a field's name, default value, options, or AI settings.

        Parameters
        ----------
        pipeline_key : str

        field_key : str

        add_only : typing.Optional[bool]
            Append dropdown or tag options while retaining existing options. Defaults to false.

        name : typing.Optional[str]
            New field name.

        default_value : typing.Optional[str]
            New default value or formula.

        dropdown_settings : typing.Optional[PipelineFieldDropdownSettingsUpdate]
            Dropdown options to apply.

        tag_settings : typing.Optional[PipelineFieldTagSettingsUpdate]
            Tag options to apply.

        ai_settings : typing.Optional[PipelineFieldAiSettingsUpdate]
            AI settings to update.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[PipelineField]
            OK
        """
        _response = self._client_wrapper.httpx_client.request(
            f"v1/pipelines/{encode_path_param(pipeline_key)}/fields/{encode_path_param(field_key)}",
            method="POST",
            params={
                "addOnly": add_only,
            },
            json={
                "name": name,
                "defaultValue": default_value,
                "dropdownSettings": convert_and_respect_annotation_metadata(
                    object_=dropdown_settings,
                    annotation=typing.Optional[PipelineFieldDropdownSettingsUpdate],
                    direction="write",
                ),
                "tagSettings": convert_and_respect_annotation_metadata(
                    object_=tag_settings, annotation=typing.Optional[PipelineFieldTagSettingsUpdate], direction="write"
                ),
                "aiSettings": convert_and_respect_annotation_metadata(
                    object_=ai_settings, annotation=typing.Optional[PipelineFieldAiSettingsUpdate], direction="write"
                ),
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    PipelineField,
                    parse_obj_as(
                        type_=PipelineField,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def delete_pipeline_field(
        self, pipeline_key: str, field_key: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> HttpResponse[OperationResponse]:
        """
        Deletes a custom field and clears the value from all the pipeline's boxes.

        Parameters
        ----------
        pipeline_key : str

        field_key : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[OperationResponse]
            OK
        """
        _response = self._client_wrapper.httpx_client.request(
            f"v1/pipelines/{encode_path_param(pipeline_key)}/fields/{encode_path_param(field_key)}",
            method="DELETE",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    OperationResponse,
                    parse_obj_as(
                        type_=OperationResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def list_pipelines(
        self,
        *,
        sort_by: typing.Optional[str] = None,
        limit: typing.Optional[int] = None,
        page: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[PipelineListResponse]:
        """
        Lists pipelines accessible to the current user.

        Parameters
        ----------
        sort_by : typing.Optional[str]

        limit : typing.Optional[int]
            Number of items to return.

        page : typing.Optional[int]
            Zero-based page number

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[PipelineListResponse]
            OK
        """
        _response = self._client_wrapper.httpx_client.request(
            "v2/pipelines",
            method="GET",
            params={
                "sortBy": sort_by,
                "limit": limit,
                "page": page,
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    PipelineListResponse,
                    parse_obj_as(
                        type_=PipelineListResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def create_pipeline(
        self,
        *,
        name: str,
        team_key: str,
        stages: typing.Sequence[str],
        icon: typing.Optional[str] = OMIT,
        description: typing.Optional[str] = OMIT,
        template_type: typing.Optional[str] = OMIT,
        fields: typing.Optional[typing.Sequence[PipelineFieldCreate]] = OMIT,
        default_permission_set_name: typing.Optional[str] = OMIT,
        sharing_restricted_to_team: typing.Optional[bool] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[None]:
        """
        Creates a basic pipeline.

        Parameters
        ----------
        name : str
            Pipeline name.

        team_key : str
            Key for the team that will own the pipeline.

        stages : typing.Sequence[str]
            Stage names in display order.

        icon : typing.Optional[str]
            Pipeline icon name.

        description : typing.Optional[str]
            Pipeline description.

        template_type : typing.Optional[str]
            Template identifier associated with the pipeline.

        fields : typing.Optional[typing.Sequence[PipelineFieldCreate]]
            Fields to create in the pipeline.

        default_permission_set_name : typing.Optional[str]
            Default permission set for users without an explicit assignment.

        sharing_restricted_to_team : typing.Optional[bool]
            Whether sharing is restricted to members of the owning team.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[None]
        """
        _response = self._client_wrapper.httpx_client.request(
            "v2/pipelines",
            method="POST",
            json={
                "name": name,
                "teamKey": team_key,
                "stages": stages,
                "icon": icon,
                "description": description,
                "templateType": template_type,
                "fields": convert_and_respect_annotation_metadata(
                    object_=fields, annotation=typing.Optional[typing.Sequence[PipelineFieldCreate]], direction="write"
                ),
                "defaultPermissionSetName": default_permission_set_name,
                "sharingRestrictedToTeam": sharing_restricted_to_team,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                return HttpResponse(response=_response, data=None)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def get_pipeline(
        self, pipeline_key: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> HttpResponse[Pipeline]:
        """
        Returns a pipeline by key.

        Parameters
        ----------
        pipeline_key : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[Pipeline]
            OK
        """
        _response = self._client_wrapper.httpx_client.request(
            f"v2/pipelines/{encode_path_param(pipeline_key)}",
            method="GET",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    Pipeline,
                    parse_obj_as(
                        type_=Pipeline,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def update_pipeline(
        self,
        pipeline_key: str,
        *,
        team_key: typing.Optional[str] = OMIT,
        icon: typing.Optional[str] = OMIT,
        name: typing.Optional[str] = OMIT,
        description: typing.Optional[str] = OMIT,
        sharing_restricted_to_team: typing.Optional[bool] = OMIT,
        stage_order: typing.Optional[typing.Sequence[str]] = OMIT,
        stage_color_theme: typing.Optional[str] = OMIT,
        custom_permission_sets: typing.Optional[typing.Dict[str, typing.Optional[PipelinePermissionSetInput]]] = OMIT,
        default_permission_set_name: typing.Optional[str] = OMIT,
        acl_entries: typing.Optional[typing.Sequence[PipelineSharingEntryInput]] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[Pipeline]:
        """
        Updates the supplied Pipeline fields. Omitted fields remain unchanged.

        Parameters
        ----------
        pipeline_key : str

        team_key : typing.Optional[str]
            New team key. Omit to keep the current team.

        icon : typing.Optional[str]
            New icon. Omit to keep the current icon.

        name : typing.Optional[str]
            New name. Omit to keep the current name.

        description : typing.Optional[str]
            New description. Omit to keep the current description.

        sharing_restricted_to_team : typing.Optional[bool]
            New team sharing restriction. Omit to keep the current value.

        stage_order : typing.Optional[typing.Sequence[str]]
            Complete stage order. Omit to keep the current order; an empty list is invalid.

        stage_color_theme : typing.Optional[str]
            New stage color theme. Omit to keep the current theme.

        custom_permission_sets : typing.Optional[typing.Dict[str, typing.Optional[PipelinePermissionSetInput]]]
            Replacement custom permission sets. Omit to keep existing sets.

        default_permission_set_name : typing.Optional[str]
            New default permission set. Omit to keep the current value.

        acl_entries : typing.Optional[typing.Sequence[PipelineSharingEntryInput]]
            Replacement sharing entries. Omit to keep existing sharing; an empty list is invalid.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[Pipeline]
            OK
        """
        _response = self._client_wrapper.httpx_client.request(
            f"v2/pipelines/{encode_path_param(pipeline_key)}",
            method="POST",
            json={
                "teamKey": team_key,
                "icon": icon,
                "name": name,
                "description": description,
                "sharingRestrictedToTeam": sharing_restricted_to_team,
                "stageOrder": stage_order,
                "stageColorTheme": stage_color_theme,
                "customPermissionSets": convert_and_respect_annotation_metadata(
                    object_=custom_permission_sets,
                    annotation=typing.Optional[typing.Dict[str, typing.Optional[PipelinePermissionSetInput]]],
                    direction="write",
                ),
                "defaultPermissionSetName": default_permission_set_name,
                "aclEntries": convert_and_respect_annotation_metadata(
                    object_=acl_entries,
                    annotation=typing.Optional[typing.Sequence[PipelineSharingEntryInput]],
                    direction="write",
                ),
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    Pipeline,
                    parse_obj_as(
                        type_=Pipeline,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def delete_pipeline(
        self, pipeline_key: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> HttpResponse[OperationResponse]:
        """
        Deletes an empty pipeline.

        Parameters
        ----------
        pipeline_key : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[OperationResponse]
            OK
        """
        _response = self._client_wrapper.httpx_client.request(
            f"v2/pipelines/{encode_path_param(pipeline_key)}",
            method="DELETE",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    OperationResponse,
                    parse_obj_as(
                        type_=OperationResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def create_pipeline_field(
        self,
        pipeline_key: str,
        *,
        name: str,
        type: FieldType,
        default_value: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[PipelineField]:
        """
        Creates a custom field in a pipeline.

        Parameters
        ----------
        pipeline_key : str

        name : str
            Field name.

        type : FieldType
            Field data type.

        default_value : typing.Optional[str]
            Initial default value. Currently only used for formula fields.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[PipelineField]
            OK
        """
        _response = self._client_wrapper.httpx_client.request(
            f"v2/pipelines/{encode_path_param(pipeline_key)}/fields",
            method="POST",
            json={
                "name": name,
                "type": type,
                "defaultValue": default_value,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    PipelineField,
                    parse_obj_as(
                        type_=PipelineField,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)


class AsyncRawPipelineClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._client_wrapper = client_wrapper

    async def list_pipeline_fields(
        self, pipeline_key: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> AsyncHttpResponse[typing.List[PipelineField]]:
        """
        Returns the fields in a pipeline in their stored order.

        Parameters
        ----------
        pipeline_key : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[typing.List[PipelineField]]
            OK
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"v1/pipelines/{encode_path_param(pipeline_key)}/fields",
            method="GET",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    typing.List[PipelineField],
                    parse_obj_as(
                        type_=typing.List[PipelineField],  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def get_pipeline_field(
        self, pipeline_key: str, field_key: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> AsyncHttpResponse[PipelineField]:
        """
        Returns a field by its key within a pipeline.

        Parameters
        ----------
        pipeline_key : str

        field_key : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[PipelineField]
            OK
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"v1/pipelines/{encode_path_param(pipeline_key)}/fields/{encode_path_param(field_key)}",
            method="GET",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    PipelineField,
                    parse_obj_as(
                        type_=PipelineField,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def update_pipeline_field(
        self,
        pipeline_key: str,
        field_key: str,
        *,
        add_only: typing.Optional[bool] = None,
        name: typing.Optional[str] = OMIT,
        default_value: typing.Optional[str] = OMIT,
        dropdown_settings: typing.Optional[PipelineFieldDropdownSettingsUpdate] = OMIT,
        tag_settings: typing.Optional[PipelineFieldTagSettingsUpdate] = OMIT,
        ai_settings: typing.Optional[PipelineFieldAiSettingsUpdate] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[PipelineField]:
        """
        Updates a field's name, default value, options, or AI settings.

        Parameters
        ----------
        pipeline_key : str

        field_key : str

        add_only : typing.Optional[bool]
            Append dropdown or tag options while retaining existing options. Defaults to false.

        name : typing.Optional[str]
            New field name.

        default_value : typing.Optional[str]
            New default value or formula.

        dropdown_settings : typing.Optional[PipelineFieldDropdownSettingsUpdate]
            Dropdown options to apply.

        tag_settings : typing.Optional[PipelineFieldTagSettingsUpdate]
            Tag options to apply.

        ai_settings : typing.Optional[PipelineFieldAiSettingsUpdate]
            AI settings to update.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[PipelineField]
            OK
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"v1/pipelines/{encode_path_param(pipeline_key)}/fields/{encode_path_param(field_key)}",
            method="POST",
            params={
                "addOnly": add_only,
            },
            json={
                "name": name,
                "defaultValue": default_value,
                "dropdownSettings": convert_and_respect_annotation_metadata(
                    object_=dropdown_settings,
                    annotation=typing.Optional[PipelineFieldDropdownSettingsUpdate],
                    direction="write",
                ),
                "tagSettings": convert_and_respect_annotation_metadata(
                    object_=tag_settings, annotation=typing.Optional[PipelineFieldTagSettingsUpdate], direction="write"
                ),
                "aiSettings": convert_and_respect_annotation_metadata(
                    object_=ai_settings, annotation=typing.Optional[PipelineFieldAiSettingsUpdate], direction="write"
                ),
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    PipelineField,
                    parse_obj_as(
                        type_=PipelineField,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def delete_pipeline_field(
        self, pipeline_key: str, field_key: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> AsyncHttpResponse[OperationResponse]:
        """
        Deletes a custom field and clears the value from all the pipeline's boxes.

        Parameters
        ----------
        pipeline_key : str

        field_key : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[OperationResponse]
            OK
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"v1/pipelines/{encode_path_param(pipeline_key)}/fields/{encode_path_param(field_key)}",
            method="DELETE",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    OperationResponse,
                    parse_obj_as(
                        type_=OperationResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def list_pipelines(
        self,
        *,
        sort_by: typing.Optional[str] = None,
        limit: typing.Optional[int] = None,
        page: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[PipelineListResponse]:
        """
        Lists pipelines accessible to the current user.

        Parameters
        ----------
        sort_by : typing.Optional[str]

        limit : typing.Optional[int]
            Number of items to return.

        page : typing.Optional[int]
            Zero-based page number

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[PipelineListResponse]
            OK
        """
        _response = await self._client_wrapper.httpx_client.request(
            "v2/pipelines",
            method="GET",
            params={
                "sortBy": sort_by,
                "limit": limit,
                "page": page,
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    PipelineListResponse,
                    parse_obj_as(
                        type_=PipelineListResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def create_pipeline(
        self,
        *,
        name: str,
        team_key: str,
        stages: typing.Sequence[str],
        icon: typing.Optional[str] = OMIT,
        description: typing.Optional[str] = OMIT,
        template_type: typing.Optional[str] = OMIT,
        fields: typing.Optional[typing.Sequence[PipelineFieldCreate]] = OMIT,
        default_permission_set_name: typing.Optional[str] = OMIT,
        sharing_restricted_to_team: typing.Optional[bool] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[None]:
        """
        Creates a basic pipeline.

        Parameters
        ----------
        name : str
            Pipeline name.

        team_key : str
            Key for the team that will own the pipeline.

        stages : typing.Sequence[str]
            Stage names in display order.

        icon : typing.Optional[str]
            Pipeline icon name.

        description : typing.Optional[str]
            Pipeline description.

        template_type : typing.Optional[str]
            Template identifier associated with the pipeline.

        fields : typing.Optional[typing.Sequence[PipelineFieldCreate]]
            Fields to create in the pipeline.

        default_permission_set_name : typing.Optional[str]
            Default permission set for users without an explicit assignment.

        sharing_restricted_to_team : typing.Optional[bool]
            Whether sharing is restricted to members of the owning team.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[None]
        """
        _response = await self._client_wrapper.httpx_client.request(
            "v2/pipelines",
            method="POST",
            json={
                "name": name,
                "teamKey": team_key,
                "stages": stages,
                "icon": icon,
                "description": description,
                "templateType": template_type,
                "fields": convert_and_respect_annotation_metadata(
                    object_=fields, annotation=typing.Optional[typing.Sequence[PipelineFieldCreate]], direction="write"
                ),
                "defaultPermissionSetName": default_permission_set_name,
                "sharingRestrictedToTeam": sharing_restricted_to_team,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                return AsyncHttpResponse(response=_response, data=None)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def get_pipeline(
        self, pipeline_key: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> AsyncHttpResponse[Pipeline]:
        """
        Returns a pipeline by key.

        Parameters
        ----------
        pipeline_key : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[Pipeline]
            OK
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"v2/pipelines/{encode_path_param(pipeline_key)}",
            method="GET",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    Pipeline,
                    parse_obj_as(
                        type_=Pipeline,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def update_pipeline(
        self,
        pipeline_key: str,
        *,
        team_key: typing.Optional[str] = OMIT,
        icon: typing.Optional[str] = OMIT,
        name: typing.Optional[str] = OMIT,
        description: typing.Optional[str] = OMIT,
        sharing_restricted_to_team: typing.Optional[bool] = OMIT,
        stage_order: typing.Optional[typing.Sequence[str]] = OMIT,
        stage_color_theme: typing.Optional[str] = OMIT,
        custom_permission_sets: typing.Optional[typing.Dict[str, typing.Optional[PipelinePermissionSetInput]]] = OMIT,
        default_permission_set_name: typing.Optional[str] = OMIT,
        acl_entries: typing.Optional[typing.Sequence[PipelineSharingEntryInput]] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[Pipeline]:
        """
        Updates the supplied Pipeline fields. Omitted fields remain unchanged.

        Parameters
        ----------
        pipeline_key : str

        team_key : typing.Optional[str]
            New team key. Omit to keep the current team.

        icon : typing.Optional[str]
            New icon. Omit to keep the current icon.

        name : typing.Optional[str]
            New name. Omit to keep the current name.

        description : typing.Optional[str]
            New description. Omit to keep the current description.

        sharing_restricted_to_team : typing.Optional[bool]
            New team sharing restriction. Omit to keep the current value.

        stage_order : typing.Optional[typing.Sequence[str]]
            Complete stage order. Omit to keep the current order; an empty list is invalid.

        stage_color_theme : typing.Optional[str]
            New stage color theme. Omit to keep the current theme.

        custom_permission_sets : typing.Optional[typing.Dict[str, typing.Optional[PipelinePermissionSetInput]]]
            Replacement custom permission sets. Omit to keep existing sets.

        default_permission_set_name : typing.Optional[str]
            New default permission set. Omit to keep the current value.

        acl_entries : typing.Optional[typing.Sequence[PipelineSharingEntryInput]]
            Replacement sharing entries. Omit to keep existing sharing; an empty list is invalid.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[Pipeline]
            OK
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"v2/pipelines/{encode_path_param(pipeline_key)}",
            method="POST",
            json={
                "teamKey": team_key,
                "icon": icon,
                "name": name,
                "description": description,
                "sharingRestrictedToTeam": sharing_restricted_to_team,
                "stageOrder": stage_order,
                "stageColorTheme": stage_color_theme,
                "customPermissionSets": convert_and_respect_annotation_metadata(
                    object_=custom_permission_sets,
                    annotation=typing.Optional[typing.Dict[str, typing.Optional[PipelinePermissionSetInput]]],
                    direction="write",
                ),
                "defaultPermissionSetName": default_permission_set_name,
                "aclEntries": convert_and_respect_annotation_metadata(
                    object_=acl_entries,
                    annotation=typing.Optional[typing.Sequence[PipelineSharingEntryInput]],
                    direction="write",
                ),
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    Pipeline,
                    parse_obj_as(
                        type_=Pipeline,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def delete_pipeline(
        self, pipeline_key: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> AsyncHttpResponse[OperationResponse]:
        """
        Deletes an empty pipeline.

        Parameters
        ----------
        pipeline_key : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[OperationResponse]
            OK
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"v2/pipelines/{encode_path_param(pipeline_key)}",
            method="DELETE",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    OperationResponse,
                    parse_obj_as(
                        type_=OperationResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def create_pipeline_field(
        self,
        pipeline_key: str,
        *,
        name: str,
        type: FieldType,
        default_value: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[PipelineField]:
        """
        Creates a custom field in a pipeline.

        Parameters
        ----------
        pipeline_key : str

        name : str
            Field name.

        type : FieldType
            Field data type.

        default_value : typing.Optional[str]
            Initial default value. Currently only used for formula fields.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[PipelineField]
            OK
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"v2/pipelines/{encode_path_param(pipeline_key)}/fields",
            method="POST",
            json={
                "name": name,
                "type": type,
                "defaultValue": default_value,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    PipelineField,
                    parse_obj_as(
                        type_=PipelineField,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)
