# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from ..types.assignee_input import AssigneeInput
from ..types.operation_response import OperationResponse
from ..types.task import Task
from ..types.task_list_response import TaskListResponse
from .raw_client import AsyncRawTasksClient, RawTasksClient

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class TasksClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawTasksClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawTasksClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawTasksClient
        """
        return self._raw_client

    def list_box_tasks(
        self,
        box_key: str,
        *,
        limit: typing.Optional[int] = None,
        page: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> TaskListResponse:
        """
        Lists tasks on a box, ordered by creation date.

        Parameters
        ----------
        box_key : str
            Key for the box whose tasks should be listed.

        limit : typing.Optional[int]
            Number of items to return. Maximum: 1000

        page : typing.Optional[int]
            Zero-based page number

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        TaskListResponse
            OK

        Examples
        --------
        from streak_crm import Streak

        client = Streak(
            token="YOUR_TOKEN",
        )
        client.tasks.list_box_tasks(
            box_key="boxKey",
        )
        """
        _response = self._raw_client.list_box_tasks(box_key, limit=limit, page=page, request_options=request_options)
        return _response.data

    def create_task(
        self,
        box_key: str,
        *,
        text: str,
        due_date: typing.Optional[int] = OMIT,
        assigned_to: typing.Optional[typing.Sequence[AssigneeInput]] = OMIT,
        meeting_key: typing.Optional[str] = OMIT,
        is_draft: typing.Optional[bool] = OMIT,
        team_contact_key: typing.Optional[str] = OMIT,
        draft: typing.Optional[bool] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> Task:
        """
        Creates a task on a box.

        Parameters
        ----------
        box_key : str
            Key for the box to create the task on.

        text : str
            Task text.

        due_date : typing.Optional[int]
            Task due date, in epoch milliseconds. Use -1 to create a task with no due date.

        assigned_to : typing.Optional[typing.Sequence[AssigneeInput]]
            Users to assign to this task. Omit to assign the task to the creator.

        meeting_key : typing.Optional[str]
            Key for the meeting this task belongs to, when any.

        is_draft : typing.Optional[bool]
            Whether to create this task as a draft. Draft tasks do not send notifications or webhooks.

        team_contact_key : typing.Optional[str]
            Key for the contact used to infer suggested task actions.

        draft : typing.Optional[bool]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        Task
            OK

        Examples
        --------
        from streak_crm import Streak

        client = Streak(
            token="YOUR_TOKEN",
        )
        client.tasks.create_task(
            box_key="boxKey",
            text="text",
        )
        """
        _response = self._raw_client.create_task(
            box_key,
            text=text,
            due_date=due_date,
            assigned_to=assigned_to,
            meeting_key=meeting_key,
            is_draft=is_draft,
            team_contact_key=team_contact_key,
            draft=draft,
            request_options=request_options,
        )
        return _response.data

    def list_upcoming_tasks(
        self,
        *,
        direction: typing.Optional[str] = None,
        include_completed: typing.Optional[bool] = None,
        limit: typing.Optional[int] = None,
        pipeline_key: typing.Optional[str] = None,
        sort_order: typing.Optional[str] = None,
        user_keys: typing.Optional[typing.Sequence[str]] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> TaskListResponse:
        """
        Lists tasks across all pipelines and boxes. By default, returns incomplete tasks assigned to the current user before tomorrow in the user's timezone, which includes today's and overdue tasks. Use userKeys, pipelineKey, includeCompleted, direction, limit, and sortOrder to page through other agenda slices.

        Parameters
        ----------
        direction : typing.Optional[str]
            Agenda direction. Accepted values are desc, past, asc, and future. Defaults to desc.

        include_completed : typing.Optional[bool]
            Whether completed tasks should be included in the returned agenda.

        limit : typing.Optional[int]
            Maximum number of tasks to return per assigned user.

        pipeline_key : typing.Optional[str]
            Key for the pipeline to filter tasks to. Omit to search across all visible pipelines.

        sort_order : typing.Optional[str]
            Opaque 30-digit sort cursor returned as task.sortOrder. Omit to use tomorrow at local midnight as the cursor boundary.

        user_keys : typing.Optional[typing.Sequence[str]]
            User keys whose assigned tasks should be returned. Omit to return tasks assigned to the current user.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        TaskListResponse
            OK

        Examples
        --------
        from streak_crm import Streak

        client = Streak(
            token="YOUR_TOKEN",
        )
        client.tasks.list_upcoming_tasks()
        """
        _response = self._raw_client.list_upcoming_tasks(
            direction=direction,
            include_completed=include_completed,
            limit=limit,
            pipeline_key=pipeline_key,
            sort_order=sort_order,
            user_keys=user_keys,
            request_options=request_options,
        )
        return _response.data

    def get_task(self, task_key: str, *, request_options: typing.Optional[RequestOptions] = None) -> Task:
        """
        Returns a single task by key.

        Parameters
        ----------
        task_key : str
            Key for the task to return.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        Task
            OK

        Examples
        --------
        from streak_crm import Streak

        client = Streak(
            token="YOUR_TOKEN",
        )
        client.tasks.get_task(
            task_key="taskKey",
        )
        """
        _response = self._raw_client.get_task(task_key, request_options=request_options)
        return _response.data

    def update_task(
        self,
        task_key: str,
        *,
        text: typing.Optional[str] = OMIT,
        due_date: typing.Optional[int] = OMIT,
        status: typing.Optional[str] = OMIT,
        assigned_to: typing.Optional[typing.Sequence[AssigneeInput]] = OMIT,
        meeting_key: typing.Optional[str] = OMIT,
        is_draft: typing.Optional[bool] = OMIT,
        draft: typing.Optional[bool] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> Task:
        """
        Updates a task by key. Omitted body fields are left unchanged.

        Parameters
        ----------
        task_key : str
            Key for the task to update.

        text : typing.Optional[str]
            New task text. Omit this field to keep existing text unchanged.

        due_date : typing.Optional[int]
            New task due date, in epoch milliseconds. Use -1 to clear the due date.

        status : typing.Optional[str]
            New task completion status. Omit this field to keep existing status unchanged.

        assigned_to : typing.Optional[typing.Sequence[AssigneeInput]]
            Replacement users assigned to this task. Omit this field to keep existing assignees unchanged.

        meeting_key : typing.Optional[str]
            Key for the meeting this task belongs to. Omit this field to keep existing meeting unchanged.

        is_draft : typing.Optional[bool]
            Whether to publish a draft task. Omit this field to keep existing draft state unchanged.

        draft : typing.Optional[bool]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        Task
            OK

        Examples
        --------
        from streak_crm import Streak

        client = Streak(
            token="YOUR_TOKEN",
        )
        client.tasks.update_task(
            task_key="taskKey",
        )
        """
        _response = self._raw_client.update_task(
            task_key,
            text=text,
            due_date=due_date,
            status=status,
            assigned_to=assigned_to,
            meeting_key=meeting_key,
            is_draft=is_draft,
            draft=draft,
            request_options=request_options,
        )
        return _response.data

    def delete_task(
        self, task_key: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> OperationResponse:
        """
        Deletes a task by key.

        Parameters
        ----------
        task_key : str
            Key for the task to delete.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        OperationResponse
            OK

        Examples
        --------
        from streak_crm import Streak

        client = Streak(
            token="YOUR_TOKEN",
        )
        client.tasks.delete_task(
            task_key="taskKey",
        )
        """
        _response = self._raw_client.delete_task(task_key, request_options=request_options)
        return _response.data


class AsyncTasksClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawTasksClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawTasksClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawTasksClient
        """
        return self._raw_client

    async def list_box_tasks(
        self,
        box_key: str,
        *,
        limit: typing.Optional[int] = None,
        page: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> TaskListResponse:
        """
        Lists tasks on a box, ordered by creation date.

        Parameters
        ----------
        box_key : str
            Key for the box whose tasks should be listed.

        limit : typing.Optional[int]
            Number of items to return. Maximum: 1000

        page : typing.Optional[int]
            Zero-based page number

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        TaskListResponse
            OK

        Examples
        --------
        import asyncio

        from streak_crm import AsyncStreak

        client = AsyncStreak(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.tasks.list_box_tasks(
                box_key="boxKey",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.list_box_tasks(
            box_key, limit=limit, page=page, request_options=request_options
        )
        return _response.data

    async def create_task(
        self,
        box_key: str,
        *,
        text: str,
        due_date: typing.Optional[int] = OMIT,
        assigned_to: typing.Optional[typing.Sequence[AssigneeInput]] = OMIT,
        meeting_key: typing.Optional[str] = OMIT,
        is_draft: typing.Optional[bool] = OMIT,
        team_contact_key: typing.Optional[str] = OMIT,
        draft: typing.Optional[bool] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> Task:
        """
        Creates a task on a box.

        Parameters
        ----------
        box_key : str
            Key for the box to create the task on.

        text : str
            Task text.

        due_date : typing.Optional[int]
            Task due date, in epoch milliseconds. Use -1 to create a task with no due date.

        assigned_to : typing.Optional[typing.Sequence[AssigneeInput]]
            Users to assign to this task. Omit to assign the task to the creator.

        meeting_key : typing.Optional[str]
            Key for the meeting this task belongs to, when any.

        is_draft : typing.Optional[bool]
            Whether to create this task as a draft. Draft tasks do not send notifications or webhooks.

        team_contact_key : typing.Optional[str]
            Key for the contact used to infer suggested task actions.

        draft : typing.Optional[bool]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        Task
            OK

        Examples
        --------
        import asyncio

        from streak_crm import AsyncStreak

        client = AsyncStreak(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.tasks.create_task(
                box_key="boxKey",
                text="text",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.create_task(
            box_key,
            text=text,
            due_date=due_date,
            assigned_to=assigned_to,
            meeting_key=meeting_key,
            is_draft=is_draft,
            team_contact_key=team_contact_key,
            draft=draft,
            request_options=request_options,
        )
        return _response.data

    async def list_upcoming_tasks(
        self,
        *,
        direction: typing.Optional[str] = None,
        include_completed: typing.Optional[bool] = None,
        limit: typing.Optional[int] = None,
        pipeline_key: typing.Optional[str] = None,
        sort_order: typing.Optional[str] = None,
        user_keys: typing.Optional[typing.Sequence[str]] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> TaskListResponse:
        """
        Lists tasks across all pipelines and boxes. By default, returns incomplete tasks assigned to the current user before tomorrow in the user's timezone, which includes today's and overdue tasks. Use userKeys, pipelineKey, includeCompleted, direction, limit, and sortOrder to page through other agenda slices.

        Parameters
        ----------
        direction : typing.Optional[str]
            Agenda direction. Accepted values are desc, past, asc, and future. Defaults to desc.

        include_completed : typing.Optional[bool]
            Whether completed tasks should be included in the returned agenda.

        limit : typing.Optional[int]
            Maximum number of tasks to return per assigned user.

        pipeline_key : typing.Optional[str]
            Key for the pipeline to filter tasks to. Omit to search across all visible pipelines.

        sort_order : typing.Optional[str]
            Opaque 30-digit sort cursor returned as task.sortOrder. Omit to use tomorrow at local midnight as the cursor boundary.

        user_keys : typing.Optional[typing.Sequence[str]]
            User keys whose assigned tasks should be returned. Omit to return tasks assigned to the current user.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        TaskListResponse
            OK

        Examples
        --------
        import asyncio

        from streak_crm import AsyncStreak

        client = AsyncStreak(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.tasks.list_upcoming_tasks()


        asyncio.run(main())
        """
        _response = await self._raw_client.list_upcoming_tasks(
            direction=direction,
            include_completed=include_completed,
            limit=limit,
            pipeline_key=pipeline_key,
            sort_order=sort_order,
            user_keys=user_keys,
            request_options=request_options,
        )
        return _response.data

    async def get_task(self, task_key: str, *, request_options: typing.Optional[RequestOptions] = None) -> Task:
        """
        Returns a single task by key.

        Parameters
        ----------
        task_key : str
            Key for the task to return.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        Task
            OK

        Examples
        --------
        import asyncio

        from streak_crm import AsyncStreak

        client = AsyncStreak(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.tasks.get_task(
                task_key="taskKey",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get_task(task_key, request_options=request_options)
        return _response.data

    async def update_task(
        self,
        task_key: str,
        *,
        text: typing.Optional[str] = OMIT,
        due_date: typing.Optional[int] = OMIT,
        status: typing.Optional[str] = OMIT,
        assigned_to: typing.Optional[typing.Sequence[AssigneeInput]] = OMIT,
        meeting_key: typing.Optional[str] = OMIT,
        is_draft: typing.Optional[bool] = OMIT,
        draft: typing.Optional[bool] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> Task:
        """
        Updates a task by key. Omitted body fields are left unchanged.

        Parameters
        ----------
        task_key : str
            Key for the task to update.

        text : typing.Optional[str]
            New task text. Omit this field to keep existing text unchanged.

        due_date : typing.Optional[int]
            New task due date, in epoch milliseconds. Use -1 to clear the due date.

        status : typing.Optional[str]
            New task completion status. Omit this field to keep existing status unchanged.

        assigned_to : typing.Optional[typing.Sequence[AssigneeInput]]
            Replacement users assigned to this task. Omit this field to keep existing assignees unchanged.

        meeting_key : typing.Optional[str]
            Key for the meeting this task belongs to. Omit this field to keep existing meeting unchanged.

        is_draft : typing.Optional[bool]
            Whether to publish a draft task. Omit this field to keep existing draft state unchanged.

        draft : typing.Optional[bool]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        Task
            OK

        Examples
        --------
        import asyncio

        from streak_crm import AsyncStreak

        client = AsyncStreak(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.tasks.update_task(
                task_key="taskKey",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.update_task(
            task_key,
            text=text,
            due_date=due_date,
            status=status,
            assigned_to=assigned_to,
            meeting_key=meeting_key,
            is_draft=is_draft,
            draft=draft,
            request_options=request_options,
        )
        return _response.data

    async def delete_task(
        self, task_key: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> OperationResponse:
        """
        Deletes a task by key.

        Parameters
        ----------
        task_key : str
            Key for the task to delete.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        OperationResponse
            OK

        Examples
        --------
        import asyncio

        from streak_crm import AsyncStreak

        client = AsyncStreak(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.tasks.delete_task(
                task_key="taskKey",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.delete_task(task_key, request_options=request_options)
        return _response.data
