# This file was auto-generated by Fern from our API Definition.

import typing
from json.decoder import JSONDecodeError

from ..core.api_error import ApiError
from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.http_response import AsyncHttpResponse, HttpResponse
from ..core.jsonable_encoder import encode_path_param
from ..core.parse_error import ParsingError
from ..core.pydantic_utilities import parse_obj_as
from ..core.request_options import RequestOptions
from ..core.serialization import convert_and_respect_annotation_metadata
from ..types.assignee_input import AssigneeInput
from ..types.operation_response import OperationResponse
from ..types.task import Task
from ..types.task_list_response import TaskListResponse
from pydantic import ValidationError

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class RawTasksClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._client_wrapper = client_wrapper

    def list_box_tasks(
        self,
        box_key: str,
        *,
        limit: typing.Optional[int] = None,
        page: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[TaskListResponse]:
        """
        Lists tasks on a box, ordered by creation date.

        Parameters
        ----------
        box_key : str
            Key for the box whose tasks should be listed.

        limit : typing.Optional[int]
            Number of items to return. Maximum: 1000

        page : typing.Optional[int]
            Zero-based page number

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[TaskListResponse]
            OK
        """
        _response = self._client_wrapper.httpx_client.request(
            f"v2/boxes/{encode_path_param(box_key)}/tasks",
            method="GET",
            params={
                "limit": limit,
                "page": page,
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    TaskListResponse,
                    parse_obj_as(
                        type_=TaskListResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def create_task(
        self,
        box_key: str,
        *,
        text: str,
        due_date: typing.Optional[int] = OMIT,
        assigned_to: typing.Optional[typing.Sequence[AssigneeInput]] = OMIT,
        meeting_key: typing.Optional[str] = OMIT,
        is_draft: typing.Optional[bool] = OMIT,
        team_contact_key: typing.Optional[str] = OMIT,
        draft: typing.Optional[bool] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[Task]:
        """
        Creates a task on a box.

        Parameters
        ----------
        box_key : str
            Key for the box to create the task on.

        text : str
            Task text.

        due_date : typing.Optional[int]
            Task due date, in epoch milliseconds. Use -1 to create a task with no due date.

        assigned_to : typing.Optional[typing.Sequence[AssigneeInput]]
            Users to assign to this task. Omit to assign the task to the creator.

        meeting_key : typing.Optional[str]
            Key for the meeting this task belongs to, when any.

        is_draft : typing.Optional[bool]
            Whether to create this task as a draft. Draft tasks do not send notifications or webhooks.

        team_contact_key : typing.Optional[str]
            Key for the contact used to infer suggested task actions.

        draft : typing.Optional[bool]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[Task]
            OK
        """
        _response = self._client_wrapper.httpx_client.request(
            f"v2/boxes/{encode_path_param(box_key)}/tasks",
            method="POST",
            json={
                "text": text,
                "dueDate": due_date,
                "assignedTo": convert_and_respect_annotation_metadata(
                    object_=assigned_to, annotation=typing.Optional[typing.Sequence[AssigneeInput]], direction="write"
                ),
                "meetingKey": meeting_key,
                "isDraft": is_draft,
                "teamContactKey": team_contact_key,
                "draft": draft,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    Task,
                    parse_obj_as(
                        type_=Task,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def list_upcoming_tasks(
        self,
        *,
        direction: typing.Optional[str] = None,
        include_completed: typing.Optional[bool] = None,
        limit: typing.Optional[int] = None,
        pipeline_key: typing.Optional[str] = None,
        sort_order: typing.Optional[str] = None,
        user_keys: typing.Optional[typing.Sequence[str]] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[TaskListResponse]:
        """
        Lists tasks across all pipelines and boxes. By default, returns incomplete tasks assigned to the current user before tomorrow in the user's timezone, which includes today's and overdue tasks. Use userKeys, pipelineKey, includeCompleted, direction, limit, and sortOrder to page through other agenda slices.

        Parameters
        ----------
        direction : typing.Optional[str]
            Agenda direction. Accepted values are desc, past, asc, and future. Defaults to desc.

        include_completed : typing.Optional[bool]
            Whether completed tasks should be included in the returned agenda.

        limit : typing.Optional[int]
            Maximum number of tasks to return per assigned user.

        pipeline_key : typing.Optional[str]
            Key for the pipeline to filter tasks to. Omit to search across all visible pipelines.

        sort_order : typing.Optional[str]
            Opaque 30-digit sort cursor returned as task.sortOrder. Omit to use tomorrow at local midnight as the cursor boundary.

        user_keys : typing.Optional[typing.Sequence[str]]
            User keys whose assigned tasks should be returned. Omit to return tasks assigned to the current user.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[TaskListResponse]
            OK
        """
        _response = self._client_wrapper.httpx_client.request(
            "v2/tasks",
            method="GET",
            params={
                "direction": direction,
                "includeCompleted": include_completed,
                "limit": limit,
                "pipelineKey": pipeline_key,
                "sortOrder": sort_order,
                "userKeys": user_keys,
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    TaskListResponse,
                    parse_obj_as(
                        type_=TaskListResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def get_task(self, task_key: str, *, request_options: typing.Optional[RequestOptions] = None) -> HttpResponse[Task]:
        """
        Returns a single task by key.

        Parameters
        ----------
        task_key : str
            Key for the task to return.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[Task]
            OK
        """
        _response = self._client_wrapper.httpx_client.request(
            f"v2/tasks/{encode_path_param(task_key)}",
            method="GET",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    Task,
                    parse_obj_as(
                        type_=Task,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def update_task(
        self,
        task_key: str,
        *,
        text: typing.Optional[str] = OMIT,
        due_date: typing.Optional[int] = OMIT,
        status: typing.Optional[str] = OMIT,
        assigned_to: typing.Optional[typing.Sequence[AssigneeInput]] = OMIT,
        meeting_key: typing.Optional[str] = OMIT,
        is_draft: typing.Optional[bool] = OMIT,
        draft: typing.Optional[bool] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[Task]:
        """
        Updates a task by key. Omitted body fields are left unchanged.

        Parameters
        ----------
        task_key : str
            Key for the task to update.

        text : typing.Optional[str]
            New task text. Omit this field to keep existing text unchanged.

        due_date : typing.Optional[int]
            New task due date, in epoch milliseconds. Use -1 to clear the due date.

        status : typing.Optional[str]
            New task completion status. Omit this field to keep existing status unchanged.

        assigned_to : typing.Optional[typing.Sequence[AssigneeInput]]
            Replacement users assigned to this task. Omit this field to keep existing assignees unchanged.

        meeting_key : typing.Optional[str]
            Key for the meeting this task belongs to. Omit this field to keep existing meeting unchanged.

        is_draft : typing.Optional[bool]
            Whether to publish a draft task. Omit this field to keep existing draft state unchanged.

        draft : typing.Optional[bool]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[Task]
            OK
        """
        _response = self._client_wrapper.httpx_client.request(
            f"v2/tasks/{encode_path_param(task_key)}",
            method="POST",
            json={
                "text": text,
                "dueDate": due_date,
                "status": status,
                "assignedTo": convert_and_respect_annotation_metadata(
                    object_=assigned_to, annotation=typing.Optional[typing.Sequence[AssigneeInput]], direction="write"
                ),
                "meetingKey": meeting_key,
                "isDraft": is_draft,
                "draft": draft,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    Task,
                    parse_obj_as(
                        type_=Task,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def delete_task(
        self, task_key: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> HttpResponse[OperationResponse]:
        """
        Deletes a task by key.

        Parameters
        ----------
        task_key : str
            Key for the task to delete.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[OperationResponse]
            OK
        """
        _response = self._client_wrapper.httpx_client.request(
            f"v2/tasks/{encode_path_param(task_key)}",
            method="DELETE",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    OperationResponse,
                    parse_obj_as(
                        type_=OperationResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)


class AsyncRawTasksClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._client_wrapper = client_wrapper

    async def list_box_tasks(
        self,
        box_key: str,
        *,
        limit: typing.Optional[int] = None,
        page: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[TaskListResponse]:
        """
        Lists tasks on a box, ordered by creation date.

        Parameters
        ----------
        box_key : str
            Key for the box whose tasks should be listed.

        limit : typing.Optional[int]
            Number of items to return. Maximum: 1000

        page : typing.Optional[int]
            Zero-based page number

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[TaskListResponse]
            OK
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"v2/boxes/{encode_path_param(box_key)}/tasks",
            method="GET",
            params={
                "limit": limit,
                "page": page,
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    TaskListResponse,
                    parse_obj_as(
                        type_=TaskListResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def create_task(
        self,
        box_key: str,
        *,
        text: str,
        due_date: typing.Optional[int] = OMIT,
        assigned_to: typing.Optional[typing.Sequence[AssigneeInput]] = OMIT,
        meeting_key: typing.Optional[str] = OMIT,
        is_draft: typing.Optional[bool] = OMIT,
        team_contact_key: typing.Optional[str] = OMIT,
        draft: typing.Optional[bool] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[Task]:
        """
        Creates a task on a box.

        Parameters
        ----------
        box_key : str
            Key for the box to create the task on.

        text : str
            Task text.

        due_date : typing.Optional[int]
            Task due date, in epoch milliseconds. Use -1 to create a task with no due date.

        assigned_to : typing.Optional[typing.Sequence[AssigneeInput]]
            Users to assign to this task. Omit to assign the task to the creator.

        meeting_key : typing.Optional[str]
            Key for the meeting this task belongs to, when any.

        is_draft : typing.Optional[bool]
            Whether to create this task as a draft. Draft tasks do not send notifications or webhooks.

        team_contact_key : typing.Optional[str]
            Key for the contact used to infer suggested task actions.

        draft : typing.Optional[bool]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[Task]
            OK
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"v2/boxes/{encode_path_param(box_key)}/tasks",
            method="POST",
            json={
                "text": text,
                "dueDate": due_date,
                "assignedTo": convert_and_respect_annotation_metadata(
                    object_=assigned_to, annotation=typing.Optional[typing.Sequence[AssigneeInput]], direction="write"
                ),
                "meetingKey": meeting_key,
                "isDraft": is_draft,
                "teamContactKey": team_contact_key,
                "draft": draft,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    Task,
                    parse_obj_as(
                        type_=Task,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def list_upcoming_tasks(
        self,
        *,
        direction: typing.Optional[str] = None,
        include_completed: typing.Optional[bool] = None,
        limit: typing.Optional[int] = None,
        pipeline_key: typing.Optional[str] = None,
        sort_order: typing.Optional[str] = None,
        user_keys: typing.Optional[typing.Sequence[str]] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[TaskListResponse]:
        """
        Lists tasks across all pipelines and boxes. By default, returns incomplete tasks assigned to the current user before tomorrow in the user's timezone, which includes today's and overdue tasks. Use userKeys, pipelineKey, includeCompleted, direction, limit, and sortOrder to page through other agenda slices.

        Parameters
        ----------
        direction : typing.Optional[str]
            Agenda direction. Accepted values are desc, past, asc, and future. Defaults to desc.

        include_completed : typing.Optional[bool]
            Whether completed tasks should be included in the returned agenda.

        limit : typing.Optional[int]
            Maximum number of tasks to return per assigned user.

        pipeline_key : typing.Optional[str]
            Key for the pipeline to filter tasks to. Omit to search across all visible pipelines.

        sort_order : typing.Optional[str]
            Opaque 30-digit sort cursor returned as task.sortOrder. Omit to use tomorrow at local midnight as the cursor boundary.

        user_keys : typing.Optional[typing.Sequence[str]]
            User keys whose assigned tasks should be returned. Omit to return tasks assigned to the current user.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[TaskListResponse]
            OK
        """
        _response = await self._client_wrapper.httpx_client.request(
            "v2/tasks",
            method="GET",
            params={
                "direction": direction,
                "includeCompleted": include_completed,
                "limit": limit,
                "pipelineKey": pipeline_key,
                "sortOrder": sort_order,
                "userKeys": user_keys,
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    TaskListResponse,
                    parse_obj_as(
                        type_=TaskListResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def get_task(
        self, task_key: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> AsyncHttpResponse[Task]:
        """
        Returns a single task by key.

        Parameters
        ----------
        task_key : str
            Key for the task to return.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[Task]
            OK
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"v2/tasks/{encode_path_param(task_key)}",
            method="GET",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    Task,
                    parse_obj_as(
                        type_=Task,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def update_task(
        self,
        task_key: str,
        *,
        text: typing.Optional[str] = OMIT,
        due_date: typing.Optional[int] = OMIT,
        status: typing.Optional[str] = OMIT,
        assigned_to: typing.Optional[typing.Sequence[AssigneeInput]] = OMIT,
        meeting_key: typing.Optional[str] = OMIT,
        is_draft: typing.Optional[bool] = OMIT,
        draft: typing.Optional[bool] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[Task]:
        """
        Updates a task by key. Omitted body fields are left unchanged.

        Parameters
        ----------
        task_key : str
            Key for the task to update.

        text : typing.Optional[str]
            New task text. Omit this field to keep existing text unchanged.

        due_date : typing.Optional[int]
            New task due date, in epoch milliseconds. Use -1 to clear the due date.

        status : typing.Optional[str]
            New task completion status. Omit this field to keep existing status unchanged.

        assigned_to : typing.Optional[typing.Sequence[AssigneeInput]]
            Replacement users assigned to this task. Omit this field to keep existing assignees unchanged.

        meeting_key : typing.Optional[str]
            Key for the meeting this task belongs to. Omit this field to keep existing meeting unchanged.

        is_draft : typing.Optional[bool]
            Whether to publish a draft task. Omit this field to keep existing draft state unchanged.

        draft : typing.Optional[bool]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[Task]
            OK
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"v2/tasks/{encode_path_param(task_key)}",
            method="POST",
            json={
                "text": text,
                "dueDate": due_date,
                "status": status,
                "assignedTo": convert_and_respect_annotation_metadata(
                    object_=assigned_to, annotation=typing.Optional[typing.Sequence[AssigneeInput]], direction="write"
                ),
                "meetingKey": meeting_key,
                "isDraft": is_draft,
                "draft": draft,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    Task,
                    parse_obj_as(
                        type_=Task,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def delete_task(
        self, task_key: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> AsyncHttpResponse[OperationResponse]:
        """
        Deletes a task by key.

        Parameters
        ----------
        task_key : str
            Key for the task to delete.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[OperationResponse]
            OK
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"v2/tasks/{encode_path_param(task_key)}",
            method="DELETE",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    OperationResponse,
                    parse_obj_as(
                        type_=OperationResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)
