# This file was auto-generated by Fern from our API Definition.

import typing

Action = typing.Union[
    typing.Literal[
        "GET",
        "UPDATE",
        "DELETE",
        "CREATE",
        "CHANGE_PERMISSIONS",
        "CHANGE_ADMINS",
        "SET_TEAM",
        "RESTRICT_SHARING",
        "OVERRIDE_SHARING_RESTRICTION",
        "OVERRIDE_VALIDATOR",
        "RESIZE",
        "HIDE",
        "FREEZE",
        "OPTIONS",
        "FORMAT",
        "ORDER",
        "SUMMARY",
        "EXPORT",
        "FLOW_PAUSE_RESUME",
        "FLOW_VIEW_LOGS",
        "GET_BOXES",
    ],
    typing.Any,
]
