# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .api_key_type import ApiKeyType


class ApiKey(UniversalBaseModel):
    api_key: typing_extensions.Annotated[
        str, FieldMetadata(alias="apiKey"), pydantic.Field(alias="apiKey", description="The API key secret value.")
    ]
    """
    The API key secret value.
    """

    key: str = pydantic.Field()
    """
    Key for this API key.
    """

    creation_timestamp: typing_extensions.Annotated[
        int,
        FieldMetadata(alias="creationTimestamp"),
        pydantic.Field(
            alias="creationTimestamp", description="Timestamp when this API key was created, in epoch milliseconds."
        ),
    ]
    """
    Timestamp when this API key was created, in epoch milliseconds.
    """

    last_saved_timestamp: typing_extensions.Annotated[
        int,
        FieldMetadata(alias="lastSavedTimestamp"),
        pydantic.Field(
            alias="lastSavedTimestamp",
            description="Timestamp when the last time this key was modified, in epoch milliseconds.",
        ),
    ]
    """
    Timestamp when the last time this key was modified, in epoch milliseconds.
    """

    key_type: typing_extensions.Annotated[
        ApiKeyType,
        FieldMetadata(alias="keyType"),
        pydantic.Field(
            alias="keyType", description="Whether this key authenticates one user or can impersonate members of a team."
        ),
    ]
    """
    Whether this key authenticates one user or can impersonate members of a team.
    """

    team_key: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="teamKey"),
        pydantic.Field(
            alias="teamKey", description="Team this key can impersonate members of. Only present for team keys."
        ),
    ] = None
    """
    Team this key can impersonate members of. Only present for team keys.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
