# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata


class CommentMention(UniversalBaseModel):
    user_key: typing_extensions.Annotated[
        str, FieldMetadata(alias="userKey"), pydantic.Field(alias="userKey", description="Key for the mentioned user.")
    ]
    """
    Key for the mentioned user.
    """

    offset: typing.Optional[int] = pydantic.Field(default=None)
    """
    Zero-based character offset where the mention starts.
    """

    length: typing.Optional[int] = pydantic.Field(default=None)
    """
    Character length of the mention.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
