# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .user_brief import UserBrief


class CommentReactionSummary(UniversalBaseModel):
    emoji: str = pydantic.Field()
    """
    Emoji used for this reaction group.
    """

    count: typing.Optional[int] = pydantic.Field(default=None)
    """
    Number of users who reacted with this emoji.
    """

    users: typing.List[UserBrief] = pydantic.Field()
    """
    Users who reacted with this emoji, ordered by oldest reaction first.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
