# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata


class ContactLinkInput(UniversalBaseModel):
    """
    A relationship to a contact.
    """

    key: str = pydantic.Field()
    """
    Key of the related contact.
    """

    is_magic_linked: typing_extensions.Annotated[
        typing.Optional[bool],
        FieldMetadata(alias="isMagicLinked"),
        pydantic.Field(alias="isMagicLinked", description="Whether the relationship was created automatically."),
    ] = None
    """
    Whether the relationship was created automatically.
    """

    creation_timestamp: typing_extensions.Annotated[
        typing.Optional[int],
        FieldMetadata(alias="creationTimestamp"),
        pydantic.Field(
            alias="creationTimestamp", description="Relationship creation timestamp, in epoch milliseconds, when known."
        ),
    ] = None
    """
    Relationship creation timestamp, in epoch milliseconds, when known.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
