# This file was auto-generated by Fern from our API Definition.

import typing

FieldType = typing.Union[
    typing.Literal[
        "TEXT_INPUT", "DROPDOWN", "CHECKBOX", "DATE", "PERSON", "FORMULA", "TAG", "TEAM_CONTACT", "TEAM_ORGANIZATION"
    ],
    typing.Any,
]
