# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .meeting_type import MeetingType


class Meeting(UniversalBaseModel):
    key: str = pydantic.Field()
    """
    Key for this meeting.
    """

    box_key: typing_extensions.Annotated[
        str,
        FieldMetadata(alias="boxKey"),
        pydantic.Field(alias="boxKey", description="Key for the box this meeting belongs to."),
    ]
    """
    Key for the box this meeting belongs to.
    """

    pipeline_key: typing_extensions.Annotated[
        str,
        FieldMetadata(alias="pipelineKey"),
        pydantic.Field(alias="pipelineKey", description="Key for the pipeline this meeting belongs to."),
    ]
    """
    Key for the pipeline this meeting belongs to.
    """

    creator_key: typing_extensions.Annotated[
        str,
        FieldMetadata(alias="creatorKey"),
        pydantic.Field(alias="creatorKey", description="Key for the user who created this meeting."),
    ]
    """
    Key for the user who created this meeting.
    """

    is_draft: typing_extensions.Annotated[
        typing.Optional[bool],
        FieldMetadata(alias="isDraft"),
        pydantic.Field(alias="isDraft", description="Whether this meeting is a draft."),
    ] = None
    """
    Whether this meeting is a draft.
    """

    task_keys: typing_extensions.Annotated[
        typing.List[str],
        FieldMetadata(alias="taskKeys"),
        pydantic.Field(alias="taskKeys", description="Task keys associated with this meeting."),
    ]
    """
    Task keys associated with this meeting.
    """

    creation_date: typing_extensions.Annotated[
        int,
        FieldMetadata(alias="creationDate"),
        pydantic.Field(
            alias="creationDate", description="Timestamp when this meeting was created, in epoch milliseconds."
        ),
    ]
    """
    Timestamp when this meeting was created, in epoch milliseconds.
    """

    meeting_type: typing_extensions.Annotated[
        MeetingType,
        FieldMetadata(alias="meetingType"),
        pydantic.Field(alias="meetingType", description="Meeting type."),
    ]
    """
    Meeting type.
    """

    start_timestamp: typing_extensions.Annotated[
        int,
        FieldMetadata(alias="startTimestamp"),
        pydantic.Field(alias="startTimestamp", description="Meeting start timestamp, in epoch milliseconds."),
    ]
    """
    Meeting start timestamp, in epoch milliseconds.
    """

    duration: typing.Optional[int] = pydantic.Field(default=None)
    """
    Meeting duration in milliseconds.
    """

    notes: str = pydantic.Field()
    """
    Meeting notes.
    """

    last_saved_timestamp: typing_extensions.Annotated[
        int,
        FieldMetadata(alias="lastSavedTimestamp"),
        pydantic.Field(
            alias="lastSavedTimestamp",
            description="Timestamp when this meeting was last persisted, in epoch milliseconds.",
        ),
    ]
    """
    Timestamp when this meeting was last persisted, in epoch milliseconds.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
