# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .organization import Organization


class OrganizationPage(UniversalBaseModel):
    """
    A page of organization records and its continuation cursor.
    """

    results: typing.List[Organization] = pydantic.Field()
    """
    Records in this page, in result order.
    """

    cursor: typing.Optional[str] = pydantic.Field(default=None)
    """
    Opaque cursor to pass to the next page request, when present.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
