# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .contact_link import ContactLink
from .organization_link import OrganizationLink


class Organization(UniversalBaseModel):
    """
    An organization shared with the team.
    """

    key: str = pydantic.Field()
    """
    Stable key for this organization.
    """

    team_key: typing_extensions.Annotated[
        str,
        FieldMetadata(alias="teamKey"),
        pydantic.Field(alias="teamKey", description="Key for the team that owns this organization."),
    ]
    """
    Key for the team that owns this organization.
    """

    name: typing.Optional[str] = pydantic.Field(default=None)
    """
    Name of the organization.
    """

    other: typing.Optional[str] = pydantic.Field(default=None)
    """
    Notes about the organization.
    """

    domains: typing.List[str] = pydantic.Field()
    """
    Website domains in their stored order.
    """

    normalized_domains: typing_extensions.Annotated[
        typing.List[str],
        FieldMetadata(alias="normalizedDomains"),
        pydantic.Field(alias="normalizedDomains", description="Stored normalized website domains."),
    ]
    """
    Stored normalized website domains.
    """

    industry: typing.Optional[str] = pydantic.Field(default=None)
    """
    Industry of the organization.
    """

    phone_numbers: typing_extensions.Annotated[
        typing.List[str],
        FieldMetadata(alias="phoneNumbers"),
        pydantic.Field(alias="phoneNumbers", description="Phone numbers in their stored order."),
    ]
    """
    Phone numbers in their stored order.
    """

    addresses: typing.List[str] = pydantic.Field()
    """
    Postal addresses in their stored order.
    """

    employee_count: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="employeeCount"),
        pydantic.Field(alias="employeeCount", description="Employee count or range as text."),
    ] = None
    """
    Employee count or range as text.
    """

    logo_url: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="logoURL"),
        pydantic.Field(alias="logoURL", description="URL of the organization logo."),
    ] = None
    """
    URL of the organization logo.
    """

    twitter_handle: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="twitterHandle"),
        pydantic.Field(alias="twitterHandle", description="Twitter profile handle."),
    ] = None
    """
    Twitter profile handle.
    """

    facebook_handle: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="facebookHandle"),
        pydantic.Field(alias="facebookHandle", description="Facebook profile handle."),
    ] = None
    """
    Facebook profile handle.
    """

    linkedin_handle: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="linkedinHandle"),
        pydantic.Field(alias="linkedinHandle", description="LinkedIn profile handle."),
    ] = None
    """
    LinkedIn profile handle.
    """

    instagram_handle: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="instagramHandle"),
        pydantic.Field(alias="instagramHandle", description="Instagram profile handle."),
    ] = None
    """
    Instagram profile handle.
    """

    last_saved_user_key: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="lastSavedUserKey"),
        pydantic.Field(alias="lastSavedUserKey", description="Key for the user who last edited this record."),
    ] = None
    """
    Key for the user who last edited this record.
    """

    creator_key: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="creatorKey"),
        pydantic.Field(alias="creatorKey", description="Key for the user who created this record."),
    ] = None
    """
    Key for the user who created this record.
    """

    creation_date: typing_extensions.Annotated[
        typing.Optional[int],
        FieldMetadata(alias="creationDate"),
        pydantic.Field(alias="creationDate", description="Time this record was first created, in epoch milliseconds."),
    ] = None
    """
    Time this record was first created, in epoch milliseconds.
    """

    version_timestamp: typing_extensions.Annotated[
        typing.Optional[int],
        FieldMetadata(alias="versionTimestamp"),
        pydantic.Field(
            alias="versionTimestamp", description="Time this version of the record was created, in epoch milliseconds."
        ),
    ] = None
    """
    Time this version of the record was created, in epoch milliseconds.
    """

    last_saved_timestamp: typing_extensions.Annotated[
        typing.Optional[int],
        FieldMetadata(alias="lastSavedTimestamp"),
        pydantic.Field(
            alias="lastSavedTimestamp", description="Time this record was last saved, in epoch milliseconds."
        ),
    ] = None
    """
    Time this record was last saved, in epoch milliseconds.
    """

    last_enrichment_timestamp: typing_extensions.Annotated[
        typing.Optional[int],
        FieldMetadata(alias="lastEnrichmentTimestamp"),
        pydantic.Field(
            alias="lastEnrichmentTimestamp",
            description="Time enrichment was last applied or reviewed, in epoch milliseconds.",
        ),
    ] = None
    """
    Time enrichment was last applied or reviewed, in epoch milliseconds.
    """

    contact_links: typing_extensions.Annotated[
        typing.List[ContactLink],
        FieldMetadata(alias="contactLinks"),
        pydantic.Field(alias="contactLinks", description="Contacts linked to this record, in their stored order."),
    ]
    """
    Contacts linked to this record, in their stored order.
    """

    org_links: typing_extensions.Annotated[
        typing.List[OrganizationLink],
        FieldMetadata(alias="orgLinks"),
        pydantic.Field(alias="orgLinks", description="Organizations linked to this record, in their stored order."),
    ]
    """
    Organizations linked to this record, in their stored order.
    """

    fields: typing.Dict[str, str] = pydantic.Field()
    """
    Custom field values keyed by field identifier.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
