# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata


class OrganizationLink(UniversalBaseModel):
    """
    A relationship to an organization.
    """

    key: str = pydantic.Field()
    """
    Stable key for the linked organization.
    """

    is_magic_linked: typing_extensions.Annotated[
        typing.Optional[bool],
        FieldMetadata(alias="isMagicLinked"),
        pydantic.Field(alias="isMagicLinked", description="Whether Streak linked this record automatically."),
    ] = None
    """
    Whether Streak linked this record automatically.
    """

    creation_timestamp: typing_extensions.Annotated[
        typing.Optional[int],
        FieldMetadata(alias="creationTimestamp"),
        pydantic.Field(
            alias="creationTimestamp", description="Time the relationship was created, in epoch milliseconds."
        ),
    ] = None
    """
    Time the relationship was created, in epoch milliseconds.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
