# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .field_type import FieldType


class PipelineFieldCreate(UniversalBaseModel):
    name: str = pydantic.Field()
    """
    Field name.
    """

    type: FieldType = pydantic.Field()
    """
    Field data type.
    """

    default_value: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="defaultValue"),
        pydantic.Field(
            alias="defaultValue", description="Initial default value. Currently only used for formula fields."
        ),
    ] = None
    """
    Initial default value. Currently only used for formula fields.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
