# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .pipeline_stage_color import PipelineStageColor


class PipelineStage(UniversalBaseModel):
    key: str = pydantic.Field()
    """
    Stage key within the pipeline.
    """

    name: str = pydantic.Field()
    """
    Stage name.
    """

    color: PipelineStageColor = pydantic.Field()
    """
    Stage color.
    """

    is_color_from_theme: typing_extensions.Annotated[
        typing.Optional[bool],
        FieldMetadata(alias="isColorFromTheme"),
        pydantic.Field(alias="isColorFromTheme", description="Whether the color is inherited from the pipeline theme."),
    ] = None
    """
    Whether the color is inherited from the pipeline theme.
    """

    box_count: typing_extensions.Annotated[
        typing.Optional[int],
        FieldMetadata(alias="boxCount"),
        pydantic.Field(alias="boxCount", description="Number of boxes currently in this stage."),
    ] = None
    """
    Number of boxes currently in this stage.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
