# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class PipelineFieldDropdownItemUpdate(UniversalBaseModel):
    """
    An existing or new dropdown option.
    """

    key: typing.Optional[str] = pydantic.Field(default=None)
    """
    Existing option key. Omit the key when adding an option.
    """

    name: typing.Optional[str] = pydantic.Field(default=None)
    """
    Nonempty option label.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
