# This file was auto-generated by Fern from our API Definition.

import typing

PipelineConditionalCheck = typing.Union[
    typing.Literal[
        "NONE", "ASSIGNED_TO", "FIELD_COMPARISON", "STAGE", "CREATOR", "BOX_UPDATE", "BOX_VIEW", "UNARCHIVED"
    ],
    typing.Any,
]
