# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .pipeline_field_tag_item_update import PipelineFieldTagItemUpdate


class PipelineFieldTagSettingsUpdate(UniversalBaseModel):
    """
    Tag options in the requested order.
    """

    tags: typing.Optional[typing.List[PipelineFieldTagItemUpdate]] = pydantic.Field(default=None)
    """
    Tags to keep or add. An empty list removes all tags unless addOnly is true.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
