# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .search_results import SearchResults


class SearchResponse(UniversalBaseModel):
    """
    Response returned by the legacy v1 search endpoint.
    """

    results: SearchResults = pydantic.Field()
    """
    Search results grouped by entity type.
    """

    query: typing.Optional[str] = pydantic.Field(default=None)
    """
    The query string used for full-text searches. Null when searching by exact box name.
    """

    page: typing.Optional[int] = pydantic.Field(default=None)
    """
    Zero-based page number returned by the search.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
