# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .reminder_status import ReminderStatus
from .task_action import TaskAction
from .task_status import TaskStatus
from .user_brief import UserBrief


class Task(UniversalBaseModel):
    """
    Task attached to a box, including assignment, due date, status, and suggested actions.
    """

    key: str = pydantic.Field()
    """
    Key for this task.
    """

    box_key: typing_extensions.Annotated[
        str,
        FieldMetadata(alias="boxKey"),
        pydantic.Field(alias="boxKey", description="Key for the box this task belongs to."),
    ]
    """
    Key for the box this task belongs to.
    """

    pipeline_key: typing_extensions.Annotated[
        str,
        FieldMetadata(alias="pipelineKey"),
        pydantic.Field(alias="pipelineKey", description="Key for the pipeline this task belongs to."),
    ]
    """
    Key for the pipeline this task belongs to.
    """

    creator_key: typing_extensions.Annotated[
        str,
        FieldMetadata(alias="creatorKey"),
        pydantic.Field(alias="creatorKey", description="Key for the user who created this task."),
    ]
    """
    Key for the user who created this task.
    """

    creator: UserBrief = pydantic.Field()
    """
    The user who created this task.
    """

    assigned_to: typing_extensions.Annotated[
        typing.List[UserBrief],
        FieldMetadata(alias="assignedTo"),
        pydantic.Field(
            alias="assignedTo",
            description="Users assigned to this task. Tasks created without explicit assignees are assigned to the creator by default.",
        ),
    ]
    """
    Users assigned to this task. Tasks created without explicit assignees are assigned to the creator by default.
    """

    creation_date: typing_extensions.Annotated[
        int,
        FieldMetadata(alias="creationDate"),
        pydantic.Field(
            alias="creationDate", description="Timestamp when this task was created, in epoch milliseconds."
        ),
    ]
    """
    Timestamp when this task was created, in epoch milliseconds.
    """

    last_saved_timestamp: typing_extensions.Annotated[
        int,
        FieldMetadata(alias="lastSavedTimestamp"),
        pydantic.Field(
            alias="lastSavedTimestamp",
            description="Timestamp when this task was last persisted, in epoch milliseconds.",
        ),
    ]
    """
    Timestamp when this task was last persisted, in epoch milliseconds.
    """

    last_status_change_date: typing_extensions.Annotated[
        int,
        FieldMetadata(alias="lastStatusChangeDate"),
        pydantic.Field(
            alias="lastStatusChangeDate",
            description="Timestamp when this task status last changed, in epoch milliseconds.",
        ),
    ]
    """
    Timestamp when this task status last changed, in epoch milliseconds.
    """

    due_date: typing_extensions.Annotated[
        typing.Optional[int],
        FieldMetadata(alias="dueDate"),
        pydantic.Field(alias="dueDate", description="Task due date, in epoch milliseconds."),
    ] = None
    """
    Task due date, in epoch milliseconds.
    """

    text: str = pydantic.Field()
    """
    Task text.
    """

    actions: typing.Optional[typing.List[TaskAction]] = pydantic.Field(default=None)
    """
    Suggested actions inferred from the task text.
    """

    status: TaskStatus = pydantic.Field()
    """
    Task completion status.
    """

    reminder_status: typing_extensions.Annotated[
        ReminderStatus,
        FieldMetadata(alias="reminderStatus"),
        pydantic.Field(alias="reminderStatus", description="Task reminder status."),
    ]
    """
    Task reminder status.
    """

    meeting_key: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="meetingKey"),
        pydantic.Field(alias="meetingKey", description="Key for the meeting this task belongs to, when any."),
    ] = None
    """
    Key for the meeting this task belongs to, when any.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
