# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .action_type import ActionType
from .contact import Contact


class TaskAction(UniversalBaseModel):
    """
    Suggested action inferred from task text.
    """

    type: ActionType = pydantic.Field()
    """
    Suggested action type.
    """

    value: str = pydantic.Field()
    """
    Suggested action value, such as an email address or phone number.
    """

    contact: Contact = pydantic.Field()
    """
    Contact this action is associated with.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
