# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .team_field_update import TeamFieldUpdate


class TeamFieldSettingsUpdate(UniversalBaseModel):
    """
    Complete custom-field replacement for team contacts or organizations.
    """

    fields: typing.Dict[str, TeamFieldUpdate] = pydantic.Field()
    """
    Complete custom-field map keyed by stable field key.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
