# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .team_based_permissions import TeamBasedPermissions
from .team_field_settings import TeamFieldSettings
from .team_member import TeamMember


class Team(UniversalBaseModel):
    """
    A Streak team and its membership, sharing, billing, and directory settings.
    """

    key: str = pydantic.Field()
    """
    Key for this team.
    """

    creation_date: typing_extensions.Annotated[
        int,
        FieldMetadata(alias="creationDate"),
        pydantic.Field(alias="creationDate", description="Timestamp when the team was created, in epoch milliseconds."),
    ]
    """
    Timestamp when the team was created, in epoch milliseconds.
    """

    creator: str = pydantic.Field()
    """
    Key for the user who created the team.
    """

    members: typing.List[TeamMember] = pydantic.Field()
    """
    Members of the team and their team roles.
    """

    name: str = pydantic.Field()
    """
    Display name for the team.
    """

    sharing_restricted_to_team: typing_extensions.Annotated[
        typing.Optional[bool],
        FieldMetadata(alias="sharingRestrictedToTeam"),
        pydantic.Field(alias="sharingRestrictedToTeam", description="Whether sharing outside the team is restricted."),
    ] = None
    """
    Whether sharing outside the team is restricted.
    """

    automatically_approve_join_requests: typing_extensions.Annotated[
        typing.Optional[bool],
        FieldMetadata(alias="automaticallyApproveJoinRequests"),
        pydantic.Field(
            alias="automaticallyApproveJoinRequests",
            description="Whether requests to join the team are approved automatically.",
        ),
    ] = None
    """
    Whether requests to join the team are approved automatically.
    """

    automatically_send_invoice_emails: typing_extensions.Annotated[
        typing.Optional[bool],
        FieldMetadata(alias="automaticallySendInvoiceEmails"),
        pydantic.Field(
            alias="automaticallySendInvoiceEmails",
            description="Whether invoice emails are sent automatically for this team.",
        ),
    ] = None
    """
    Whether invoice emails are sent automatically for this team.
    """

    emails_to_send_invoice_to: typing_extensions.Annotated[
        typing.List[str],
        FieldMetadata(alias="emailsToSendInvoiceTo"),
        pydantic.Field(
            alias="emailsToSendInvoiceTo", description="Additional email addresses that receive team invoices."
        ),
    ]
    """
    Additional email addresses that receive team invoices.
    """

    billing_admin: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="billingAdmin"),
        pydantic.Field(alias="billingAdmin", description="Key for the user who administers billing for this team."),
    ] = None
    """
    Key for the user who administers billing for this team.
    """

    last_saved_timestamp: typing_extensions.Annotated[
        int,
        FieldMetadata(alias="lastSavedTimestamp"),
        pydantic.Field(
            alias="lastSavedTimestamp", description="Timestamp when the team was last persisted, in epoch milliseconds."
        ),
    ]
    """
    Timestamp when the team was last persisted, in epoch milliseconds.
    """

    contact_org_list_permissions: typing_extensions.Annotated[
        typing.Dict[str, TeamBasedPermissions],
        FieldMetadata(alias="contactOrgListPermissions"),
        pydantic.Field(
            alias="contactOrgListPermissions",
            description="Permissions for the team's system contact and organization lists.",
        ),
    ]
    """
    Permissions for the team's system contact and organization lists.
    """

    contact_settings: typing_extensions.Annotated[
        TeamFieldSettings,
        FieldMetadata(alias="contactSettings"),
        pydantic.Field(alias="contactSettings", description="Custom contact field definitions for this team."),
    ]
    """
    Custom contact field definitions for this team.
    """

    organization_settings: typing_extensions.Annotated[
        TeamFieldSettings,
        FieldMetadata(alias="organizationSettings"),
        pydantic.Field(
            alias="organizationSettings", description="Custom organization field definitions for this team."
        ),
    ]
    """
    Custom organization field definitions for this team.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
