# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata


class TeamAclEntryUpdate(UniversalBaseModel):
    """
    One explicit user permission in a team list ACL.
    """

    user_key: typing_extensions.Annotated[
        str,
        FieldMetadata(alias="userKey"),
        pydantic.Field(alias="userKey", description="Key for the user receiving the permission."),
    ]
    """
    Key for the user receiving the permission.
    """

    permission_set_name: typing_extensions.Annotated[
        str,
        FieldMetadata(alias="permissionSetName"),
        pydantic.Field(alias="permissionSetName", description="Permission set assigned to the user."),
    ]
    """
    Permission set assigned to the user.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
