# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .team_field import TeamField


class TeamFieldSettings(UniversalBaseModel):
    """
    Custom field definitions for a team's contacts or organizations.
    """

    fields: typing.Dict[str, TeamField] = pydantic.Field()
    """
    Custom fields keyed by their stable field key.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
