# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata


class TeamAclEntry(UniversalBaseModel):
    """
    A team member's explicit permission for a system list.
    """

    user_key: typing_extensions.Annotated[
        str,
        FieldMetadata(alias="userKey"),
        pydantic.Field(alias="userKey", description="Key for the user receiving the permission."),
    ]
    """
    Key for the user receiving the permission.
    """

    permission_set_name: typing_extensions.Annotated[
        str,
        FieldMetadata(alias="permissionSetName"),
        pydantic.Field(alias="permissionSetName", description="Permission set assigned to the user."),
    ]
    """
    Permission set assigned to the user.
    """

    is_read_only: typing_extensions.Annotated[
        typing.Optional[bool],
        FieldMetadata(alias="isReadOnly"),
        pydantic.Field(
            alias="isReadOnly", description="Whether the permission is fixed and cannot be edited by the requester."
        ),
    ] = None
    """
    Whether the permission is fixed and cannot be edited by the requester.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
