# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .team_acl_entry_update import TeamAclEntryUpdate


class TeamBasedPermissionsUpdate(UniversalBaseModel):
    """
    Partial permission update for one system team list.
    """

    default_permission_set_name: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="defaultPermissionSetName"),
        pydantic.Field(
            alias="defaultPermissionSetName",
            description="New default permission set. Omit to leave the default unchanged.",
        ),
    ] = None
    """
    New default permission set. Omit to leave the default unchanged.
    """

    acl_entries: typing_extensions.Annotated[
        typing.Optional[typing.List[TeamAclEntryUpdate]],
        FieldMetadata(alias="aclEntries"),
        pydantic.Field(
            alias="aclEntries",
            description="Complete user override list. Omit to leave overrides unchanged; send an empty list to clear them.",
        ),
    ] = None
    """
    Complete user override list. Omit to leave overrides unchanged; send an empty list to clear them.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
