# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .team_acl_entry import TeamAclEntry


class TeamBasedPermissions(UniversalBaseModel):
    """
    Default and user-specific permissions for a system team list.
    """

    default_permission_set_name: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="defaultPermissionSetName"),
        pydantic.Field(
            alias="defaultPermissionSetName",
            description="Permission set applied to team members without an explicit override.",
        ),
    ] = None
    """
    Permission set applied to team members without an explicit override.
    """

    acl_entries: typing_extensions.Annotated[
        typing.List[TeamAclEntry],
        FieldMetadata(alias="aclEntries"),
        pydantic.Field(
            alias="aclEntries", description="User permission overrides in the wire shape used by team sharing controls."
        ),
    ]
    """
    User permission overrides in the wire shape used by team sharing controls.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
