# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .field_type import FieldType
from .team_dropdown_settings import TeamDropdownSettings
from .team_tag_settings import TeamTagSettings


class TeamField(UniversalBaseModel):
    """
    A custom contact or organization field definition.
    """

    name: str = pydantic.Field()
    """
    Display name for the field.
    """

    key: str = pydantic.Field()
    """
    Stable key for the field.
    """

    type: FieldType = pydantic.Field()
    """
    Data type stored by the field.
    """

    default_value: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="defaultValue"),
        pydantic.Field(alias="defaultValue", description="Default textual field value, when one is configured."),
    ] = None
    """
    Default textual field value, when one is configured.
    """

    last_default_value_updated_timestamp: typing_extensions.Annotated[
        typing.Optional[int],
        FieldMetadata(alias="lastDefaultValueUpdatedTimestamp"),
        pydantic.Field(
            alias="lastDefaultValueUpdatedTimestamp",
            description="Timestamp when the default value last changed, in epoch milliseconds.",
        ),
    ] = None
    """
    Timestamp when the default value last changed, in epoch milliseconds.
    """

    last_updated_timestamp: typing_extensions.Annotated[
        typing.Optional[int],
        FieldMetadata(alias="lastUpdatedTimestamp"),
        pydantic.Field(
            alias="lastUpdatedTimestamp",
            description="Timestamp when the field definition last changed, in epoch milliseconds.",
        ),
    ] = None
    """
    Timestamp when the field definition last changed, in epoch milliseconds.
    """

    dropdown_settings: typing_extensions.Annotated[
        typing.Optional[TeamDropdownSettings],
        FieldMetadata(alias="dropdownSettings"),
        pydantic.Field(alias="dropdownSettings", description="Allowed dropdown options for a dropdown field."),
    ] = None
    """
    Allowed dropdown options for a dropdown field.
    """

    tag_settings: typing_extensions.Annotated[
        typing.Optional[TeamTagSettings],
        FieldMetadata(alias="tagSettings"),
        pydantic.Field(alias="tagSettings", description="Allowed tags for a tag field."),
    ] = None
    """
    Allowed tags for a tag field.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
