# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class TeamDropdownItem(UniversalBaseModel):
    """
    One option in a team dropdown field.
    """

    key: str = pydantic.Field()
    """
    Stable key for the option.
    """

    name: str = pydantic.Field()
    """
    Display name for the option.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
