# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata


class UserBrief(UniversalBaseModel):
    user_key: typing_extensions.Annotated[
        str, FieldMetadata(alias="userKey"), pydantic.Field(alias="userKey", description="Key for this user.")
    ]
    """
    Key for this user.
    """

    email: typing.Optional[str] = pydantic.Field(default=None)
    """
    User email address, when available.
    """

    display_name: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="displayName"),
        pydantic.Field(alias="displayName", description="Short display name for this user, when available."),
    ] = None
    """
    Short display name for this user, when available.
    """

    full_name: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="fullName"),
        pydantic.Field(alias="fullName", description="Full display name for this user, when available."),
    ] = None
    """
    Full display name for this user, when available.
    """

    given_name: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="givenName"),
        pydantic.Field(alias="givenName", description="Given name for this user, when available."),
    ] = None
    """
    Given name for this user, when available.
    """

    avatar_url: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="avatarUrl"),
        pydantic.Field(alias="avatarUrl", description="Avatar image URL for this user, when available."),
    ] = None
    """
    Avatar image URL for this user, when available.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
