# This file was auto-generated by Fern from our API Definition.

import typing

WorkflowTheme = typing.Union[
    typing.Literal[
        "DEFAULT",
        "STREAK",
        "RAINBOW_SATURATED",
        "RAINBOW_FADED",
        "TRAFFIC_LIGHT_SATURATED",
        "TRAFFIC_LIGHT_FADED",
        "LAKESIDE_SATURATED",
        "LAKESIDE_FADED",
        "SUNSET_SATURATED",
        "SUNSET_FADED",
        "SUMMER_SATURATED",
        "SUMMER_FADED",
        "HALLOWEEN_SATURATED",
        "HALLOWEEN_FADED",
        "GREYSCALE",
        "BLUEGREY",
        "RED",
        "YELLOWORANGE",
        "GREEN",
        "TEAL",
        "CYAN",
        "BLUE",
        "INDIGO",
        "DEEPPURPLE",
        "VIOLET",
        "PINK",
    ],
    typing.Any,
]
